/**
 * GENERATED by scripts/gen-widget-contract.js from scripts/contract/widget-contract.js — do not edit.
 *
 * The v2 widget payload as the app writes it. A field marked optional
 * here may be left out when it equals its default; the native readers
 * fill the default in. See the contract file for the rules.
 */

export const WIDGET_CONTRACT_VERSION = 2;

export type WidgetContractEid = 'fitr' | 'adha';

export type WidgetContractPrayerStatus =
  | 'on-time'
  | 'late'
  | 'missed'
  | 'qadha';

export type WidgetContractReaderMode = 'mushaf' | 'translation';

export type WidgetContractAlertModeKind = 'adhan' | 'notification' | 'silent';

export type WidgetContractLiveActivityDesign =
  | 'timeline'
  | 'countdown'
  | 'markers';

export type WidgetContractTasbihAction = 'inc' | 'reset' | 'next';

/**
 * Everything the home-screen widgets draw. Written by the app, read on every
 * widget redraw.
 */
export type WidgetContractPayload = {
  /** Always 2 for this shape. */
  schemaVersion: number;
  /**
   * The app's language tag (`sv`, `ar`). Native chrome resolves its own
   * strings against it, so one widget never speaks two languages.
   */
  language?: string;
  /** How to write a time. */
  clock?: WidgetContractClock;
  /** Short place label. */
  locationName?: string;
  /**
   * Today first, then the days after it. Readers pick the entry whose
   * `dateKey` is the device's local date, so a widget keeps rolling forward
   * without the app.
   */
  days: WidgetContractDay[];
  /** Jumuʿah, Ramadan, Eid accents. */
  seasonal?: WidgetContractSeasonal | null;
  /** Today's five with their journal status — the Log Today widget. */
  today?: WidgetContractToday | null;
  /** Streak and the practice grid. Absent means "do not draw", never zero. */
  practice?: WidgetContractPractice | null;
  /** Where the reader left off, and what the khatmah asks of today. */
  reading?: WidgetContractReading | null;
  /** Today's Hijri date and the month after it. */
  hijri?: WidgetContractHijri | null;
  /** The dhikr counter, for the Tasbih widget. */
  tasbih?: WidgetContractTasbih | null;
};

/**
 * The user's clock, resolved by the app (Settings → Appearance, else the
 * device). Digits are always Latin; only the day-period marker is localised,
 * exactly as src/utils/clockFormat.ts writes it.
 */
export type WidgetContractClock = {
  /** 12-hour clock. */
  hour12?: boolean;
  /** Morning marker in the app language. */
  am?: string;
  /** Afternoon marker in the app language. */
  pm?: string;
  /** Marker before the digits (下午5:31). */
  periodFirst?: boolean;
};

/** One local calendar day of prayer times. */
export type WidgetContractDay = {
  /** Local YYYY-MM-DD. */
  dateKey: string;
  /**
   * The device's UTC offset at local noon of this date when the app built it.
   * A reader whose own offset for the date differs is looking at times
   * computed under rules that no longer apply (#56).
   */
  utcOffsetMinutes?: number | null;
  /** Short day label ("Wed, Apr 9"). */
  label?: string;
  /** The five ṣalāh, Fajr to ʿIshāʾ. */
  prayers: WidgetContractRow[];
  /** Absent when the user turned Sunrise off. */
  sunrise?: WidgetContractRow | null;
  /**
   * The night marks the user turned on — Islamic Midnight, the Last Third,
   * the First Third — as the app groups them with this day.
   */
  extras?: WidgetContractRow[];
  /**
   * True for a day the app had no times for, filled with the day before's.
   * Only its Fajr is offered as "next", exactly as the app does.
   */
  estimated?: boolean;
};

/** One time on one day. */
export type WidgetContractRow = {
  /** `Fajr`, `Sunrise`, `Midnight`, … — never localised. */
  key: string;
  /** Full localised name. */
  name?: string;
  /** Short label for narrow layouts. */
  abbr?: string;
  /**
   * Minutes after local midnight of the day: 0–1439, or 1440 and more for a
   * night mark that falls after the midnight ending the day (the First Third,
   * some nights). Null when the time does not occur at this latitude; draw a
   * dash.
   */
  minutes?: number | null;
};

/** Seasonal accents. */
export type WidgetContractSeasonal = {
  /** Friday before Maghrib. */
  jumuah?: boolean;
  /** Inside Ramadan. */
  ramadan?: boolean;
  /** Eid day, or null. */
  eid?: WidgetContractEid | null;
};

/** Today's five as the Log Today widget needs them. */
export type WidgetContractToday = {
  /**
   * Local YYYY-MM-DD. A widget that slept through midnight must not draw
   * yesterday's ticks as today's.
   */
  dateKey: string;
  logged?: number;
  loggable?: number;
  /** Missed today and not yet made up. */
  owed?: number;
  prayers?: WidgetContractTodayPrayer[];
};

/** One prayer on the Log Today widget. */
export type WidgetContractTodayPrayer = {
  /** Journal prayer key. */
  key: string;
  /** Localised name. */
  name?: string;
  /** Its time today, as `Row.minutes`. */
  minutes?: number | null;
  /** Journal status; null when nothing is recorded. */
  status?: WidgetContractPrayerStatus | null;
  /** Its time has arrived; only a due prayer takes a tap. */
  due?: boolean;
};

/** Practice history. */
export type WidgetContractPractice = {
  streak?: number;
  bestStreak?: number;
  /** Of the five, how many are logged today. */
  loggedToday?: number;
  /** Missed and not yet made up, all time. */
  owed?: number;
  /**
   * Sunnah kept this month as a fraction; null before there is a denominator.
   */
  sunnahRate?: number | null;
  fastsThisMonth?: number;
  /** Oldest first, ending today; empty days omitted. */
  days?: WidgetContractPracticeDay[];
  /**
   * First day with a prayer entry, YYYY-MM-DD. Before it an empty square
   * means "not started yet", after it "not filled in".
   */
  since?: string | null;
};

/**
 * One day's marks on the practice grid. Short keys: up to 210 of these ride
 * in every payload.
 */
export type WidgetContractPracticeDay = {
  /** Local YYYY-MM-DD. */
  d: string;
  /**
   * Weighted score ×100 — on-time 100, late 70, qadha 45 — summed over the
   * five, capped at 500.
   */
  kw?: number;
  /** How many of the five carry any entry. */
  l?: number;
  /** A prayer recorded missed and not made up. */
  m?: boolean;
  /** A completed fast. */
  f?: boolean;
  /** Sunnah units kept. */
  s?: number;
};

/** The Continue Reading widget. */
export type WidgetContractReading = {
  surah?: number;
  /** Localised surah name. */
  surahName?: string;
  ayah?: number;
  page?: number;
  juz?: number;
  pagesRead?: number;
  totalPages?: number;
  bookmarks?: number;
  /** Epoch ms of the last page turn. */
  lastReadAt?: number | null;
  /**
   * Which reader a tap opens — decided by the app, which knows whether the
   * muṣḥaf is on disk.
   */
  mode?: WidgetContractReaderMode;
  khatmah?: WidgetContractKhatmah | null;
  /** False when the Qurʾān has never been opened. */
  started?: boolean;
  /** The muṣḥaf page images are on disk. */
  downloaded?: boolean;
};

/** Today's share of the khatmah plan. */
export type WidgetContractKhatmah = {
  /** 1-based day of the plan. */
  day?: number;
  targetDays?: number;
  pagesToday?: number;
  doneToday?: number;
  behindBy?: number;
  daysLeft?: number;
  /** Pages left unread behind the reader. */
  skipped?: number;
};

/** Today's Hijri date. */
export type WidgetContractHijri = {
  day: number;
  month: number;
  year: number;
  monthName?: string;
  /** The whole date, localised. */
  label?: string;
  nextMonthName?: string;
  nextMonthInDays?: number;
};

/** The dhikr counter. */
export type WidgetContractTasbih = {
  presetId?: string;
  /** Localised transliteration. */
  label?: string;
  arabic?: string;
  count?: number;
  /** 0 means open counting. */
  target?: number;
  unbounded?: boolean;
  /** Position in the preset cycle. */
  index?: number;
  /** Cycle length. */
  total?: number;
  /** Every preset's count, in order. */
  counts?: number[];
  /** Every preset's label — the widget steps the cycle in its own process. */
  labels?: string[];
  targets?: number[];
  unboundedFlags?: boolean[];
  /** Beads counted today, across presets. */
  todayTotal?: number;
  todayRounds?: number;
};

/**
 * What a Live Activity draws — the iOS Lock Screen card and Dynamic Island,
 * and the Android pinned notification — as one payload built once for both
 * (docs/rewrite-plan.md, step 1.5). Before it there were two, built in two
 * places, with the next prayer as an instant in seconds on one and
 * milliseconds on the other. Times are wall clock, as the widgets' are; each
 * native works out "next" and "previous" for the minute it draws at.
 */
export type WidgetContractLiveActivity = {
  /** Always 2 for this shape. */
  schemaVersion: number;
  /** The app's language tag. */
  language?: string;
  /** How to write a time. */
  clock?: WidgetContractClock;
  /**
   * The widget payload's days, today first, each row carrying its localised
   * full name.
   */
  days: WidgetContractDay[];
  /**
   * The Hijri date of each day, localised. Android heads the notification
   * with the one the next prayer falls on.
   */
  hijri?: WidgetContractDayText[];
  /**
   * What each prayer's alert does, for the Android lock-screen alert button.
   */
  alertModes?: WidgetContractAlertMode[];
  /** Accent and style. */
  appearance?: WidgetContractLiveActivityAppearance;
  /** What only the Android notification needs. */
  android?: WidgetContractLiveActivityAndroid;
  /**
   * Words the Android notification draws, in the app language — the thirteen
   * locales live in the app.
   */
  words?: WidgetContractLiveActivityWords;
};

/** A line of text that belongs to one day. */
export type WidgetContractDayText = {
  /** Local YYYY-MM-DD. */
  dateKey: string;
  text?: string;
};

/** What one prayer does when its time comes. */
export type WidgetContractAlertMode = {
  /** Row key. */
  key: string;
  /** As Settings → Notifications shows it. */
  mode: WidgetContractAlertModeKind;
};

/** How the Live Activity is tinted and laid out. */
export type WidgetContractLiveActivityAppearance = {
  /** The app accent's light swatch, #RRGGBB. */
  accentHex?: string;
  /** iOS: follow the system tint (Liquid Glass) instead of the accent. */
  systemTinted?: boolean;
  /**
   * Android: follow the Material You accent, re-read natively on each repost.
   */
  systemAccent?: boolean;
  /** "Tinted surfaces": the accent becomes the card's background. */
  tinted?: boolean;
  /** Android: which of the three layouts. */
  design?: WidgetContractLiveActivityDesign;
};

/** The Android notification's own settings. */
export type WidgetContractLiveActivityAndroid = {
  /** Offer the button that changes the next alert once. */
  alertActionEnabled?: boolean;
  /** Offer the hide/show-on-lock-screen button. */
  aodActionEnabled?: boolean;
  /** The notification channel an adhan alert posts to. */
  adhanChannelId?: string;
  /** The adhan chosen. */
  adhanSoundId?: string;
  /** The channel a plain alert posts to. */
  defaultChannelId?: string;
};

/** Localised words for the Android notification. */
export type WidgetContractLiveActivityWords = {
  /** The foreground service line. */
  fgsText?: string;
  alertLabelAdhan?: string;
  alertLabelNotification?: string;
  alertLabelSilent?: string;
  /** "once", after a changed alert. */
  alertOnceWord?: string;
  aodHideLabel?: string;
  aodShowLabel?: string;
  nowWord?: string;
  inWord?: string;
  atWord?: string;
  /** The body of the alert the button posts. */
  atPrayerBody?: string;
};

/**
 * One Log Today tap, queued by the widget until the app drains it. Same wire
 * shape as v1.
 */
export type WidgetContractLogQueueEntry = {
  /** Local YYYY-MM-DD the tap was for. */
  d: string;
  /** Journal prayer key. */
  p: string;
  /**
   * Epoch ms of the tap. Read with its fraction dropped: widgets before the
   * contract wrote a fractional Double here, and a tap queued by one must
   * survive the update.
   */
  t: number;
};

/** One Tasbih widget action. Same wire shape as v1. */
export type WidgetContractTasbihQueueEntry = {
  /** Action. */
  a: WidgetContractTasbihAction;
  /** Epoch ms. Read with its fraction dropped, as the log tap is. */
  t: number;
  /**
   * Run length for coalesced taps; absent means one. A long so an absurd
   * count still reads, and is clamped by the rule rather than dropped by the
   * reader.
   */
  n?: number | null;
};

// ── Reading ─────────────────────────────────────────────────────

/**
 * The reference readers: the rules the Swift and Kotlin readers follow, in
 * the language the golden fixtures (contract-tests/) are written from. Each
 * returns null when a required field is missing or mistyped, fills defaults,
 * and omits nulls.
 */
export function readWidgetContractPayload(
  input: unknown,
): WidgetContractPayload | null {
  if (!wcIsObject(input)) return null;
  const schemaVersionRead = wcInt(input.schemaVersion);
  if (schemaVersionRead == null) return null;
  const daysRead = wcList(input.days, x => readWidgetContractDay(x));
  if (daysRead == null) return null;
  const out: WidgetContractPayload = {
    schemaVersion: schemaVersionRead,
    language: wcString(input.language) ?? '',
    clock:
      readWidgetContractClock(input.clock) ??
      (readWidgetContractClock({}) as WidgetContractClock),
    locationName: wcString(input.locationName) ?? '',
    days: daysRead,
  };
  const seasonalRead = readWidgetContractSeasonal(input.seasonal);
  if (seasonalRead != null) out.seasonal = seasonalRead;
  const todayRead = readWidgetContractToday(input.today);
  if (todayRead != null) out.today = todayRead;
  const practiceRead = readWidgetContractPractice(input.practice);
  if (practiceRead != null) out.practice = practiceRead;
  const readingRead = readWidgetContractReading(input.reading);
  if (readingRead != null) out.reading = readingRead;
  const hijriRead = readWidgetContractHijri(input.hijri);
  if (hijriRead != null) out.hijri = hijriRead;
  const tasbihRead = readWidgetContractTasbih(input.tasbih);
  if (tasbihRead != null) out.tasbih = tasbihRead;
  return out;
}

export function readWidgetContractClock(
  input: unknown,
): WidgetContractClock | null {
  if (!wcIsObject(input)) return null;
  const out: WidgetContractClock = {
    hour12: wcBool(input.hour12) ?? false,
    am: wcString(input.am) ?? 'AM',
    pm: wcString(input.pm) ?? 'PM',
    periodFirst: wcBool(input.periodFirst) ?? false,
  };
  return out;
}

export function readWidgetContractDay(
  input: unknown,
): WidgetContractDay | null {
  if (!wcIsObject(input)) return null;
  const dateKeyRead = wcString(input.dateKey);
  if (dateKeyRead == null) return null;
  const prayersRead = wcList(input.prayers, x => readWidgetContractRow(x));
  if (prayersRead == null) return null;
  const out: WidgetContractDay = {
    dateKey: dateKeyRead,
    label: wcString(input.label) ?? '',
    prayers: prayersRead,
    extras: wcList(input.extras, x => readWidgetContractRow(x)) ?? [],
    estimated: wcBool(input.estimated) ?? false,
  };
  const utcOffsetMinutesRead = wcInt(input.utcOffsetMinutes);
  if (utcOffsetMinutesRead != null) out.utcOffsetMinutes = utcOffsetMinutesRead;
  const sunriseRead = readWidgetContractRow(input.sunrise);
  if (sunriseRead != null) out.sunrise = sunriseRead;
  return out;
}

export function readWidgetContractRow(
  input: unknown,
): WidgetContractRow | null {
  if (!wcIsObject(input)) return null;
  const keyRead = wcString(input.key);
  if (keyRead == null) return null;
  const out: WidgetContractRow = {
    key: keyRead,
    name: wcString(input.name) ?? '',
    abbr: wcString(input.abbr) ?? '',
  };
  const minutesRead = wcInt(input.minutes);
  if (minutesRead != null) out.minutes = minutesRead;
  return out;
}

export function readWidgetContractSeasonal(
  input: unknown,
): WidgetContractSeasonal | null {
  if (!wcIsObject(input)) return null;
  const out: WidgetContractSeasonal = {
    jumuah: wcBool(input.jumuah) ?? false,
    ramadan: wcBool(input.ramadan) ?? false,
  };
  const eidRead = wcEnum(input.eid, ['fitr', 'adha'] as const);
  if (eidRead != null) out.eid = eidRead;
  return out;
}

export function readWidgetContractToday(
  input: unknown,
): WidgetContractToday | null {
  if (!wcIsObject(input)) return null;
  const dateKeyRead = wcString(input.dateKey);
  if (dateKeyRead == null) return null;
  const out: WidgetContractToday = {
    dateKey: dateKeyRead,
    logged: wcInt(input.logged) ?? 0,
    loggable: wcInt(input.loggable) ?? 0,
    owed: wcInt(input.owed) ?? 0,
    prayers: wcList(input.prayers, x => readWidgetContractTodayPrayer(x)) ?? [],
  };
  return out;
}

export function readWidgetContractTodayPrayer(
  input: unknown,
): WidgetContractTodayPrayer | null {
  if (!wcIsObject(input)) return null;
  const keyRead = wcString(input.key);
  if (keyRead == null) return null;
  const out: WidgetContractTodayPrayer = {
    key: keyRead,
    name: wcString(input.name) ?? '',
    due: wcBool(input.due) ?? false,
  };
  const minutesRead = wcInt(input.minutes);
  if (minutesRead != null) out.minutes = minutesRead;
  const statusRead = wcEnum(input.status, [
    'on-time',
    'late',
    'missed',
    'qadha',
  ] as const);
  if (statusRead != null) out.status = statusRead;
  return out;
}

export function readWidgetContractPractice(
  input: unknown,
): WidgetContractPractice | null {
  if (!wcIsObject(input)) return null;
  const out: WidgetContractPractice = {
    streak: wcInt(input.streak) ?? 0,
    bestStreak: wcInt(input.bestStreak) ?? 0,
    loggedToday: wcInt(input.loggedToday) ?? 0,
    owed: wcInt(input.owed) ?? 0,
    fastsThisMonth: wcInt(input.fastsThisMonth) ?? 0,
    days: wcList(input.days, x => readWidgetContractPracticeDay(x)) ?? [],
  };
  const sunnahRateRead = wcDouble(input.sunnahRate);
  if (sunnahRateRead != null) out.sunnahRate = sunnahRateRead;
  const sinceRead = wcString(input.since);
  if (sinceRead != null) out.since = sinceRead;
  return out;
}

export function readWidgetContractPracticeDay(
  input: unknown,
): WidgetContractPracticeDay | null {
  if (!wcIsObject(input)) return null;
  const dRead = wcString(input.d);
  if (dRead == null) return null;
  const out: WidgetContractPracticeDay = {
    d: dRead,
    kw: wcInt(input.kw) ?? 0,
    l: wcInt(input.l) ?? 0,
    m: wcBool(input.m) ?? false,
    f: wcBool(input.f) ?? false,
    s: wcInt(input.s) ?? 0,
  };
  return out;
}

export function readWidgetContractReading(
  input: unknown,
): WidgetContractReading | null {
  if (!wcIsObject(input)) return null;
  const out: WidgetContractReading = {
    surah: wcInt(input.surah) ?? 1,
    surahName: wcString(input.surahName) ?? '',
    ayah: wcInt(input.ayah) ?? 1,
    page: wcInt(input.page) ?? 1,
    juz: wcInt(input.juz) ?? 1,
    pagesRead: wcInt(input.pagesRead) ?? 0,
    totalPages: wcInt(input.totalPages) ?? 604,
    bookmarks: wcInt(input.bookmarks) ?? 0,
    mode:
      wcEnum(input.mode, ['mushaf', 'translation'] as const) ?? 'translation',
    started: wcBool(input.started) ?? false,
    downloaded: wcBool(input.downloaded) ?? false,
  };
  const lastReadAtRead = wcLong(input.lastReadAt);
  if (lastReadAtRead != null) out.lastReadAt = lastReadAtRead;
  const khatmahRead = readWidgetContractKhatmah(input.khatmah);
  if (khatmahRead != null) out.khatmah = khatmahRead;
  return out;
}

export function readWidgetContractKhatmah(
  input: unknown,
): WidgetContractKhatmah | null {
  if (!wcIsObject(input)) return null;
  const out: WidgetContractKhatmah = {
    day: wcInt(input.day) ?? 1,
    targetDays: wcInt(input.targetDays) ?? 0,
    pagesToday: wcInt(input.pagesToday) ?? 0,
    doneToday: wcInt(input.doneToday) ?? 0,
    behindBy: wcInt(input.behindBy) ?? 0,
    daysLeft: wcInt(input.daysLeft) ?? 0,
    skipped: wcInt(input.skipped) ?? 0,
  };
  return out;
}

export function readWidgetContractHijri(
  input: unknown,
): WidgetContractHijri | null {
  if (!wcIsObject(input)) return null;
  const dayRead = wcInt(input.day);
  if (dayRead == null) return null;
  const monthRead = wcInt(input.month);
  if (monthRead == null) return null;
  const yearRead = wcInt(input.year);
  if (yearRead == null) return null;
  const out: WidgetContractHijri = {
    day: dayRead,
    month: monthRead,
    year: yearRead,
    monthName: wcString(input.monthName) ?? '',
    label: wcString(input.label) ?? '',
    nextMonthName: wcString(input.nextMonthName) ?? '',
    nextMonthInDays: wcInt(input.nextMonthInDays) ?? 0,
  };
  return out;
}

export function readWidgetContractTasbih(
  input: unknown,
): WidgetContractTasbih | null {
  if (!wcIsObject(input)) return null;
  const out: WidgetContractTasbih = {
    presetId: wcString(input.presetId) ?? '',
    label: wcString(input.label) ?? '',
    arabic: wcString(input.arabic) ?? '',
    count: wcInt(input.count) ?? 0,
    target: wcInt(input.target) ?? 0,
    unbounded: wcBool(input.unbounded) ?? false,
    index: wcInt(input.index) ?? 0,
    total: wcInt(input.total) ?? 0,
    counts: wcList(input.counts, x => wcInt(x)) ?? [],
    labels: wcList(input.labels, x => wcString(x)) ?? [],
    targets: wcList(input.targets, x => wcInt(x)) ?? [],
    unboundedFlags: wcList(input.unboundedFlags, x => wcBool(x)) ?? [],
    todayTotal: wcInt(input.todayTotal) ?? 0,
    todayRounds: wcInt(input.todayRounds) ?? 0,
  };
  return out;
}

export function readWidgetContractLiveActivity(
  input: unknown,
): WidgetContractLiveActivity | null {
  if (!wcIsObject(input)) return null;
  const schemaVersionRead = wcInt(input.schemaVersion);
  if (schemaVersionRead == null) return null;
  const daysRead = wcList(input.days, x => readWidgetContractDay(x));
  if (daysRead == null) return null;
  const out: WidgetContractLiveActivity = {
    schemaVersion: schemaVersionRead,
    language: wcString(input.language) ?? '',
    clock:
      readWidgetContractClock(input.clock) ??
      (readWidgetContractClock({}) as WidgetContractClock),
    days: daysRead,
    hijri: wcList(input.hijri, x => readWidgetContractDayText(x)) ?? [],
    alertModes:
      wcList(input.alertModes, x => readWidgetContractAlertMode(x)) ?? [],
    appearance:
      readWidgetContractLiveActivityAppearance(input.appearance) ??
      (readWidgetContractLiveActivityAppearance(
        {},
      ) as WidgetContractLiveActivityAppearance),
    android:
      readWidgetContractLiveActivityAndroid(input.android) ??
      (readWidgetContractLiveActivityAndroid(
        {},
      ) as WidgetContractLiveActivityAndroid),
    words:
      readWidgetContractLiveActivityWords(input.words) ??
      (readWidgetContractLiveActivityWords(
        {},
      ) as WidgetContractLiveActivityWords),
  };
  return out;
}

export function readWidgetContractDayText(
  input: unknown,
): WidgetContractDayText | null {
  if (!wcIsObject(input)) return null;
  const dateKeyRead = wcString(input.dateKey);
  if (dateKeyRead == null) return null;
  const out: WidgetContractDayText = {
    dateKey: dateKeyRead,
    text: wcString(input.text) ?? '',
  };
  return out;
}

export function readWidgetContractAlertMode(
  input: unknown,
): WidgetContractAlertMode | null {
  if (!wcIsObject(input)) return null;
  const keyRead = wcString(input.key);
  if (keyRead == null) return null;
  const modeRead = wcEnum(input.mode, [
    'adhan',
    'notification',
    'silent',
  ] as const);
  if (modeRead == null) return null;
  const out: WidgetContractAlertMode = {
    key: keyRead,
    mode: modeRead,
  };
  return out;
}

export function readWidgetContractLiveActivityAppearance(
  input: unknown,
): WidgetContractLiveActivityAppearance | null {
  if (!wcIsObject(input)) return null;
  const out: WidgetContractLiveActivityAppearance = {
    accentHex: wcString(input.accentHex) ?? '#22c55e',
    systemTinted: wcBool(input.systemTinted) ?? false,
    systemAccent: wcBool(input.systemAccent) ?? false,
    tinted: wcBool(input.tinted) ?? false,
    design:
      wcEnum(input.design, ['timeline', 'countdown', 'markers'] as const) ??
      'timeline',
  };
  return out;
}

export function readWidgetContractLiveActivityAndroid(
  input: unknown,
): WidgetContractLiveActivityAndroid | null {
  if (!wcIsObject(input)) return null;
  const out: WidgetContractLiveActivityAndroid = {
    alertActionEnabled: wcBool(input.alertActionEnabled) ?? false,
    aodActionEnabled: wcBool(input.aodActionEnabled) ?? true,
    adhanChannelId: wcString(input.adhanChannelId) ?? 'prayer-times-default',
    adhanSoundId: wcString(input.adhanSoundId) ?? 'default',
    defaultChannelId:
      wcString(input.defaultChannelId) ?? 'prayer-times-default',
  };
  return out;
}

export function readWidgetContractLiveActivityWords(
  input: unknown,
): WidgetContractLiveActivityWords | null {
  if (!wcIsObject(input)) return null;
  const out: WidgetContractLiveActivityWords = {
    fgsText: wcString(input.fgsText) ?? '',
    alertLabelAdhan: wcString(input.alertLabelAdhan) ?? '',
    alertLabelNotification: wcString(input.alertLabelNotification) ?? '',
    alertLabelSilent: wcString(input.alertLabelSilent) ?? '',
    alertOnceWord: wcString(input.alertOnceWord) ?? '',
    aodHideLabel: wcString(input.aodHideLabel) ?? '',
    aodShowLabel: wcString(input.aodShowLabel) ?? '',
    nowWord: wcString(input.nowWord) ?? '',
    inWord: wcString(input.inWord) ?? '',
    atWord: wcString(input.atWord) ?? '',
    atPrayerBody: wcString(input.atPrayerBody) ?? '',
  };
  return out;
}

export function readWidgetContractLogQueueEntry(
  input: unknown,
): WidgetContractLogQueueEntry | null {
  if (!wcIsObject(input)) return null;
  const dRead = wcString(input.d);
  if (dRead == null) return null;
  const pRead = wcString(input.p);
  if (pRead == null) return null;
  const tRead = wcLongTruncated(input.t);
  if (tRead == null) return null;
  const out: WidgetContractLogQueueEntry = {
    d: dRead,
    p: pRead,
    t: tRead,
  };
  return out;
}

export function readWidgetContractTasbihQueueEntry(
  input: unknown,
): WidgetContractTasbihQueueEntry | null {
  if (!wcIsObject(input)) return null;
  const aRead = wcEnum(input.a, ['inc', 'reset', 'next'] as const);
  if (aRead == null) return null;
  const tRead = wcLongTruncated(input.t);
  if (tRead == null) return null;
  const out: WidgetContractTasbihQueueEntry = {
    a: aRead,
    t: tRead,
  };
  const nRead = wcLong(input.n);
  if (nRead != null) out.n = nRead;
  return out;
}

function wcIsObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

function wcString(v: unknown): string | undefined {
  return typeof v === 'string' ? v : undefined;
}

function wcBool(v: unknown): boolean | undefined {
  return typeof v === 'boolean' ? v : undefined;
}

/** A whole number, below 9e15 in size, as every platform reads one. */
function wcLong(v: unknown): number | undefined {
  return typeof v === 'number' && Number.isInteger(v) && Math.abs(v) < 9e15
    ? v
    : undefined;
}

/**
 * A `truncate` long: any finite number below 9e15, its fraction dropped.
 * For values a writer once stored as a fractional Double (epoch ms), so
 * an entry already on disk still reads.
 */
function wcLongTruncated(v: unknown): number | undefined {
  return typeof v === 'number' && Number.isFinite(v) && Math.abs(v) < 9e15
    ? Math.trunc(v)
    : undefined;
}

/** An `int` is 32-bit everywhere, because Kotlin reads it as Int. */
function wcInt(v: unknown): number | undefined {
  const n = wcLong(v);
  return n !== undefined && n >= -2147483648 && n <= 2147483647 ? n : undefined;
}

function wcDouble(v: unknown): number | undefined {
  return typeof v === 'number' && Number.isFinite(v) ? v : undefined;
}

function wcEnum<T extends string>(
  v: unknown,
  values: readonly T[],
): T | undefined {
  return typeof v === 'string' && (values as readonly string[]).includes(v)
    ? (v as T)
    : undefined;
}

function wcList<T>(
  v: unknown,
  element: (x: unknown) => T | null | undefined,
): T[] | undefined {
  if (!Array.isArray(v)) return undefined;
  const out: T[] = [];
  for (const x of v) {
    const read = element(x);
    if (read != null) out.push(read);
  }
  return out;
}
