/**
 * GENERATED by scripts/gen-widget-contract.js from scripts/contract/widget-contract.js — do not edit.
 *
 * The v2 widget payload as the app writes it. A field marked optional
 * here may be left out when it equals its default; the native readers
 * fill the default in. See the contract file for the rules.
 */

export const WIDGET_CONTRACT_VERSION = 2;

export type WidgetContractEid = 'fitr' | 'adha';

export type WidgetContractPrayerStatus =
  | 'on-time'
  | 'late'
  | 'missed'
  | 'qadha';

export type WidgetContractReaderMode = 'mushaf' | 'translation';

export type WidgetContractTasbihAction = 'inc' | 'reset' | 'next';

/**
 * Everything the home-screen widgets draw. Written by the app, read on every
 * widget redraw.
 */
export type WidgetContractPayload = {
  /** Always 2 for this shape. */
  schemaVersion: number;
  /** Epoch ms when the app wrote it. */
  builtAt?: number;
  /**
   * The app's language tag (`sv`, `ar`). Native chrome resolves its own
   * strings against it, so one widget never speaks two languages.
   */
  language?: string;
  /** How to write a time. */
  clock?: WidgetContractClock;
  /** Short place label. */
  locationName?: string;
  /**
   * Today first, then the days after it. Readers pick the entry whose
   * `dateKey` is the device's local date, so a widget keeps rolling forward
   * without the app.
   */
  days: WidgetContractDay[];
  /** Jumuʿah, Ramadan, Eid accents. */
  seasonal?: WidgetContractSeasonal | null;
  /** Today's five with their journal status — the Log Today widget. */
  today?: WidgetContractToday | null;
  /** Streak and the practice grid. Absent means "do not draw", never zero. */
  practice?: WidgetContractPractice | null;
  /** Where the reader left off, and what the khatmah asks of today. */
  reading?: WidgetContractReading | null;
  /** Today's Hijri date and the month after it. */
  hijri?: WidgetContractHijri | null;
  /** The dhikr counter, for the Tasbih widget. */
  tasbih?: WidgetContractTasbih | null;
};

/**
 * The user's clock, resolved by the app (Settings → Appearance, else the
 * device). Digits are always Latin; only the day-period marker is localised,
 * exactly as src/utils/clockFormat.ts writes it.
 */
export type WidgetContractClock = {
  /** 12-hour clock. */
  hour12?: boolean;
  /** Morning marker in the app language. */
  am?: string;
  /** Afternoon marker in the app language. */
  pm?: string;
  /** Marker before the digits (下午5:31). */
  periodFirst?: boolean;
};

/** One local calendar day of prayer times. */
export type WidgetContractDay = {
  /** Local YYYY-MM-DD. */
  dateKey: string;
  /**
   * The device's UTC offset at local noon of this date when the app built it.
   * A reader whose own offset for the date differs is looking at times
   * computed under rules that no longer apply (#56).
   */
  utcOffsetMinutes?: number | null;
  /** Short day label ("Wed, Apr 9"). */
  label?: string;
  /** The five ṣalāh, Fajr to ʿIshāʾ. */
  prayers: WidgetContractRow[];
  /** Absent when the user turned Sunrise off. */
  sunrise?: WidgetContractRow | null;
  /**
   * The night marks the user turned on, each on the calendar date it falls.
   */
  extras?: WidgetContractRow[];
};

/** One time on one day. */
export type WidgetContractRow = {
  /** `Fajr`, `Sunrise`, `Midnight`, … — never localised. */
  key: string;
  /** Full localised name. */
  name?: string;
  /** Short label for narrow layouts. */
  abbr?: string;
  /**
   * Minutes after local midnight of the day, 0–1439. Null when the time does
   * not occur at this latitude; draw a dash.
   */
  minutes?: number | null;
};

/** Seasonal accents. */
export type WidgetContractSeasonal = {
  /** Friday before Maghrib. */
  jumuah?: boolean;
  /** Inside Ramadan. */
  ramadan?: boolean;
  /** Eid day, or null. */
  eid?: WidgetContractEid | null;
};

/** Today's five as the Log Today widget needs them. */
export type WidgetContractToday = {
  /**
   * Local YYYY-MM-DD. A widget that slept through midnight must not draw
   * yesterday's ticks as today's.
   */
  dateKey: string;
  logged?: number;
  loggable?: number;
  /** Missed today and not yet made up. */
  owed?: number;
  prayers?: WidgetContractTodayPrayer[];
};

/** One prayer on the Log Today widget. */
export type WidgetContractTodayPrayer = {
  /** Journal prayer key. */
  key: string;
  /** Localised name. */
  name?: string;
  /** Its time today, as `Row.minutes`. */
  minutes?: number | null;
  /** Journal status; null when nothing is recorded. */
  status?: WidgetContractPrayerStatus | null;
  /** Its time has arrived; only a due prayer takes a tap. */
  due?: boolean;
};

/** Practice history. */
export type WidgetContractPractice = {
  streak?: number;
  bestStreak?: number;
  /** Of the five, how many are logged today. */
  loggedToday?: number;
  /** Missed and not yet made up, all time. */
  owed?: number;
  /**
   * Sunnah kept this month as a fraction; null before there is a denominator.
   */
  sunnahRate?: number | null;
  fastsThisMonth?: number;
  /** Oldest first, ending today; empty days omitted. */
  days?: WidgetContractPracticeDay[];
  /**
   * First day with a prayer entry, YYYY-MM-DD. Before it an empty square
   * means "not started yet", after it "not filled in".
   */
  since?: string | null;
};

/**
 * One day's marks on the practice grid. Short keys: up to 210 of these ride
 * in every payload.
 */
export type WidgetContractPracticeDay = {
  /** Local YYYY-MM-DD. */
  d: string;
  /**
   * Weighted score ×100 — on-time 100, late 70, qadha 45 — summed over the
   * five, capped at 500.
   */
  kw?: number;
  /** How many of the five carry any entry. */
  l?: number;
  /** A prayer recorded missed and not made up. */
  m?: boolean;
  /** A completed fast. */
  f?: boolean;
  /** Sunnah units kept. */
  s?: number;
};

/** The Continue Reading widget. */
export type WidgetContractReading = {
  surah?: number;
  /** Localised surah name. */
  surahName?: string;
  ayah?: number;
  page?: number;
  juz?: number;
  pagesRead?: number;
  totalPages?: number;
  bookmarks?: number;
  /** Epoch ms of the last page turn. */
  lastReadAt?: number | null;
  /**
   * Which reader a tap opens — decided by the app, which knows whether the
   * muṣḥaf is on disk.
   */
  mode?: WidgetContractReaderMode;
  khatmah?: WidgetContractKhatmah | null;
  /** False when the Qurʾān has never been opened. */
  started?: boolean;
  /** The muṣḥaf page images are on disk. */
  downloaded?: boolean;
};

/** Today's share of the khatmah plan. */
export type WidgetContractKhatmah = {
  /** 1-based day of the plan. */
  day?: number;
  targetDays?: number;
  pagesToday?: number;
  doneToday?: number;
  behindBy?: number;
  daysLeft?: number;
  /** Pages left unread behind the reader. */
  skipped?: number;
};

/** Today's Hijri date. */
export type WidgetContractHijri = {
  day: number;
  month: number;
  year: number;
  monthName?: string;
  /** The whole date, localised. */
  label?: string;
  nextMonthName?: string;
  nextMonthInDays?: number;
};

/** The dhikr counter. */
export type WidgetContractTasbih = {
  presetId?: string;
  /** Localised transliteration. */
  label?: string;
  arabic?: string;
  count?: number;
  /** 0 means open counting. */
  target?: number;
  unbounded?: boolean;
  /** Position in the preset cycle. */
  index?: number;
  /** Cycle length. */
  total?: number;
  /** Every preset's count, in order. */
  counts?: number[];
  /** Every preset's label — the widget steps the cycle in its own process. */
  labels?: string[];
  targets?: number[];
  unboundedFlags?: boolean[];
  /** Beads counted today, across presets. */
  todayTotal?: number;
  todayRounds?: number;
};

/**
 * One Log Today tap, queued by the widget until the app drains it. Same wire
 * shape as v1.
 */
export type WidgetContractLogQueueEntry = {
  /** Local YYYY-MM-DD the tap was for. */
  d: string;
  /** Journal prayer key. */
  p: string;
  /** Epoch ms of the tap. */
  t: number;
};

/** One Tasbih widget action. Same wire shape as v1. */
export type WidgetContractTasbihQueueEntry = {
  /** Action. */
  a: WidgetContractTasbihAction;
  /** Epoch ms. */
  t: number;
  /** Run length for coalesced taps; absent means one. */
  n?: number | null;
};
