// GENERATED by scripts/gen-widget-contract.js from scripts/contract/widget-contract.js — do not edit.
//
// The v2 widget payload and the queues back to the app. Every reader here
// is lenient: a required field that is missing or mistyped makes its
// object unreadable (null); anything else falls back to its default or
// null; a list drops the elements it cannot read. Formatting and time
// maths live in WallClock.kt, never here.

package com.prayer_times.contract

import org.json.JSONArray
import org.json.JSONException
import org.json.JSONObject

object WidgetContract {
  const val VERSION = 2

  /**
   * A JSON array of objects at the top level — the queues back to the app —
   * keeping every element that reads and dropping the rest, the rule every
   * generated list follows. Null only when `json` is not an array at all.
   */
  fun <T> readList(json: String?, element: (JSONObject?) -> T?): List<T>? {
    val a =
      try {
        JSONArray(json ?: return null)
      } catch (e: JSONException) {
        return null
      }
    val out = ArrayList<T>(a.length())
    for (i in 0 until a.length()) element(a.optJSONObject(i))?.let { out.add(it) }
    return out
  }

  enum class Eid(val wire: String) {
    FITR("fitr"),
    ADHA("adha");

    companion object {
      fun fromWire(s: String?): Eid? = entries.firstOrNull { it.wire == s }
    }
  }

  enum class PrayerStatus(val wire: String) {
    ON_TIME("on-time"),
    LATE("late"),
    MISSED("missed"),
    QADHA("qadha");

    companion object {
      fun fromWire(s: String?): PrayerStatus? = entries.firstOrNull { it.wire == s }
    }
  }

  enum class ReaderMode(val wire: String) {
    MUSHAF("mushaf"),
    TRANSLATION("translation");

    companion object {
      fun fromWire(s: String?): ReaderMode? = entries.firstOrNull { it.wire == s }
    }
  }

  enum class TasbihAction(val wire: String) {
    INC("inc"),
    RESET("reset"),
    NEXT("next");

    companion object {
      fun fromWire(s: String?): TasbihAction? = entries.firstOrNull { it.wire == s }
    }
  }

  /**
   * Everything the home-screen widgets draw. Written by the app, read on
   * every widget redraw.
   */
  data class Payload(
    /** Always 2 for this shape. */
    val schemaVersion: Int,
    /**
     * The app's language tag (`sv`, `ar`). Native chrome resolves its own
     * strings against it, so one widget never speaks two languages.
     */
    val language: String = "",
    /** How to write a time. */
    val clock: Clock = Clock(),
    /** Short place label. */
    val locationName: String = "",
    /**
     * Today first, then the days after it. Readers pick the entry whose
     * `dateKey` is the device's local date, so a widget keeps rolling forward
     * without the app.
     */
    val days: List<Day>,
    /** Jumuʿah, Ramadan, Eid accents. */
    val seasonal: Seasonal? = null,
    /** Today's five with their journal status — the Log Today widget. */
    val today: Today? = null,
    /**
     * Streak and the practice grid. Absent means "do not draw", never zero.
     */
    val practice: Practice? = null,
    /** Where the reader left off, and what the khatmah asks of today. */
    val reading: Reading? = null,
    /** Today's Hijri date and the month after it. */
    val hijri: Hijri? = null,
    /** The dhikr counter, for the Tasbih widget. */
    val tasbih: Tasbih? = null,
  ) {
    fun toJson(): JSONObject = JSONObject().apply {
      put("schemaVersion", schemaVersion)
      put("language", language)
      put("clock", clock.toJson())
      put("locationName", locationName)
      put("days", JSONArray().apply { days.forEach { put(it.toJson()) } })
      seasonal?.let { put("seasonal", it.toJson()) }
      today?.let { put("today", it.toJson()) }
      practice?.let { put("practice", it.toJson()) }
      reading?.let { put("reading", it.toJson()) }
      hijri?.let { put("hijri", it.toJson()) }
      tasbih?.let { put("tasbih", it.toJson()) }
    }

    companion object {
      fun fromJson(o: JSONObject?): Payload? {
        if (o == null) return null
        return Payload(
          schemaVersion = o.wcRaw("schemaVersion").wcAsInt() ?: return null,
          language = o.wcString("language") ?: "",
          clock = Clock.fromJson(o.wcRaw("clock") as? JSONObject) ?: Clock(),
          locationName = o.wcString("locationName") ?: "",
          days = o.wcList("days") { Day.fromJson(it as? JSONObject) } ?: return null,
          seasonal = Seasonal.fromJson(o.wcRaw("seasonal") as? JSONObject),
          today = Today.fromJson(o.wcRaw("today") as? JSONObject),
          practice = Practice.fromJson(o.wcRaw("practice") as? JSONObject),
          reading = Reading.fromJson(o.wcRaw("reading") as? JSONObject),
          hijri = Hijri.fromJson(o.wcRaw("hijri") as? JSONObject),
          tasbih = Tasbih.fromJson(o.wcRaw("tasbih") as? JSONObject),
        )
      }

      fun parse(json: String?): Payload? =
        try {
          if (json.isNullOrEmpty()) null else fromJson(JSONObject(json))
        } catch (e: JSONException) {
          null
        }
    }
  }

  /**
   * The user's clock, resolved by the app (Settings → Appearance, else the
   * device). Digits are always Latin; only the day-period marker is
   * localised, exactly as src/utils/clockFormat.ts writes it.
   */
  data class Clock(
    /** 12-hour clock. */
    val hour12: Boolean = false,
    /** Morning marker in the app language. */
    val am: String = "AM",
    /** Afternoon marker in the app language. */
    val pm: String = "PM",
    /** Marker before the digits (下午5:31). */
    val periodFirst: Boolean = false,
  ) {
    fun toJson(): JSONObject = JSONObject().apply {
      put("hour12", hour12)
      put("am", am)
      put("pm", pm)
      put("periodFirst", periodFirst)
    }

    companion object {
      fun fromJson(o: JSONObject?): Clock? {
        if (o == null) return null
        return Clock(
          hour12 = o.wcBool("hour12") ?: false,
          am = o.wcString("am") ?: "AM",
          pm = o.wcString("pm") ?: "PM",
          periodFirst = o.wcBool("periodFirst") ?: false,
        )
      }

      fun parse(json: String?): Clock? =
        try {
          if (json.isNullOrEmpty()) null else fromJson(JSONObject(json))
        } catch (e: JSONException) {
          null
        }
    }
  }

  /** One local calendar day of prayer times. */
  data class Day(
    /** Local YYYY-MM-DD. */
    val dateKey: String,
    /**
     * The device's UTC offset at local noon of this date when the app built
     * it. A reader whose own offset for the date differs is looking at times
     * computed under rules that no longer apply (#56).
     */
    val utcOffsetMinutes: Int? = null,
    /** Short day label ("Wed, Apr 9"). */
    val label: String = "",
    /** The five ṣalāh, Fajr to ʿIshāʾ. */
    val prayers: List<Row>,
    /** Absent when the user turned Sunrise off. */
    val sunrise: Row? = null,
    /**
     * The night marks the user turned on — Islamic Midnight, the Last Third,
     * the First Third — as the app groups them with this day.
     */
    val extras: List<Row> = emptyList(),
    /**
     * True for a day the app had no times for, filled with the day before's.
     * Only its Fajr is offered as "next", exactly as the app does.
     */
    val estimated: Boolean = false,
  ) {
    fun toJson(): JSONObject = JSONObject().apply {
      put("dateKey", dateKey)
      utcOffsetMinutes?.let { put("utcOffsetMinutes", it) }
      put("label", label)
      put("prayers", JSONArray().apply { prayers.forEach { put(it.toJson()) } })
      sunrise?.let { put("sunrise", it.toJson()) }
      put("extras", JSONArray().apply { extras.forEach { put(it.toJson()) } })
      put("estimated", estimated)
    }

    companion object {
      fun fromJson(o: JSONObject?): Day? {
        if (o == null) return null
        return Day(
          dateKey = o.wcString("dateKey") ?: return null,
          utcOffsetMinutes = o.wcRaw("utcOffsetMinutes").wcAsInt(),
          label = o.wcString("label") ?: "",
          prayers = o.wcList("prayers") { Row.fromJson(it as? JSONObject) } ?: return null,
          sunrise = Row.fromJson(o.wcRaw("sunrise") as? JSONObject),
          extras = o.wcList("extras") { Row.fromJson(it as? JSONObject) } ?: emptyList(),
          estimated = o.wcBool("estimated") ?: false,
        )
      }

      fun parse(json: String?): Day? =
        try {
          if (json.isNullOrEmpty()) null else fromJson(JSONObject(json))
        } catch (e: JSONException) {
          null
        }
    }
  }

  /** One time on one day. */
  data class Row(
    /** `Fajr`, `Sunrise`, `Midnight`, … — never localised. */
    val key: String,
    /** Full localised name. */
    val name: String = "",
    /** Short label for narrow layouts. */
    val abbr: String = "",
    /**
     * Minutes after local midnight of the day: 0–1439, or 1440 and more for a
     * night mark that falls after the midnight ending the day (the First
     * Third, some nights). Null when the time does not occur at this
     * latitude; draw a dash.
     */
    val minutes: Int? = null,
  ) {
    fun toJson(): JSONObject = JSONObject().apply {
      put("key", key)
      put("name", name)
      put("abbr", abbr)
      minutes?.let { put("minutes", it) }
    }

    companion object {
      fun fromJson(o: JSONObject?): Row? {
        if (o == null) return null
        return Row(
          key = o.wcString("key") ?: return null,
          name = o.wcString("name") ?: "",
          abbr = o.wcString("abbr") ?: "",
          minutes = o.wcRaw("minutes").wcAsInt(),
        )
      }

      fun parse(json: String?): Row? =
        try {
          if (json.isNullOrEmpty()) null else fromJson(JSONObject(json))
        } catch (e: JSONException) {
          null
        }
    }
  }

  /** Seasonal accents. */
  data class Seasonal(
    /** Friday before Maghrib. */
    val jumuah: Boolean = false,
    /** Inside Ramadan. */
    val ramadan: Boolean = false,
    /** Eid day, or null. */
    val eid: Eid? = null,
  ) {
    fun toJson(): JSONObject = JSONObject().apply {
      put("jumuah", jumuah)
      put("ramadan", ramadan)
      eid?.let { put("eid", it.wire) }
    }

    companion object {
      fun fromJson(o: JSONObject?): Seasonal? {
        if (o == null) return null
        return Seasonal(
          jumuah = o.wcBool("jumuah") ?: false,
          ramadan = o.wcBool("ramadan") ?: false,
          eid = Eid.fromWire(o.wcString("eid")),
        )
      }

      fun parse(json: String?): Seasonal? =
        try {
          if (json.isNullOrEmpty()) null else fromJson(JSONObject(json))
        } catch (e: JSONException) {
          null
        }
    }
  }

  /** Today's five as the Log Today widget needs them. */
  data class Today(
    /**
     * Local YYYY-MM-DD. A widget that slept through midnight must not draw
     * yesterday's ticks as today's.
     */
    val dateKey: String,
    val logged: Int = 0,
    val loggable: Int = 0,
    /** Missed today and not yet made up. */
    val owed: Int = 0,
    val prayers: List<TodayPrayer> = emptyList(),
  ) {
    fun toJson(): JSONObject = JSONObject().apply {
      put("dateKey", dateKey)
      put("logged", logged)
      put("loggable", loggable)
      put("owed", owed)
      put("prayers", JSONArray().apply { prayers.forEach { put(it.toJson()) } })
    }

    companion object {
      fun fromJson(o: JSONObject?): Today? {
        if (o == null) return null
        return Today(
          dateKey = o.wcString("dateKey") ?: return null,
          logged = o.wcRaw("logged").wcAsInt() ?: 0,
          loggable = o.wcRaw("loggable").wcAsInt() ?: 0,
          owed = o.wcRaw("owed").wcAsInt() ?: 0,
          prayers = o.wcList("prayers") { TodayPrayer.fromJson(it as? JSONObject) } ?: emptyList(),
        )
      }

      fun parse(json: String?): Today? =
        try {
          if (json.isNullOrEmpty()) null else fromJson(JSONObject(json))
        } catch (e: JSONException) {
          null
        }
    }
  }

  /** One prayer on the Log Today widget. */
  data class TodayPrayer(
    /** Journal prayer key. */
    val key: String,
    /** Localised name. */
    val name: String = "",
    /** Its time today, as `Row.minutes`. */
    val minutes: Int? = null,
    /** Journal status; null when nothing is recorded. */
    val status: PrayerStatus? = null,
    /** Its time has arrived; only a due prayer takes a tap. */
    val due: Boolean = false,
  ) {
    fun toJson(): JSONObject = JSONObject().apply {
      put("key", key)
      put("name", name)
      minutes?.let { put("minutes", it) }
      status?.let { put("status", it.wire) }
      put("due", due)
    }

    companion object {
      fun fromJson(o: JSONObject?): TodayPrayer? {
        if (o == null) return null
        return TodayPrayer(
          key = o.wcString("key") ?: return null,
          name = o.wcString("name") ?: "",
          minutes = o.wcRaw("minutes").wcAsInt(),
          status = PrayerStatus.fromWire(o.wcString("status")),
          due = o.wcBool("due") ?: false,
        )
      }

      fun parse(json: String?): TodayPrayer? =
        try {
          if (json.isNullOrEmpty()) null else fromJson(JSONObject(json))
        } catch (e: JSONException) {
          null
        }
    }
  }

  /** Practice history. */
  data class Practice(
    val streak: Int = 0,
    val bestStreak: Int = 0,
    /** Of the five, how many are logged today. */
    val loggedToday: Int = 0,
    /** Missed and not yet made up, all time. */
    val owed: Int = 0,
    /**
     * Sunnah kept this month as a fraction; null before there is a
     * denominator.
     */
    val sunnahRate: Double? = null,
    val fastsThisMonth: Int = 0,
    /** Oldest first, ending today; empty days omitted. */
    val days: List<PracticeDay> = emptyList(),
    /**
     * First day with a prayer entry, YYYY-MM-DD. Before it an empty square
     * means "not started yet", after it "not filled in".
     */
    val since: String? = null,
  ) {
    fun toJson(): JSONObject = JSONObject().apply {
      put("streak", streak)
      put("bestStreak", bestStreak)
      put("loggedToday", loggedToday)
      put("owed", owed)
      sunnahRate?.let { put("sunnahRate", it) }
      put("fastsThisMonth", fastsThisMonth)
      put("days", JSONArray().apply { days.forEach { put(it.toJson()) } })
      since?.let { put("since", it) }
    }

    companion object {
      fun fromJson(o: JSONObject?): Practice? {
        if (o == null) return null
        return Practice(
          streak = o.wcRaw("streak").wcAsInt() ?: 0,
          bestStreak = o.wcRaw("bestStreak").wcAsInt() ?: 0,
          loggedToday = o.wcRaw("loggedToday").wcAsInt() ?: 0,
          owed = o.wcRaw("owed").wcAsInt() ?: 0,
          sunnahRate = (o.wcRaw("sunnahRate") as? Number)?.toDouble(),
          fastsThisMonth = o.wcRaw("fastsThisMonth").wcAsInt() ?: 0,
          days = o.wcList("days") { PracticeDay.fromJson(it as? JSONObject) } ?: emptyList(),
          since = o.wcString("since"),
        )
      }

      fun parse(json: String?): Practice? =
        try {
          if (json.isNullOrEmpty()) null else fromJson(JSONObject(json))
        } catch (e: JSONException) {
          null
        }
    }
  }

  /**
   * One day's marks on the practice grid. Short keys: up to 210 of these ride
   * in every payload.
   */
  data class PracticeDay(
    /** Local YYYY-MM-DD. */
    val d: String,
    /**
     * Weighted score ×100 — on-time 100, late 70, qadha 45 — summed over the
     * five, capped at 500.
     */
    val kw: Int = 0,
    /** How many of the five carry any entry. */
    val l: Int = 0,
    /** A prayer recorded missed and not made up. */
    val m: Boolean = false,
    /** A completed fast. */
    val f: Boolean = false,
    /** Sunnah units kept. */
    val s: Int = 0,
  ) {
    fun toJson(): JSONObject = JSONObject().apply {
      put("d", d)
      put("kw", kw)
      put("l", l)
      put("m", m)
      put("f", f)
      put("s", s)
    }

    companion object {
      fun fromJson(o: JSONObject?): PracticeDay? {
        if (o == null) return null
        return PracticeDay(
          d = o.wcString("d") ?: return null,
          kw = o.wcRaw("kw").wcAsInt() ?: 0,
          l = o.wcRaw("l").wcAsInt() ?: 0,
          m = o.wcBool("m") ?: false,
          f = o.wcBool("f") ?: false,
          s = o.wcRaw("s").wcAsInt() ?: 0,
        )
      }

      fun parse(json: String?): PracticeDay? =
        try {
          if (json.isNullOrEmpty()) null else fromJson(JSONObject(json))
        } catch (e: JSONException) {
          null
        }
    }
  }

  /** The Continue Reading widget. */
  data class Reading(
    val surah: Int = 1,
    /** Localised surah name. */
    val surahName: String = "",
    val ayah: Int = 1,
    val page: Int = 1,
    val juz: Int = 1,
    val pagesRead: Int = 0,
    val totalPages: Int = 604,
    val bookmarks: Int = 0,
    /** Epoch ms of the last page turn. */
    val lastReadAt: Long? = null,
    /**
     * Which reader a tap opens — decided by the app, which knows whether the
     * muṣḥaf is on disk.
     */
    val mode: ReaderMode = ReaderMode.TRANSLATION,
    val khatmah: Khatmah? = null,
    /** False when the Qurʾān has never been opened. */
    val started: Boolean = false,
    /** The muṣḥaf page images are on disk. */
    val downloaded: Boolean = false,
  ) {
    fun toJson(): JSONObject = JSONObject().apply {
      put("surah", surah)
      put("surahName", surahName)
      put("ayah", ayah)
      put("page", page)
      put("juz", juz)
      put("pagesRead", pagesRead)
      put("totalPages", totalPages)
      put("bookmarks", bookmarks)
      lastReadAt?.let { put("lastReadAt", it) }
      put("mode", mode.wire)
      khatmah?.let { put("khatmah", it.toJson()) }
      put("started", started)
      put("downloaded", downloaded)
    }

    companion object {
      fun fromJson(o: JSONObject?): Reading? {
        if (o == null) return null
        return Reading(
          surah = o.wcRaw("surah").wcAsInt() ?: 1,
          surahName = o.wcString("surahName") ?: "",
          ayah = o.wcRaw("ayah").wcAsInt() ?: 1,
          page = o.wcRaw("page").wcAsInt() ?: 1,
          juz = o.wcRaw("juz").wcAsInt() ?: 1,
          pagesRead = o.wcRaw("pagesRead").wcAsInt() ?: 0,
          totalPages = o.wcRaw("totalPages").wcAsInt() ?: 604,
          bookmarks = o.wcRaw("bookmarks").wcAsInt() ?: 0,
          lastReadAt = o.wcRaw("lastReadAt").wcAsLong(),
          mode = ReaderMode.fromWire(o.wcString("mode")) ?: ReaderMode.TRANSLATION,
          khatmah = Khatmah.fromJson(o.wcRaw("khatmah") as? JSONObject),
          started = o.wcBool("started") ?: false,
          downloaded = o.wcBool("downloaded") ?: false,
        )
      }

      fun parse(json: String?): Reading? =
        try {
          if (json.isNullOrEmpty()) null else fromJson(JSONObject(json))
        } catch (e: JSONException) {
          null
        }
    }
  }

  /** Today's share of the khatmah plan. */
  data class Khatmah(
    /** 1-based day of the plan. */
    val day: Int = 1,
    val targetDays: Int = 0,
    val pagesToday: Int = 0,
    val doneToday: Int = 0,
    val behindBy: Int = 0,
    val daysLeft: Int = 0,
    /** Pages left unread behind the reader. */
    val skipped: Int = 0,
  ) {
    fun toJson(): JSONObject = JSONObject().apply {
      put("day", day)
      put("targetDays", targetDays)
      put("pagesToday", pagesToday)
      put("doneToday", doneToday)
      put("behindBy", behindBy)
      put("daysLeft", daysLeft)
      put("skipped", skipped)
    }

    companion object {
      fun fromJson(o: JSONObject?): Khatmah? {
        if (o == null) return null
        return Khatmah(
          day = o.wcRaw("day").wcAsInt() ?: 1,
          targetDays = o.wcRaw("targetDays").wcAsInt() ?: 0,
          pagesToday = o.wcRaw("pagesToday").wcAsInt() ?: 0,
          doneToday = o.wcRaw("doneToday").wcAsInt() ?: 0,
          behindBy = o.wcRaw("behindBy").wcAsInt() ?: 0,
          daysLeft = o.wcRaw("daysLeft").wcAsInt() ?: 0,
          skipped = o.wcRaw("skipped").wcAsInt() ?: 0,
        )
      }

      fun parse(json: String?): Khatmah? =
        try {
          if (json.isNullOrEmpty()) null else fromJson(JSONObject(json))
        } catch (e: JSONException) {
          null
        }
    }
  }

  /** Today's Hijri date. */
  data class Hijri(
    val day: Int,
    val month: Int,
    val year: Int,
    val monthName: String = "",
    /** The whole date, localised. */
    val label: String = "",
    val nextMonthName: String = "",
    val nextMonthInDays: Int = 0,
  ) {
    fun toJson(): JSONObject = JSONObject().apply {
      put("day", day)
      put("month", month)
      put("year", year)
      put("monthName", monthName)
      put("label", label)
      put("nextMonthName", nextMonthName)
      put("nextMonthInDays", nextMonthInDays)
    }

    companion object {
      fun fromJson(o: JSONObject?): Hijri? {
        if (o == null) return null
        return Hijri(
          day = o.wcRaw("day").wcAsInt() ?: return null,
          month = o.wcRaw("month").wcAsInt() ?: return null,
          year = o.wcRaw("year").wcAsInt() ?: return null,
          monthName = o.wcString("monthName") ?: "",
          label = o.wcString("label") ?: "",
          nextMonthName = o.wcString("nextMonthName") ?: "",
          nextMonthInDays = o.wcRaw("nextMonthInDays").wcAsInt() ?: 0,
        )
      }

      fun parse(json: String?): Hijri? =
        try {
          if (json.isNullOrEmpty()) null else fromJson(JSONObject(json))
        } catch (e: JSONException) {
          null
        }
    }
  }

  /** The dhikr counter. */
  data class Tasbih(
    val presetId: String = "",
    /** Localised transliteration. */
    val label: String = "",
    val arabic: String = "",
    val count: Int = 0,
    /** 0 means open counting. */
    val target: Int = 0,
    val unbounded: Boolean = false,
    /** Position in the preset cycle. */
    val index: Int = 0,
    /** Cycle length. */
    val total: Int = 0,
    /** Every preset's count, in order. */
    val counts: List<Int> = emptyList(),
    /**
     * Every preset's label — the widget steps the cycle in its own process.
     */
    val labels: List<String> = emptyList(),
    val targets: List<Int> = emptyList(),
    val unboundedFlags: List<Boolean> = emptyList(),
    /** Beads counted today, across presets. */
    val todayTotal: Int = 0,
    val todayRounds: Int = 0,
  ) {
    fun toJson(): JSONObject = JSONObject().apply {
      put("presetId", presetId)
      put("label", label)
      put("arabic", arabic)
      put("count", count)
      put("target", target)
      put("unbounded", unbounded)
      put("index", index)
      put("total", total)
      put("counts", JSONArray().apply { counts.forEach { put(it) } })
      put("labels", JSONArray().apply { labels.forEach { put(it) } })
      put("targets", JSONArray().apply { targets.forEach { put(it) } })
      put("unboundedFlags", JSONArray().apply { unboundedFlags.forEach { put(it) } })
      put("todayTotal", todayTotal)
      put("todayRounds", todayRounds)
    }

    companion object {
      fun fromJson(o: JSONObject?): Tasbih? {
        if (o == null) return null
        return Tasbih(
          presetId = o.wcString("presetId") ?: "",
          label = o.wcString("label") ?: "",
          arabic = o.wcString("arabic") ?: "",
          count = o.wcRaw("count").wcAsInt() ?: 0,
          target = o.wcRaw("target").wcAsInt() ?: 0,
          unbounded = o.wcBool("unbounded") ?: false,
          index = o.wcRaw("index").wcAsInt() ?: 0,
          total = o.wcRaw("total").wcAsInt() ?: 0,
          counts = o.wcList("counts") { it.wcAsInt() } ?: emptyList(),
          labels = o.wcList("labels") { it as? String } ?: emptyList(),
          targets = o.wcList("targets") { it.wcAsInt() } ?: emptyList(),
          unboundedFlags = o.wcList("unboundedFlags") { it as? Boolean } ?: emptyList(),
          todayTotal = o.wcRaw("todayTotal").wcAsInt() ?: 0,
          todayRounds = o.wcRaw("todayRounds").wcAsInt() ?: 0,
        )
      }

      fun parse(json: String?): Tasbih? =
        try {
          if (json.isNullOrEmpty()) null else fromJson(JSONObject(json))
        } catch (e: JSONException) {
          null
        }
    }
  }

  /**
   * One Log Today tap, queued by the widget until the app drains it. Same
   * wire shape as v1.
   */
  data class LogQueueEntry(
    /** Local YYYY-MM-DD the tap was for. */
    val d: String,
    /** Journal prayer key. */
    val p: String,
    /**
     * Epoch ms of the tap. Read with its fraction dropped: widgets before the
     * contract wrote a fractional Double here, and a tap queued by one must
     * survive the update.
     */
    val t: Long,
  ) {
    fun toJson(): JSONObject = JSONObject().apply {
      put("d", d)
      put("p", p)
      put("t", t)
    }

    companion object {
      fun fromJson(o: JSONObject?): LogQueueEntry? {
        if (o == null) return null
        return LogQueueEntry(
          d = o.wcString("d") ?: return null,
          p = o.wcString("p") ?: return null,
          t = o.wcRaw("t").wcAsLongTruncated() ?: return null,
        )
      }

      fun parse(json: String?): LogQueueEntry? =
        try {
          if (json.isNullOrEmpty()) null else fromJson(JSONObject(json))
        } catch (e: JSONException) {
          null
        }
    }
  }

  /** One Tasbih widget action. Same wire shape as v1. */
  data class TasbihQueueEntry(
    /** Action. */
    val a: TasbihAction,
    /** Epoch ms. Read with its fraction dropped, as the log tap is. */
    val t: Long,
    /**
     * Run length for coalesced taps; absent means one. A long so an absurd
     * count still reads, and is clamped by the rule rather than dropped by
     * the reader.
     */
    val n: Long? = null,
  ) {
    fun toJson(): JSONObject = JSONObject().apply {
      put("a", a.wire)
      put("t", t)
      n?.let { put("n", it) }
    }

    companion object {
      fun fromJson(o: JSONObject?): TasbihQueueEntry? {
        if (o == null) return null
        return TasbihQueueEntry(
          a = TasbihAction.fromWire(o.wcString("a")) ?: return null,
          t = o.wcRaw("t").wcAsLongTruncated() ?: return null,
          n = o.wcRaw("n").wcAsLong(),
        )
      }

      fun parse(json: String?): TasbihQueueEntry? =
        try {
          if (json.isNullOrEmpty()) null else fromJson(JSONObject(json))
        } catch (e: JSONException) {
          null
        }
    }
  }

}

// ── Lenient reading ────────────────────────────────────────────────────
//
// org.json's own opt* readers are not used: optString turns a JSON null into
// the four letters "null" on Android, and optInt turns a missing key into 0,
// which is how a renamed field used to draw as an empty label with no error.

private fun JSONObject.wcRaw(k: String): Any? = if (has(k) && !isNull(k)) opt(k) else null

private fun JSONObject.wcString(k: String): String? = wcRaw(k) as? String

private fun JSONObject.wcBool(k: String): Boolean? = wcRaw(k) as? Boolean

private fun Any?.wcAsLong(): Long? =
  when (this) {
    is Int -> toLong()
    is Long -> this
    is Number -> {
      val d = toDouble()
      if (d.isFinite() && d == Math.floor(d) && Math.abs(d) < 9.0e15) d.toLong() else null
    }
    else -> null
  }

/**
 * A `truncate` long: any finite number below 9e15, its fraction dropped.
 * For values a writer once stored as a fractional Double (epoch ms), so
 * an entry already on disk still reads.
 */
private fun Any?.wcAsLongTruncated(): Long? =
  when (this) {
    is Int -> toLong()
    is Long -> this
    is Number -> {
      val d = toDouble()
      if (d.isFinite() && Math.abs(d) < 9.0e15) d.toLong() else null
    }
    else -> null
  }

private fun Any?.wcAsInt(): Int? =
  wcAsLong()?.let { if (it in Int.MIN_VALUE..Int.MAX_VALUE) it.toInt() else null }

private inline fun <T> JSONObject.wcList(k: String, element: (Any?) -> T?): List<T>? {
  val a = wcRaw(k) as? JSONArray ?: return null
  val out = ArrayList<T>(a.length())
  for (i in 0 until a.length()) {
    val v = if (a.isNull(i)) null else a.opt(i)
    element(v)?.let { out.add(it) }
  }
  return out
}
