// GENERATED by scripts/gen-widget-contract.js from scripts/contract/widget-contract.js — do not edit.

import Foundation

/// Type name → decode with the contract reader, re-encode, or nil when unreadable.
let contractReaders: [String: (Data) -> Data?] = [
  "Payload": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.Payload.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Clock": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.Clock.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Day": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.Day.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Row": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.Row.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Seasonal": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.Seasonal.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Today": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.Today.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "TodayPrayer": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.TodayPrayer.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Practice": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.Practice.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "PracticeDay": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.PracticeDay.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Reading": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.Reading.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Khatmah": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.Khatmah.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Hijri": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.Hijri.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Tasbih": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.Tasbih.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "LiveActivity": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.LiveActivity.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "DayText": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.DayText.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "AlertMode": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.AlertMode.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "LiveActivityAppearance": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.LiveActivityAppearance.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "LiveActivityAndroid": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.LiveActivityAndroid.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "LiveActivityWords": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.LiveActivityWords.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "LogQueueEntry": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.LogQueueEntry.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "TasbihQueueEntry": { data in
    guard let v = try? JSONDecoder().decode(WidgetContract.TasbihQueueEntry.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
]

/// Type name → read a top-level array with `readList`, re-encode, or nil.
let contractListReaders: [String: (Data) -> Data?] = [
  "Payload": { data in
    guard let v = WidgetContract.readList(WidgetContract.Payload.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Clock": { data in
    guard let v = WidgetContract.readList(WidgetContract.Clock.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Day": { data in
    guard let v = WidgetContract.readList(WidgetContract.Day.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Row": { data in
    guard let v = WidgetContract.readList(WidgetContract.Row.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Seasonal": { data in
    guard let v = WidgetContract.readList(WidgetContract.Seasonal.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Today": { data in
    guard let v = WidgetContract.readList(WidgetContract.Today.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "TodayPrayer": { data in
    guard let v = WidgetContract.readList(WidgetContract.TodayPrayer.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Practice": { data in
    guard let v = WidgetContract.readList(WidgetContract.Practice.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "PracticeDay": { data in
    guard let v = WidgetContract.readList(WidgetContract.PracticeDay.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Reading": { data in
    guard let v = WidgetContract.readList(WidgetContract.Reading.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Khatmah": { data in
    guard let v = WidgetContract.readList(WidgetContract.Khatmah.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Hijri": { data in
    guard let v = WidgetContract.readList(WidgetContract.Hijri.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "Tasbih": { data in
    guard let v = WidgetContract.readList(WidgetContract.Tasbih.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "LiveActivity": { data in
    guard let v = WidgetContract.readList(WidgetContract.LiveActivity.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "DayText": { data in
    guard let v = WidgetContract.readList(WidgetContract.DayText.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "AlertMode": { data in
    guard let v = WidgetContract.readList(WidgetContract.AlertMode.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "LiveActivityAppearance": { data in
    guard let v = WidgetContract.readList(WidgetContract.LiveActivityAppearance.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "LiveActivityAndroid": { data in
    guard let v = WidgetContract.readList(WidgetContract.LiveActivityAndroid.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "LiveActivityWords": { data in
    guard let v = WidgetContract.readList(WidgetContract.LiveActivityWords.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "LogQueueEntry": { data in
    guard let v = WidgetContract.readList(WidgetContract.LogQueueEntry.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
  "TasbihQueueEntry": { data in
    guard let v = WidgetContract.readList(WidgetContract.TasbihQueueEntry.self, from: data) else { return nil }
    return try? JSONEncoder().encode(v)
  },
]
