// GENERATED by scripts/gen-widget-contract.js from scripts/contract/widget-contract.js — do not edit.

package com.prayer_times.contract

import org.json.JSONObject

/** Type name → read with the contract reader and write back, or null when unreadable. */
val contractReaders: Map<String, (String) -> JSONObject?> = mapOf(
  "Payload" to { s -> WidgetContract.Payload.parse(s)?.toJson() },
  "Clock" to { s -> WidgetContract.Clock.parse(s)?.toJson() },
  "Day" to { s -> WidgetContract.Day.parse(s)?.toJson() },
  "Row" to { s -> WidgetContract.Row.parse(s)?.toJson() },
  "Seasonal" to { s -> WidgetContract.Seasonal.parse(s)?.toJson() },
  "Today" to { s -> WidgetContract.Today.parse(s)?.toJson() },
  "TodayPrayer" to { s -> WidgetContract.TodayPrayer.parse(s)?.toJson() },
  "Practice" to { s -> WidgetContract.Practice.parse(s)?.toJson() },
  "PracticeDay" to { s -> WidgetContract.PracticeDay.parse(s)?.toJson() },
  "Reading" to { s -> WidgetContract.Reading.parse(s)?.toJson() },
  "Khatmah" to { s -> WidgetContract.Khatmah.parse(s)?.toJson() },
  "Hijri" to { s -> WidgetContract.Hijri.parse(s)?.toJson() },
  "Tasbih" to { s -> WidgetContract.Tasbih.parse(s)?.toJson() },
  "LogQueueEntry" to { s -> WidgetContract.LogQueueEntry.parse(s)?.toJson() },
  "TasbihQueueEntry" to { s -> WidgetContract.TasbihQueueEntry.parse(s)?.toJson() },
)
