// GENERATED by scripts/gen-widget-contract.js from scripts/contract/widget-contract.js — do not edit.

package com.prayer_times.contract

import org.json.JSONArray
import org.json.JSONObject

/** Type name → read with the contract reader and write back, or null when unreadable. */
val contractReaders: Map<String, (String) -> JSONObject?> = mapOf(
  "Payload" to { s -> WidgetContract.Payload.parse(s)?.toJson() },
  "Clock" to { s -> WidgetContract.Clock.parse(s)?.toJson() },
  "Day" to { s -> WidgetContract.Day.parse(s)?.toJson() },
  "Row" to { s -> WidgetContract.Row.parse(s)?.toJson() },
  "Seasonal" to { s -> WidgetContract.Seasonal.parse(s)?.toJson() },
  "Today" to { s -> WidgetContract.Today.parse(s)?.toJson() },
  "TodayPrayer" to { s -> WidgetContract.TodayPrayer.parse(s)?.toJson() },
  "Practice" to { s -> WidgetContract.Practice.parse(s)?.toJson() },
  "PracticeDay" to { s -> WidgetContract.PracticeDay.parse(s)?.toJson() },
  "Reading" to { s -> WidgetContract.Reading.parse(s)?.toJson() },
  "Khatmah" to { s -> WidgetContract.Khatmah.parse(s)?.toJson() },
  "Hijri" to { s -> WidgetContract.Hijri.parse(s)?.toJson() },
  "Tasbih" to { s -> WidgetContract.Tasbih.parse(s)?.toJson() },
  "LiveActivity" to { s -> WidgetContract.LiveActivity.parse(s)?.toJson() },
  "DayText" to { s -> WidgetContract.DayText.parse(s)?.toJson() },
  "AlertMode" to { s -> WidgetContract.AlertMode.parse(s)?.toJson() },
  "LiveActivityAppearance" to { s -> WidgetContract.LiveActivityAppearance.parse(s)?.toJson() },
  "LiveActivityAndroid" to { s -> WidgetContract.LiveActivityAndroid.parse(s)?.toJson() },
  "LiveActivityWords" to { s -> WidgetContract.LiveActivityWords.parse(s)?.toJson() },
  "LogQueueEntry" to { s -> WidgetContract.LogQueueEntry.parse(s)?.toJson() },
  "TasbihQueueEntry" to { s -> WidgetContract.TasbihQueueEntry.parse(s)?.toJson() },
)

/** Type name → read a top-level array with `readList` and write it back, or null. */
val contractListReaders: Map<String, (String) -> JSONArray?> = mapOf(
  "Payload" to { s -> WidgetContract.readList(s) { WidgetContract.Payload.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "Clock" to { s -> WidgetContract.readList(s) { WidgetContract.Clock.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "Day" to { s -> WidgetContract.readList(s) { WidgetContract.Day.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "Row" to { s -> WidgetContract.readList(s) { WidgetContract.Row.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "Seasonal" to { s -> WidgetContract.readList(s) { WidgetContract.Seasonal.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "Today" to { s -> WidgetContract.readList(s) { WidgetContract.Today.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "TodayPrayer" to { s -> WidgetContract.readList(s) { WidgetContract.TodayPrayer.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "Practice" to { s -> WidgetContract.readList(s) { WidgetContract.Practice.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "PracticeDay" to { s -> WidgetContract.readList(s) { WidgetContract.PracticeDay.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "Reading" to { s -> WidgetContract.readList(s) { WidgetContract.Reading.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "Khatmah" to { s -> WidgetContract.readList(s) { WidgetContract.Khatmah.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "Hijri" to { s -> WidgetContract.readList(s) { WidgetContract.Hijri.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "Tasbih" to { s -> WidgetContract.readList(s) { WidgetContract.Tasbih.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "LiveActivity" to { s -> WidgetContract.readList(s) { WidgetContract.LiveActivity.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "DayText" to { s -> WidgetContract.readList(s) { WidgetContract.DayText.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "AlertMode" to { s -> WidgetContract.readList(s) { WidgetContract.AlertMode.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "LiveActivityAppearance" to { s -> WidgetContract.readList(s) { WidgetContract.LiveActivityAppearance.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "LiveActivityAndroid" to { s -> WidgetContract.readList(s) { WidgetContract.LiveActivityAndroid.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "LiveActivityWords" to { s -> WidgetContract.readList(s) { WidgetContract.LiveActivityWords.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "LogQueueEntry" to { s -> WidgetContract.readList(s) { WidgetContract.LogQueueEntry.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
  "TasbihQueueEntry" to { s -> WidgetContract.readList(s) { WidgetContract.TasbihQueueEntry.fromJson(it) }?.let { l -> JSONArray(l.map { it.toJson() }) } },
)
