/**
 * Mushaf page layout — the data behind the font-rendered reader (v2.8.0).
 *
 * `data/mushafLayoutV2.json` is generated by `scripts/mushaf/build_qcf_assets.py`
 * from the QPC v2 word data. For every one of the 604 pages it holds the 15
 * printed lines: what kind of line it is, the words on it (as the codepoints
 * of the page's own font, where one glyph is one word), which ayah each word
 * belongs to, and how wide the line is in ems of that font.
 *
 * Two things make the page look like the print rather than like a web page:
 *
 * - **`measure`** — the width of the page's widest line, in ems. The reader
 *   sets `fontSize = availableWidth / measure`, so that line spans the page
 *   exactly and every page ends up the same physical width even though the
 *   fonts are drawn at different design sizes.
 * - **`natural`** — each line's own width in ems. A full line is within ~2% of
 *   the measure, so ordinary word spacing closes the gap invisibly; lines that
 *   close a surah are marked `centered` and are not stretched at all.
 *
 * The raw JSON is kept in its compact on-disk shape and decoded per page on
 * demand — decoding all 604 up front would cost time and memory the reader
 * never needs, since it only ever shows a handful of pages.
 */
import { riwayahById, type RiwayahId } from './riwayat';
import { nativeMushafLineAvailable } from './native/MushafLineView';

type RawSegment = [number, number, number, number] | [number, number, number, number, number];

type RawLine = {
  t: 'a' | 's' | 'b';
  /** Ayah lines: words as font codepoints, separated by "|". */
  x?: string;
  /** Ayah lines: [surah, ayah, firstWordPosition, wordCount, isEnd?] runs. */
  w?: RawSegment[];
  /** Ayah lines: natural width in ems. */
  n?: number;
  /** Ayah lines: each word's advance width, in ems. */
  a?: number[];
  /** Ayah lines: 1 when the line closes a surah and must not be stretched. */
  c?: 1;
  /** Surah/basmalah lines: which surah. */
  s?: number;
};

type RawPage = { p: number; m: number; l: RawLine[] };

export type MushafWord = {
  /** The codepoint(s) to draw with the page font. */
  text: string;
  surah: number;
  ayah: number;
  /** 1-based word position within the ayah (matches the word timing data). */
  position: number;
  /** True for the ayah-number medallion, which QPC treats as a word. */
  isEnd: boolean;
  /**
   * The word's advance width in ems — how far the pen moves, which is NOT
   * how wide the word looks. Several QPC glyphs draw ink far past their
   * advance so they interlock with their neighbours (page 1's basmalah is
   * the clearest). That is why a line is drawn as one text run and taps are
   * resolved against these advances instead of per-word views.
   */
  advance: number;
};

export type MushafLine =
  // Split rather than `kind: 'surah' | 'basmalah'` so the discriminant
  // narrows cleanly at the call sites that switch on it.
  | { kind: 'surah'; surah: number }
  | { kind: 'basmalah'; surah: number }
  | {
      kind: 'ayah';
      words: MushafWord[];
      /** Natural width in ems of the page font. */
      natural: number;
      /** Closes a surah — centred, never stretched. */
      centered: boolean;
    };

export type MushafPageLayout = {
  page: number;
  /** Width of the page's widest line, in ems of the page font. */
  measure: number;
  lines: MushafLine[];
};

/** Lines on a standard page. Pages 1–2 are ornamental plates with fewer. */
export const MUSHAF_LINES_PER_PAGE = 15;

// ---------------------------------------------------------------------------
// Line spacing
//
// `natural` is the sum of the glyph ADVANCES only — the QPC page fonts carry
// no space glyph, so whatever is added between two words is the renderer's
// to supply. The advances themselves carry the print's spacing as side
// bearings, so for an ordinary line that is almost nothing (see
// `QPC_WORD_SPACE_EM`). Everything below is the model for that gap, kept
// here (and free of React Native) so a test can replay exactly what the
// reader draws.
// ---------------------------------------------------------------------------

/**
 * What a Ḥafṣ line adds between two words BEYOND what the page font's
 * glyphs already carry, in ems: nothing.
 *
 * ── MEASURED, NOT CHOSEN ──────────────────────────────────────────────
 *
 * The print's word space is not recorded in the data, and for a long time
 * a nominal quarter em was assumed for it: the page's tightest line was
 * taken to be set at 0.25 em a gap, which put the measure at
 * `max(natural + 0.25 × gaps)` and set every other line wider still.
 *
 * Then the print was measured (`scripts/mushaf/measure_print_spacing.py`
 * over the KFGQPC scans, 2026-09-23). Fitting each line's ink width to
 * `em × (natural + gaps × space)` across page 125 gives an em of 149 px
 * and a space of 0.014 em; page 290 gives −0.03 em. The line whose
 * advances are the widest (page 125 line 15, 15.823 em) is set with its
 * words TOUCHING — gaps of one or two pixels — and the line with the
 * narrowest (line 14, 15.441 em) gets the difference spread over its ten
 * gaps, 0.038 em each. The visible gap between words, a median 0.11–0.13
 * em, is the glyphs' own side bearings: the QCF fonts were cut from the
 * print with its spacing inside the advances.
 *
 * So the measure of an ordinary page is its widest line's ADVANCES, the
 * `measure` in the data, and the gap a line adds is only what closes the
 * ~2% between its advances and that. The quarter em had made every page
 * a seventh narrower than the print and every gap two to four times the
 * print's, which is the difference a reader saw against Ayah.
 */
export const QPC_WORD_SPACE_EM = 0;

/**
 * Nominal word space, in ems, where the face carries none of its own:
 * the Unicode riwāyāt (`MushafUnicodePage`, set in AmiriQuran with real
 * spaces), the framed plates' centred lines, and the gap before a hizb or
 * sajdah symbol inside a word, which the build budgets at the same
 * quarter em (`INTERNAL_SPACE_EM` in `build_qcf_assets.py`) inside the
 * word's advance.
 */
export const WORD_SPACE_EM = 0.25;

/**
 * The band the word space may move inside on a FRAMED PLATE — pages 1 and
 * 2 (`docs/mushaf-fidelity-rules.md`). Below the minimum the QPC
 * letterforms, which interlock by design, start to touch. Above the
 * maximum a plate's line stops looking like a line of the mushaf and
 * starts looking like justified web text pulled apart, so it is centred at
 * its natural width instead — a plate's short lines are meant to be short.
 *
 * An ordinary page's lines are NOT held to this: they are set at the space
 * the print asks for, however wide, up to `WORD_SPACE_CEILING_EM`. See
 * `lineSpaceEm` for the ten lines that taught us the difference.
 */
export const WORD_SPACE_MIN_EM = 0.2;
export const WORD_SPACE_MAX_EM = 0.75;

/**
 * The widest gap ANY line may be set at, framed plates aside.
 *
 * Not a matter of taste — `WORD_SPACE_MAX_EM` is that, and it governs the
 * plates. This is the guard on the data: a line whose words sum to almost
 * nothing would otherwise be stretched across the measure by a gap of any
 * size at all. The widest gap the print itself asks for anywhere in the
 * muṣḥaf is 1.942 em (page 604, line 14, in An-Nās), so a line that wants
 * more than two ems per gap is not a line the print set — it is a line
 * whose data is wrong, and it comes out short and centred where it can be
 * seen rather than silently pulled apart.
 */
export const WORD_SPACE_CEILING_EM = 2;

/**
 * Advance of `space` (U+0020) and no-break space (U+00A0) in the bundled
 * `AmiriQuran.ttf`, in ems — read out of the shipped binary, which is byte
 * identical on both platforms:
 *
 *     hmtx['space'] / head.unitsPerEm  ==  292 / 1000
 *
 * The renderer draws every gap in that font, at a size it derives from this
 * number, so the drawn width of a line is the width we computed rather than
 * whatever the platform's fallback face happens to use. `verify_mushaf.py`
 * re-reads the font and fails if this drifts.
 */
export const MUSHAF_SPACE_ADVANCE_EM = 0.292;

/**
 * Slack carried by the box a line is drawn in, in ems, reserved out of the
 * page block so a line's box can never be wider than the block it sits in.
 *
 * This is not a fudge factor, it is the difference between a correct page and
 * a page with a word missing from every line. Android lays a single line out
 * by BREAKING it, and when nothing else will fit it breaks between glyphs —
 * and in QPC a glyph is a whole word. So a line that comes out one sub-pixel
 * wider than its box does not clip a hair of ink, it silently loses its last
 * word (page 49, every line, verified on a Pixel). Measured on device, the
 * drawn width tracks the computed width to within ~0.05 em; half an em of
 * reserve is twenty times that, and also gives the ink QPC glyphs throw past
 * their advance somewhere to land at the margins.
 */
export const MUSHAF_LINE_BOX_SLACK_EM = 0.5;

/**
 * The slack the lines being drawn actually carry, in ems.
 *
 * The native line view (`native/MushafLineView.ts`) draws a line with the
 * pen, and a pen does not break: a run a hair wider than its box lands a
 * hair further left, and nothing is lost. Its box is the run itself, and
 * the whole reserve goes back to the text. The `<Text>` path keeps the
 * half em above, for the reason given there.
 */
export function lineBoxSlackEm(): number {
  return nativeMushafLineAvailable() ? 0 : MUSHAF_LINE_BOX_SLACK_EM;
}

/**
 * How far a line's ink reaches past its ends, in ems — past the FIRST
 * glyph's advance on the right (the text is RTL), and before the LAST
 * glyph's origin on the left.
 *
 * Measured over the raw fonts, line by line, by
 * `scripts/mushaf/measure_ink_overshoot.py`: 0.3504 em on the right (page
 * 146) and 0.1956 em on the left (page 12), a hair added. Mid-line the
 * same swashes simply cross into the neighbouring word — the interlock
 * the face was drawn for — so only the two ends need room, and every
 * page keeps at least this much clear either side of its block
 * (`MUSHAF_PAGE_INSET_EM`). Before this was measured the room was
 * whatever half the box slack came to, 0.25 em, and the first word of
 * page 146 lost the tail of its swash to the edge of its view.
 */
export const MUSHAF_INK_RIGHT_EM = 0.36;
export const MUSHAF_INK_LEFT_EM = 0.2;

/**
 * The margin an ordinary page keeps either side of its text block, in ems
 * of the page font.
 *
 * In ems, not a share of the width: the margin's job is to hold the ink
 * that overshoots the line ends (`MUSHAF_INK_RIGHT_EM`), which scales
 * with the font, and then to read as a margin — the print keeps about
 * half an em, and the comparison everyone holds the app against keeps a
 * little less. It used to be 3.5% of the block, which on a phone came to
 * 0.57 em a side on top of the box slack, and the text was set that much
 * smaller for it. Framed plates keep their own, wider rule (`pageInset`).
 */
export const MUSHAF_PAGE_INSET_EM = 0.4;

/**
 * The room a line's view needs beyond its box on each side, in dp, so the
 * ink that overshoots the line ends is inside the view and so drawn.
 */
export function lineInkSidePadding(fontSize: number): { left: number; right: number } {
  if (!(fontSize > 0)) return { left: 0, right: 0 };
  return {
    left: Math.ceil(MUSHAF_INK_LEFT_EM * fontSize),
    right: Math.ceil(MUSHAF_INK_RIGHT_EM * fontSize),
  };
}

/**
 * The QPC page fonts' vertical metrics, in ems: what the platform lays a
 * line out with (hhea ascent 1.2 / descent 0.6 — a handful of pages say
 * 1.1236 / 0.52, which only makes them safer), and how far the INK goes.
 *
 * ── WHY THE INK MATTERS SEPARATELY ────────────────────────────────────
 *
 * Calligraphy does not stay inside its metrics. Across the 604 fonts the
 * tallest glyph reaches 1.62 em above the baseline and the deepest 0.80 em
 * below — a swash under a final nūn, a maddah stacked over an alif. Both
 * platforms lay the line out from the metrics and then keep only what
 * falls inside the text view: Android's `TextView` clips its drawing to
 * its bounds, and iOS rasterises `drawRect:` into a layer the size of the
 * view. So on a page whose lines sit at their natural height the bottom
 * fifth of an em of the deepest words was simply not drawn. Reported
 * 2026-09-03 as text cut off at the bottom of the line, on Android.
 *
 * Measured over the raw fonts, glyph by glyph, with a hair added;
 * `scripts/mushaf/measure_ink_overshoot.py` is where to re-measure (it
 * says 1.6172 / 0.7968 over the glyphs the layout draws).
 */
export const MUSHAF_FONT_ASCENT_EM = 1.2;
export const MUSHAF_FONT_DESCENT_EM = 0.6;
export const MUSHAF_INK_ABOVE_EM = 1.64;
export const MUSHAF_INK_BELOW_EM = 0.82;

/**
 * The padding a line's text view needs above and below its line box so
 * the ink that overshoots the metrics is inside the view, and so drawn.
 *
 * Replays how a line is placed inside `lineHeight`. Both platforms split
 * a positive leading — `lineHeight − (ascent + descent)` — in half above
 * and below (Android's `CustomLineHeightSpan`, iOS's baseline offset). A
 * NEGATIVE leading is where they part: Android still halves it, iOS gives
 * no offset and lets the typesetter take the deficit off one side. So the
 * deficit is assumed to come off EITHER side in full, which over-pads on
 * Android by a few points of transparent view and is right on iOS. The
 * padding is whatever the ink still needs beyond that room, in dp, and
 * zero when the box already holds it.
 */
export function lineInkPadding(
  fontSize: number,
  lineHeight: number,
): { top: number; bottom: number } {
  if (!(fontSize > 0) || !(lineHeight > 0)) return { top: 0, bottom: 0 };
  const metrics = (MUSHAF_FONT_ASCENT_EM + MUSHAF_FONT_DESCENT_EM) * fontSize;
  const leading = lineHeight - metrics;
  const room = leading >= 0 ? leading / 2 : leading;
  const above = MUSHAF_FONT_ASCENT_EM * fontSize + room;
  const below = MUSHAF_FONT_DESCENT_EM * fontSize + room;
  return {
    top: Math.max(0, Math.ceil(MUSHAF_INK_ABOVE_EM * fontSize - above)),
    bottom: Math.max(0, Math.ceil(MUSHAF_INK_BELOW_EM * fontSize - below)),
  };
}

/**
 * How to draw one gap: the size to set the space glyph at, and the letter
 * spacing to add to it. **The letter spacing is never negative.**
 *
 * The gap is a no-break space in AmiriQuran, whose advance is
 * MUSHAF_SPACE_ADVANCE_EM. A line solved for a WIDER space adds the
 * difference as letter spacing, which is what this always did.
 *
 * A line solved for a TIGHTER one used to subtract it — and a third of the
 * mushaf's lines are solved tighter than 0.292 em, because that is what
 * justifying a full line of QPC to the measure asks for. Negative letter
 * spacing is where the missing words came from (issue #6): on the reporter's
 * device the gaps came out at the glyph's own width whatever we asked for, so
 * the line was drawn wider than it was measured for, and Android — which lays
 * a single line out by BREAKING it, between glyphs when nothing else will fit
 * — dropped the last word of it. Every line it happened to was a line asking
 * for a tighter-than-0.292 gap, and no line that asked for a wider one lost
 * anything.
 *
 * So don't ask. Shrink the space glyph instead, and let the letter spacing
 * make up whatever is left, which is then zero or positive by construction.
 * The advance is identical either way, so nothing about the page moves.
 * Scaling DOWN cannot disturb the line box the way scaling up would (a gap
 * set at 2.5x the page size would drag the box's height with it) — and the
 * line height is pinned on the paragraph regardless.
 */
export type MushafGapMetrics = { fontSize: number; letterSpacing: number };

export function gapMetrics(spaceEm: number, fontSize: number): MushafGapMetrics {
  const target = Math.max(0, spaceEm) * fontSize;
  const scale = Math.min(1, Math.max(0, spaceEm) / MUSHAF_SPACE_ADVANCE_EM);
  // Never a font size of nothing: a gap solved to zero (the widest line of
  // an ordinary page) still draws its space glyph, at a size the platform
  // cannot mistake for "unset" — iOS reads 0 as the default size, which
  // is a real gap. One dp of glyph is a third of a pixel of advance.
  const gapFontSize = Math.max(1, fontSize * scale);
  return {
    fontSize: gapFontSize,
    // Zero when the glyph was shrunk to fit exactly; the surplus when the
    // line wants a gap wider than the glyph. Clamped because a float that
    // lands at -1e-15 is still a negative letter spacing.
    letterSpacing: Math.max(0, target - MUSHAF_SPACE_ADVANCE_EM * gapFontSize),
  };
}

/** Gaps between the words of a line (0 for plate and basmalah lines). */
export function lineGapCount(line: MushafLine): number {
  return line.kind === 'ayah' ? Math.max(0, line.words.length - 1) : 0;
}

/**
 * Per-layout and per-line memo tables.
 *
 * Everything they hold is size-independent: the measure a page is set to, the
 * pieces a line decomposes into. None of it involves the font size, the screen
 * width or the orientation — yet it was all recomputed on every render of
 * every line, which on a fullscreen toggle meant several thousand rebuilds of
 * results that could not have changed. Keyed weakly on the decoded objects,
 * which the decode cache owns, so entries go when a page is evicted.
 */
const measureCache = new WeakMap<MushafPageLayout, number>();
const tokenStreamCache = new WeakMap<MushafLine, MushafLinePiece[]>();

/**
 * The page's measure — the width of its text block, in ems of its own font,
 * as the renderer draws it.
 *
 * NOT `layout.measure`: that is the widest line's advances alone, and a line
 * is drawn with a space between every pair of words. Sizing a page from the
 * advances makes every full line render ~15% wider than the box it was sized
 * for. The measure is the widest line as DRAWN at the nominal space.
 */
export function pageMeasureEm(layout: MushafPageLayout): number {
  const memo = measureCache.get(layout);
  if (memo !== undefined) return memo;
  const value = computePageMeasureEm(layout);
  measureCache.set(layout, value);
  return value;
}

function computePageMeasureEm(layout: MushafPageLayout): number {
  // An ordinary page's measure is its widest line's advances — the print
  // adds nothing between the words (`QPC_WORD_SPACE_EM`). The plates keep
  // their nominal space: their lines are set wide in the print too.
  const nominal = nominalSpaceEm(layout);
  let widest = 0;
  for (const line of layout.lines) {
    if (line.kind !== 'ayah') continue;
    const drawn = line.natural + nominal * lineGapCount(line);
    if (drawn > widest) widest = drawn;
  }
  return widest > 0 ? widest : layout.measure;
}

/** The space a page's centred lines are set at, and its measure counts. */
function nominalSpaceEm(layout: MushafPageLayout): number {
  return isFramedPage(layout.page) ? WORD_SPACE_EM : QPC_WORD_SPACE_EM;
}

/**
 * The width of the page's text block, in ems — the measure plus the slack
 * every line's box carries. `fontSize = textWidth / pageBlockEm(layout)`, so
 * the widest line spans the measure and its box still ends exactly at the
 * edge of the block. Nothing the renderer draws ever overflows its parent.
 */
export function pageBlockEm(layout: MushafPageLayout): number {
  return pageMeasureEm(layout) + lineBoxSlackEm();
}

/**
 * The space this line is set at, in ems — solved so the line spans the
 * measure exactly.
 *
 * ── WHY A LINE MAY BE SET WIDER THAN THE BAND ─────────────────────────
 *
 * This used to hand back the NOMINAL space to any line that needed more
 * than `WORD_SPACE_MAX_EM`, so the line came out short and the renderer
 * centred it. That is right for a line the print itself sets short, and
 * wrong for one it sets flush — and the difference is not the size of the
 * gap. Page 177 line 12 (Al-Anfāl 8:6–7) needed 0.776 em, a whisker over
 * the 0.75 band, and was drawn at 81% of the measure with a void at each
 * end: the reported bug.
 *
 * Every page was then measured. Ten lines across 177, 205, 400, 443, 511
 * and 604 asked for more than the band — 0.776 to 1.942 em against the
 * quarter-em measure of the time, a quarter em less now — and every one
 * of them is an ORDINARY MID-SURAH LINE: none carries the `centered`
 * flag, none closes a surah, and the print sets all ten flush to the
 * measure. They ask for a wide gap only because the print set them with
 * few words and wide spacing, which is exactly what `natural` records.
 * Refusing to follow the print there is what made the voids.
 *
 * The cautionary case the band was drawn around — page 1's basmalah,
 * 6.7 em of text across a 12 em plate — is on a FRAMED page, and framed
 * pages keep the band and the centring: their short lines are short in
 * the print too. Everything else follows the print and is capped only by
 * `WORD_SPACE_CEILING_EM`, a guard against corrupt data rather than a
 * matter of taste.
 *
 * See docs/mushaf-fidelity-rules.md §1.
 */
export function lineSpaceEm(
  line: MushafLine,
  measureEm: number,
  opts?: { framed?: boolean },
): number {
  if (line.kind !== 'ayah') return WORD_SPACE_EM;
  const gaps = lineGapCount(line);
  const nominal = opts?.framed ? WORD_SPACE_EM : QPC_WORD_SPACE_EM;
  if (gaps === 0 || line.centered) return nominal;
  const required = (measureEm - line.natural) / gaps;
  // The plates: unchanged. A line that cannot reach the measure inside the
  // band sits at the nominal space and is centred.
  if (opts?.framed) {
    if (required > WORD_SPACE_MAX_EM) return WORD_SPACE_EM;
    return required < WORD_SPACE_MIN_EM ? WORD_SPACE_MIN_EM : required;
  }
  // An ordinary line: whatever closes the gap between its advances and
  // the measure, which the print's own bearings then space. Never below
  // the nominal, which is nothing — the widest line is set touching, as
  // it is in the print.
  if (required < nominal) return nominal;
  return Math.min(required, WORD_SPACE_CEILING_EM);
}

/**
 * Width of a line as drawn, in ems. Never more than the measure — that is the
 * invariant the renderer depends on, since a line wider than its box loses its
 * last word to the platform's single-line truncation.
 */
export function lineWidthEm(
  line: MushafLine,
  measureEm: number,
  opts?: { framed?: boolean },
): number {
  if (line.kind !== 'ayah') return 0;
  return line.natural + lineSpaceEm(line, measureEm, opts) * lineGapCount(line);
}

/**
 * One piece of a drawn line: a run of glyphs, or a gap.
 *
 * A gap is `inner` when it separates the two glyphs of a single token — ~200
 * words across the mushaf carry a hizb or sajdah symbol that way — and the
 * build script budgets those at the nominal space, so the renderer draws them
 * at the nominal space rather than at the line's justified one.
 */
export type MushafLinePiece =
  | { kind: 'glyphs'; text: string; word: MushafWord; index: number }
  | { kind: 'gap'; inner: boolean; index: number };

/**
 * A line, decomposed into what the renderer actually draws.
 *
 * **Every token is treated identically, whatever its glyph count.** That is
 * the whole point of this function existing, because the renderer used to
 * treat them differently: it wrapped multi-glyph tokens in a bidi override
 * (U+202D/U+202C) and left single-glyph tokens bare. QPC numbers its glyphs
 * in reading order, so the bare tokens were already right and it was the
 * override that was wrong — it laid its token out left to right inside a
 * right-to-left line. With the two kinds mixed in one paragraph the bidi
 * algorithm reordered the overridden tokens against their neighbours, and the
 * text of the Quran came out in the wrong order: page 49's rub-el-hizb landed
 * after `وَإِن` instead of before it, and 2:2 read `لَا ۛ فِيهِ ۛ رَيْبَ`.
 *
 * There is no bidi control character in the stream now. The glyphs are in
 * logical order, the paragraph is right-to-left, and the algorithm has one
 * uniform kind of run to lay out — which is the case it gets right.
 */
export function lineTokenStream(line: MushafLine): MushafLinePiece[] {
  const memo = tokenStreamCache.get(line);
  if (memo !== undefined) return memo;
  const value = computeLineTokenStream(line);
  tokenStreamCache.set(line, value);
  return value;
}

function computeLineTokenStream(line: MushafLine): MushafLinePiece[] {
  if (line.kind !== 'ayah') return [];
  const pieces: MushafLinePiece[] = [];
  line.words.forEach((word, i) => {
    if (i > 0) pieces.push({ kind: 'gap', inner: false, index: i });
    word.text.split(' ').forEach((text, k) => {
      if (k > 0) pieces.push({ kind: 'gap', inner: true, index: i });
      pieces.push({ kind: 'glyphs', text, word, index: i });
    });
  });
  return pieces;
}

/** Pages 1–2 are framed plates: centred lines, larger text, own proportions. */
export function isFramedPage(page: number): boolean {
  return page === 1 || page === 2;
}

let raw: RawPage[] | null = null;
/** Decoded pages, keyed by set and page — `cacheKey`. */
const decoded = new Map<string, MushafPageLayout>();

// ---------------------------------------------------------------------------
// Which page fonts are being drawn
//
// The QPC V4 tajwīd fonts (`docs/mushaf-fidelity-rules.md`, "Tajwīd
// colours") carry the same glyph codes as V2, but they are cut from the
// 1441H Madinah print, and that print does not break every page into the
// same fifteen lines as the one V2 follows — page 76 keeps the last words
// of Āl ʿImrān where V2 has An-Nisāʾ's plate, and the plate moves to 77.
// A V4 glyph is justified for the line it sits on in ITS print: laid on
// V2's lines the words came out stretched or cramped, the widest of them
// set a small font size for the whole page, and a line that closes a
// surah was centred in a space it was never cut for. So the tajwīd set
// has its own line data, `mushafLayoutV4.json` (built by
// `scripts/mushaf/build_v4_layout.py` from QUL's 1441H layout, with the
// fonts' own advances), in the same shape as V2's, and a page is decoded
// from whichever file its set names. V2's file is never read for the
// tajwīd set and the tajwīd file never for V2, so the plain muṣḥaf cannot
// be touched by anything here.
//
// Which set is live is a module switch, set by the reader from its
// preference, so that every reader of the geometry — the surface, the
// hit-test, the follow-scroll, the previews — sees one truth at a time
// rather than each being told. The decode cache is keyed by set.
// ---------------------------------------------------------------------------

/** The page-font family in use: the plain V2 faces, or V4's tajwīd colours. */
export type MushafGlyphSet = 'v2' | 'tajweed';

let glyphSet: MushafGlyphSet = 'v2';

export function mushafGlyphSet(): MushafGlyphSet {
  return glyphSet;
}

/**
 * Switch the page fonts. Idempotent and free of side effects — the decode
 * cache is keyed by set — so the reader applies it from its render
 * (`useMushafFontSet`), before its first `getPageLayout` of the frame,
 * rather than from an effect a frame late.
 */
export function setMushafGlyphSet(next: MushafGlyphSet): void {
  glyphSet = next;
}

const cacheKey = (page: number, set: MushafGlyphSet) => `${set}:${page}`;

/** The 1441H print's pages, by page − 1; null where the build has none. */
let rawV4: Array<RawPage | null> | null = null;

function loadRawV4(): Array<RawPage | null> {
  if (rawV4 == null) {
    rawV4 = require('./data/mushafLayoutV4.json') as Array<RawPage | null>;
  }
  return rawV4;
}

function loadRaw(): RawPage[] {
  if (raw == null) {
    // Required lazily: the mushaf reader is one screen of many, and this is
    // the largest data file in the app.
    raw = require('./data/mushafLayoutV2.json') as RawPage[];
  }
  return raw;
}

/** The raw page for a set: the tajwīd file's where it has the page, else V2's. */
function rawPage(page: number, set: MushafGlyphSet): RawPage | null {
  if (set === 'tajweed') {
    const entry = loadRawV4()[page - 1];
    if (entry && entry.p === page) return entry;
  }
  const pages = loadRaw();
  const entry = pages[page - 1];
  if (entry && entry.p === page) return entry;
  return pages.find(p => p.p === page) ?? null;
}

/**
 * Bring the layout data in ahead of the reader, off the critical path.
 *
 * Lazy was right — a user who never opens the muṣḥaf should not pay for
 * 1.4 MB of line data at launch. But lazy on its own meant the first
 * `getPageLayout` of a session did the whole require: six hundred pages
 * of words and advances materialised on the JS thread, in the middle of
 * the push transition, for the first page the reader was trying to draw.
 * That was the hitch on the first open of every session.
 *
 * So the screens a reader passes through on the way — the Qur'an tab, the
 * home card that says "Continue" — ask for it after their own interactions
 * are done. By the time the surah is tapped it is already here; and a
 * user who never gets that far still never pays.
 */
export function warmMushafLayout(riwayah?: RiwayahId): void {
  // A bundled riwayah draws from its own line data, not this file; a Warsh
  // reader warming the Ḥafṣ layout would be paying for a muṣḥaf they are
  // not in.
  if (riwayah && riwayahById(riwayah).render === 'unicode') return;
  loadRaw();
}

function decodeLine(line: RawLine): MushafLine | null {
  if (line.t === 's' || line.t === 'b') {
    return {
      kind: line.t === 's' ? 'surah' : 'basmalah',
      surah: line.s ?? 0,
    };
  }
  const tokens = (line.x ?? '').split('|').filter(Boolean);
  const advances = line.a ?? [];
  const words: MushafWord[] = [];
  let i = 0;
  for (const seg of line.w ?? []) {
    const [surah, ayah, first, count, isEnd] = seg;
    for (let k = 0; k < count; k++) {
      const text = tokens[i++];
      if (text == null) break;
      words.push({
        text,
        advance: advances[i - 1] ?? 0,
        surah,
        ayah,
        position: first + k,
        // Only the LAST word of a run flagged `isEnd` is the medallion.
        isEnd: isEnd === 1 && k === count - 1,
      });
    }
  }
  if (words.length === 0) return null;
  return {
    kind: 'ayah',
    words,
    natural: line.n ?? 0,
    centered: line.c === 1,
  };
}

/** Decoded layout for one page in the live glyph set, or null when the page is out of range. */
export function getPageLayout(page: number): MushafPageLayout | null {
  return getPageLayoutIn(page, glyphSet);
}

/**
 * The same, in a named set — for a surface drawing the tajwīd faces
 * beside a reader that is not (the āyah sheet's Tajweed section), which
 * must not switch the reader's own geometry to get its own.
 */
export function getPageLayoutIn(page: number, set: MushafGlyphSet): MushafPageLayout | null {
  const cached = decoded.get(cacheKey(page, set));
  if (cached) return cached;
  const entry = rawPage(page, set);
  return entry ? decodePage(entry, set) : null;
}

function decodePage(entry: RawPage, set: MushafGlyphSet): MushafPageLayout {
  const key = cacheKey(entry.p, set);
  const cached = decoded.get(key);
  if (cached) return cached;
  const lines = entry.l
    .map(line => decodeLine(line))
    .filter((l): l is MushafLine => l != null);
  const layout: MushafPageLayout = {
    page: entry.p,
    measure: entry.m,
    lines,
  };
  decoded.set(key, layout);
  // The reader only ever holds a few pages; keep the decode cache near that.
  if (decoded.size > 24) {
    const oldest = decoded.keys().next().value;
    if (oldest != null && oldest !== key) decoded.delete(oldest);
  }
  return layout;
}

/** Every ayah that appears on a page, in reading order. */
export function ayahsOnPage(page: number): Array<{ surah: number; ayah: number }> {
  const layout = getPageLayout(page);
  if (!layout) return [];
  const out: Array<{ surah: number; ayah: number }> = [];
  for (const line of layout.lines) {
    if (line.kind !== 'ayah') continue;
    for (const w of line.words) {
      const last = out[out.length - 1];
      if (!last || last.surah !== w.surah || last.ayah !== w.ayah) {
        out.push({ surah: w.surah, ayah: w.ayah });
      }
    }
  }
  return out;
}

/** Surahs whose name plate is printed on this page. */
export function surahHeadersOnPage(page: number): number[] {
  const layout = getPageLayout(page);
  if (!layout) return [];
  return layout.lines
    .filter(l => l.kind === 'surah')
    .map(l => (l as { surah: number }).surah);
}

/** Test seam. */
export function _resetLayoutCache(): void {
  decoded.clear();
  glyphSet = 'v2';
}
