/**
 * GENERATED by scripts/build-release-notes.js — do not edit.
 *
 * The store's own release notes, joined to the version name and date they
 * shipped under. Newest first. Run `npm run build-release-notes` after
 * adding a note under fastlane/metadata/android/<locale>/changelogs/.
 */

export type ReleaseNote = {
  /** Android versionCode — the key the note files are named by. */
  code: number;
  /** The name a reader knows it as, e.g. '2.18.5'. */
  version: string;
  /** ISO date of the release tag. Null only if git could not date it. */
  date: string | null;
  /** Locale code to the note's raw text. 'en' is always present. */
  notes: Record<string, string>;
};

export const RELEASE_NOTES: ReleaseNote[] = [
  {
    code: 282,
    version: '2.27.1',
    date: '2026-09-26',
    notes: {
      en: '• Shared month sheets carry the new tagline: Mihrab — The Muslim Companion.\n• The app\'s links to its source, releases and downloads now point to its new home, github.com/MihrabHQ/Mihrab. The old links keep working.',
      ar: '• جداول الشهر المشارَكة تحمل الوصف الجديد: محراب — رفيق المسلم.\n• روابط التطبيق إلى الشيفرة المصدرية والإصدارات والتنزيلات تشير الآن إلى موطنه الجديد github.com/MihrabHQ/Mihrab، والروابط القديمة ما زالت تعمل.',
      sv: '• Delade månadsblad har fått den nya undertiteln: Mihrab — Muslimens följeslagare.\n• Appens länkar till källkod, versioner och nedladdningar pekar nu på dess nya hem, github.com/MihrabHQ/Mihrab. De gamla länkarna fungerar fortfarande.',
    },
  },
  {
    code: 281,
    version: '2.27.0',
    date: '2026-09-26',
    notes: {
      en: '• New: Tajweed colours on the Warsh muṣḥaf, with Warsh\'s own rules — naql, tashīl, taqlīl and more — explained in the guide.\n• Fullscreen reading: an exit button and the page number at the top, and a smooth fade in and out.\n• Tajweed colours download in the background as soon as you turn them on.\n• The āyah sheet shows the āyah in the muṣḥaf\'s own font.\n• Khatmah options no longer run off the screen.',
      ar: '• جديد: ألوان التجويد في مصحف ورش، مع أحكام ورش الخاصة — النقل والتسهيل والتقليل وغيرها — مشروحة في الدليل.\n• القراءة بملء الشاشة: زر للخروج ورقم الصفحة في الأعلى، وانتقال سلس عند الدخول والخروج.\n• تُنزَّل ألوان التجويد في الخلفية بمجرد تفعيلها.\n• تظهر الآية في بطاقة الآية بخط المصحف نفسه.\n• خيارات الختمة لم تعد تخرج عن حدود الشاشة.',
      sv: '• Nytt: tajwīd-färger i Warsh-muṣḥafen, med Warshs egna regler — naql, tashīl, taqlīl med flera — förklarade i guiden.\n• Helskärmsläsning: en stängknapp och sidnumret överst, och en mjuk övertoning in och ut.\n• Tajwīd-färgerna laddas ner i bakgrunden så fort du slår på dem.\n• Versbladet visar versen i muṣḥafens eget typsnitt.\n• Khatmah-valen hamnar inte längre utanför skärmen.',
    },
  },
  {
    code: 280,
    version: '2.26.0',
    date: '2026-09-24',
    notes: {
      en: '• New: Tajweed colours for the muṣḥaf — each letter shown in the ink of its recitation rule, with a guide and per-rule detail on every āyah. Turn it on in Settings → Quran.\n• New (Android): let the phone go quiet for the prayer itself and come back on its own — Settings → Notifications.\n• The muṣḥaf page is set closer to the print: tighter word spacing, and lines that no longer clip or drop a word.\n• Moroccan prayer times refreshed from the Ministry of Habous.',
      ar: '• جديد: ألوان التجويد في المصحف — كل حرف بلون حكمه، مع دليل وتفاصيل كل حكم عند كل آية. فعّلها من الإعدادات ← القرآن.\n• جديد (أندرويد): أسكت الهاتف وقت الصلاة نفسها، ثم يعود صوته تلقائيًا بعدها — الإعدادات ← الإشعارات.\n• صفحة المصحف أقرب الآن إلى المطبوع: تباعد أضيق بين الكلمات، وأسطر لا تُقصّ ولا تُسقط كلمة.\n• تحديث مواقيت الصلاة في المغرب من وزارة الأوقاف.',
      sv: '• Nytt: tajwīd-färger i muṣḥafen — varje bokstav i sin regels egen färg, med en guide och regeldetaljer vid varje vers. Slå på den i Inställningar → Koranen.\n• Nytt (Android): låt telefonen tystna helt vid bönen och slå på sig själv igen efteråt — Inställningar → Aviseringar.\n• Muṣḥaf-sidan följer nu tryckta koranen närmare: tätare ordmellanrum, och rader som varken klipps eller tappar ett ord.\n• Marockos bönetider uppdaterade från ministeriet för Habous.',
    },
  },
  {
    code: 279,
    version: '2.25.1',
    date: '2026-09-22',
    notes: {
      en: '• Word reader: hold a word in the muṣḥaf, slide to another if you like, and lift to hear that one word. Turn it on in Settings → Quran → Word reader.\n• The muṣḥaf\'s night page is true black.\n• Sync no longer undoes khatmah reading done on your other device.\n• Khatmah by a date: tomorrow\'s portion is marked where it really ends.\n• Android: the app keeps its own text with a system theme font, and the ayah number sits inside its rosette.',
      ar: '• قارئ الكلمة: اضغط مطوّلًا على كلمة في المصحف، وحرّك إصبعك إلى غيرها إن شئت، ثم ارفعه لتسمعها وحدها. فعّله من الإعدادات ← القرآن ← قارئ الكلمة.\n• صفحة المصحف الليلية سوداء تمامًا.\n• لم تعد المزامنة تلغي ما قرأته من الختمة على جهازك الآخر.\n• الختمة بتاريخ: يُعلَّم ورد الغد حيث ينتهي فعلًا.\n• أندرويد: يحتفظ التطبيق بخطّه مع خط سمة النظام، ويستقر رقم الآية داخل زخرفته.',
      sv: '• Ordläsare: håll fingret på ett ord i muṣḥafen, dra till ett annat om du vill, och släpp för att höra just det ordet. Slå på den i Inställningar → Koranen → Ordläsare.\n• Muṣḥafens nattsida är helt svart.\n• Synkningen ångrar inte längre khatmah-läsning från din andra enhet.\n• Khatmah till ett datum: morgondagens del markeras där den faktiskt slutar.\n• Android: appen behåller sin egen text med ett temateckensnitt, och versnumret hamnar inuti sin rosett.',
    },
  },
  {
    code: 278,
    version: '2.25.0',
    date: '2026-09-21',
    notes: {
      en: '• Khatmah by a date: choose when to finish, and each day\'s portion is worked out from what is left. Switch between days and a date at any time from the ⋯ menu.\n• Sync no longer brings back a khatmah marker you removed, or pulls your progress back.\n• A download cut off by the connection keeps what it has — continue it, or it resumes by itself on Wi-Fi.\n• When the clocks change where you are, prayer times refresh at once.\n• Pull down on Today to refresh the times.',
      ar: '• الختمة بتاريخ: اختر متى تنتهي، ويُحسب ورد كل يوم مما بقي. بدّل بين عدد الأيام والتاريخ في أي وقت من قائمة ⋯.\n• لم تعد المزامنة تعيد علامة ختمة حذفتها، ولا ترجع تقدّمك إلى الوراء.\n• التنزيل الذي ينقطع بانقطاع الاتصال يحتفظ بما نزل — أكمله، أو يستأنف وحده على الواي فاي.\n• عند تغيير الساعة في مكانك تتحدّث أوقات الصلاة فورًا.\n• اسحب للأسفل في «اليوم» لتحديث الأوقات.',
      sv: '• Khatmah till ett datum: välj när du vill bli klar, så räknas varje dags del ut från det som återstår. Byt mellan dagar och datum när som helst i ⋯-menyn.\n• Synkningen återställer inte längre en borttagen khatmah-markör och drar inte tillbaka dina framsteg.\n• En avbruten nedladdning behåller det som hunnit laddas — fortsätt den, eller låt den fortsätta av sig själv på wifi.\n• När klockan ställs om där du är uppdateras bönetiderna direkt.\n• Dra nedåt på Idag för att uppdatera tiderna.',
    },
  },
  {
    code: 277,
    version: '2.24.1',
    date: '2026-09-20',
    notes: {
      en: '• Mac: the muṣḥaf no longer shows three page columns with the left one running under the index after switching back to it from another full-screen app.\n• Mac: the bar above the page is the colour of the page, and the surah name is centred over the page rather than over the window.\n• Mac and iPad: in fullscreen the surah name is shown in full again, instead of a letter and an ellipsis.\n• The left and right arrow keys turn pages again after searching in the index.',
      ar: '• ماك: لم يعد المصحف يعرض ثلاثة أعمدة للصفحات مع اختفاء الأيسر تحت الفهرس عند العودة إليه من تطبيق آخر بملء الشاشة.\n• ماك: الشريط فوق الصفحة صار بلون الصفحة، واسم السورة صار في وسط الصفحة لا في وسط النافذة.\n• ماك وآيباد: في وضع ملء الشاشة يظهر اسم السورة كاملًا مرة أخرى، بدل حرف وثلاث نقاط.\n• مفتاحا السهمين يمين ويسار يقلبان الصفحات من جديد بعد البحث في الفهرس.',
      sv: '• Mac: mushafen visar inte längre tre sidkolumner med den vänstra under registret när du växlar tillbaka från en annan helskärmsapp.\n• Mac: listen ovanför sidan har sidans färg, och suranamnet är centrerat över sidan i stället för över fönstret.\n• Mac och iPad: i helskärm visas suranamnet helt igen, i stället för en bokstav och tre punkter.\n• Vänster- och högerpilarna bläddrar igen efter en sökning i registret.',
    },
  },
  {
    code: 276,
    version: '2.24.0',
    date: '2026-09-18',
    notes: {
      en: '• A bookmark can follow your reading, so it stays where you stopped — or stay pinned to its ayah. Each bookmark has its own switch.\n• Khatmah progress is the pages you actually read. Mark a page read or unread beside the surah name; pages you skipped are counted and can be gone back to.\n• A dot beside the surah name says which of your places is recording.\n• New: start the day at sunset, so an evening\'s reading counts towards the day that has begun (Settings → Quran).',
      ar: '• يمكن للعلامة أن تتبع قراءتك فتبقى حيث توقفت — أو تثبت على آيتها. لكل علامة مفتاحها.\n• تقدّم الختمة صار الصفحات التي قرأتها فعلًا. علّم الصفحة مقروءة أو غير مقروءة بجانب اسم السورة؛ والصفحات التي تخطّيتها تُحصى ويمكن العودة إليها.\n• نقطة بجانب اسم السورة تبيّن أيّ مواضعك يسجّل الآن.\n• جديد: ابدأ اليوم من المغرب، فتُحسب قراءة المساء لليوم الذي بدأ للتو (الإعدادات ← القرآن).',
      sv: '• Ett bokmärke kan följa din läsning, så det ligger där du slutade — eller stanna på sin vers. Varje bokmärke har sin egen knapp.\n• Khatmah-framsteget är de sidor du faktiskt läst. Markera en sida som läst eller oläst intill surans namn; överhoppade sidor räknas och går att återvända till.\n• En prick intill surans namn visar vilken av dina platser som spelar in.\n• Nytt: låt dygnet börja vid solnedgången, så att en kvälls läsning räknas till dygnet som just börjat (Inställningar → Koranen).',
    },
  },
  {
    code: 275,
    version: '2.23.0',
    date: '2026-09-17',
    notes: {
      en: '• Deleting a khatmah no longer brings it back. On a paired device the plan returned within a sync round or two; an abandoned plan now stays abandoned everywhere.\n• The screen stays on in the verse-by-verse reader too — it already did in the mushaf and Tilawah — with a switch for it in Settings → Quran.\n• System colours (Material You) now work with Light or Dark chosen, not only System.\n• The khatmah card says "days of reading left", and how many pages behind you are.',
      ar: '• حذف الختمة لم يعد يعيدها. على جهاز مقترن كانت الخطة تعود بعد جولة مزامنة أو اثنتين؛ والآن تبقى محذوفة على كل الأجهزة.\n• تبقى الشاشة مضاءة في قارئ الآية بالآية أيضًا — وكانت كذلك في المصحف والتلاوة — مع مفتاح لها في الإعدادات ← القرآن.\n• ألوان النظام تعمل الآن مع اختيار الفاتح أو الداكن، لا مع «النظام» فقط.\n• بطاقة الختمة تقول «أيام القراءة المتبقية»، وكم صفحة تأخرت.',
      sv: '• Att radera en khatmah tar inte tillbaka den längre. På en parkopplad enhet kom planen åter efter en synk eller två; en avslutad plan förblir nu borta överallt.\n• Skärmen förblir tänd även i vers-för-vers-läsaren — det gjorde den redan i mushafen och Tilawah — med en knapp för det i Inställningar → Koranen.\n• Systemfärger (Material You) fungerar nu med Ljust eller Mörkt valt, inte bara System.\n• Khatmah-kortet säger "dagar kvar att läsa", och hur många sidor efter du ligger.',
    },
  },
  {
    code: 274,
    version: '2.22.0',
    date: '2026-09-16',
    notes: {
      en: '• A colour theme now sits inside Appearance — green, teal, blue, amber, rose or violet themes dark mode, and Classic puts the app\'s own paper and ink back. It takes the place of system colours rather than sitting beside them.\n• The mushaf page bar and the ornament at the start of each surah take the theme\'s colour instead of losing it on a night page.\n• Back up to a file: Save to Files on every platform, and import by picking the file rather than pasting the text.',
      ar: '• صارت سمة الألوان داخل المظهر — أخضر أو فيروزي أو أزرق أو كهرماني أو وردي أو بنفسجي تُلوّن الوضع الداكن، و«كلاسيكي» يعيد ورق التطبيق وحبره كما كانا. تحلّ محلّ ألوان النظام بدل أن تكون إلى جانبها.\n• شريط الصفحة في المصحف وزخرفة بداية كل سورة يأخذان لون السمة بدل أن يفقداه في الصفحة الليلية.\n• نسخة احتياطية في ملف: «حفظ في الملفات» على كل الأنظمة، والاستيراد باختيار الملف بدل لصق النص.',
      sv: '• Ett färgtema finns nu i Utseende — grönt, turkost, blått, bärnsten, rosa eller violett färgar mörkt läge, och Klassisk ger appen dess eget papper och bläck tillbaka. Det ersätter systemfärgerna i stället för att ligga bredvid dem.\n• Sidlisten i mushafen och ornamentet vid varje suras början tar temats färg i stället för att tappa den på en mörk sida.\n• Säkerhetskopiera till en fil: Spara till Filer på alla plattformar, och importera genom att välja filen i stället för att klistra in text.',
    },
  },
  {
    code: 273,
    version: '2.21.1',
    date: '2026-09-14',
    notes: {
      en: '• Save a location without naming it — leave the name blank and it takes the city\'s own name.\n• Switching between saved locations is instant now, and flipping quickly back and forth no longer stalls on a blank screen.\n• "Add new location" from the home chip switches to the place you add — on automatic location too, not just manual.\n• Searching for a city to add it now says "Location selected", so it\'s clear the place is only saved when you tap Save.',
      ar: '• احفظ موقعًا دون تسميته — اترك الاسم فارغًا فيأخذ اسم المدينة نفسها.\n• التبديل بين المواقع المحفوظة صار فوريًا، والتبديل السريع ذهابًا وإيابًا لم يعد يتوقف عند شاشة فارغة.\n• "إضافة موقع جديد" من شارة الموقع تنتقل إلى المكان الذي تضيفه — في الوضع التلقائي أيضًا، لا اليدوي فقط.\n• البحث عن مدينة لإضافتها يقول الآن "تم اختيار الموقع"، ليتضح أن المكان يُحفظ فقط عند الضغط على حفظ.',
      sv: '• Spara en plats utan att namnge den — lämna namnet tomt så tar den stadens eget namn.\n• Att växla mellan sparade platser går direkt nu, och att snabbt växla fram och tillbaka fastnar inte längre på en tom skärm.\n• "Lägg till ny plats" från platsknappen växlar till platsen du lägger till — även i automatiskt läge, inte bara manuellt.\n• Att söka en stad för att lägga till den säger nu "Plats vald", så det är tydligt att platsen sparas först när du trycker Spara.',
    },
  },
  {
    code: 272,
    version: '2.21.0',
    date: '2026-09-14',
    notes: {
      en: '• The muṣḥaf is the reader now. The verse-by-verse list is a setting — already on if you were using it, and first launch asks.\n• Today turns to tomorrow once the last time of the day has passed.\n• A − A + for the translation and tafsīr sits in the bar, not at the top of the surah.\n• The back arrow points the right way in Arabic and Urdu.\n• A khatmah keeps counting instead of quietly stopping.\n• Tab labels stay clear of rounded screen corners.\n• A faster start, and a smaller download.',
      ar: '• المصحف هو القارئ الآن. وقائمة الآيات صارت إعدادًا — مفعّلة إن كنت تستعملها، وأول تشغيل يسأل.\n• اليوم يصير غدًا متى انقضى آخر وقت في اليوم.\n• أزرار A − A + للترجمة والتفسير في الشريط، لا أعلى السورة.\n• سهم الرجوع يشير إلى الجهة الصحيحة في العربية والأردية.\n• الختمة تواصل العدّ بدل أن تتوقف بصمت.\n• عناوين التبويبات تبتعد عن زوايا الشاشة المستديرة.\n• بدء أسرع، وتنزيل أصغر.',
      sv: '• Mushafen är läsaren nu. Vers-för-vers-listan är en inställning — redan på om du använde den, och första starten frågar.\n• I dag blir till i morgon när dagens sista tid har passerat.\n• A − A + för översättning och tafsir sitter i verktygsfältet, inte överst i suran.\n• Bakåtpilen pekar åt rätt håll på arabiska och urdu.\n• En khatma fortsätter räkna i stället för att tyst sluta.\n• Fliketiketterna håller sig undan skärmens rundade hörn.\n• Snabbare start, och mindre nedladdning.',
    },
  },
  {
    code: 271,
    version: '2.20.0',
    date: '2026-09-13',
    notes: {
      en: '• Sheets scroll again. The changelog, and every other sheet, ignored a slow finger and moved only for a flick.\n• In the muṣḥaf, back leaves fullscreen instead of leaving the app.\n• A khatmah no longer freezes when one fast swipe crosses several pages.\n• Today\'s target in the reader, beside the page number.\n• Two Warsh reciters, and an ayah tapped in Warsh gives the Warsh wording.\n• The adhkār keep the way back on screen, and sharing a dua asks what to send.',
      ar: '• عادت الأوراق المنبثقة إلى التمرير. سجل التغييرات وغيره كان يتجاهل الإصبع البطيء ولا يستجيب إلا لنقرة سريعة.\n• في المصحف: زر الرجوع يخرج من ملء الشاشة لا من التطبيق.\n• الختمة لم تعد تتجمد حين يعبر تمرير سريع عدة صفحات.\n• هدف اليوم داخل القارئ، بجانب رقم الصفحة.\n• قارئان برواية ورش، والآية المنقورة في ورش تظهر بنصها في ورش.\n• الأذكار تُبقي طريق العودة ظاهرًا، ومشاركة الدعاء تسأل ماذا تُرسل.',
      sv: '• Blad går att skrolla igen. Ändringsloggen, och alla andra blad, struntade i ett långsamt finger och rörde sig bara för en snärt.\n• I mushafen lämnar bakåtknappen helskärm i stället för appen.\n• En khatma fryser inte längre när ett snabbt svep hoppar över flera sidor.\n• Dagens mål i läsaren, bredvid sidnumret.\n• Två warsh-recitatörer, och en ayah i warsh visar warsh-texten.\n• Adhkār behåller vägen tillbaka på skärmen, och delning av en dua frågar vad som ska med.',
    },
  },
  {
    code: 270,
    version: '2.19.0',
    date: '2026-09-13',
    notes: {
      en: '• A new first launch: the four questions that decide whether the app suits you, each answered in your own times.\n• Any accent colour you like — the picker offers only ones that stay readable.\n• The sky behind the countdown is lit from where the sun really is, and the moon is your own sky\'s.\n• Set the size of the translation, tafsir and pronunciation.\n• What changed after each update, and the whole changelog in Settings → About.\n• The Sky widget is gone; that drawing lives in the app.',
      ar: '• بداية جديدة عند أول تشغيل: أربعة أسئلة تحدّد ملاءمة التطبيق لك، وكل إجابة تُعرض بأوقاتك أنت.\n• أي لون تميّز تختاره — والمنتقي لا يعرض إلا ما يبقى مقروءًا.\n• السماء خلف العدّ التنازلي مضاءة من موضع الشمس الحقيقي، والقمر قمر سمائك أنت.\n• تحكّم في حجم الترجمة والتفسير والنطق.\n• ما الجديد بعد كل تحديث، وسجل التغييرات كاملًا في الإعدادات ← حول.\n• أداة «السماء» لم تعد موجودة؛ فهذا الرسم يعيش داخل التطبيق.',
      sv: '• En ny första start: de fyra frågor som avgör om appen passar dig, var och en besvarad med dina egna tider.\n• Vilken accentfärg du vill — väljaren erbjuder bara de som förblir läsbara.\n• Himlen bakom nedräkningen lyses av där solen faktiskt står, och månen är din egen himmels.\n• Ställ in storleken på översättning, tafsir och uttal.\n• Vad som ändrats efter varje uppdatering, och hela ändringsloggen i Inställningar → Om.\n• Himmel-widgeten är borta; teckningen bor i appen.',
    },
  },
  {
    code: 269,
    version: '2.18.5',
    date: '2026-09-11',
    notes: {
      en: '• "Continue reading" lands on the ayah again — and reading keeps its own place, separate from the khatmah, with its own marker on the page.\n• The check on Today asks what the moment leaves open: on time or late while the second time runs, all four once the window has gone.\n• A tapped adhkār reminder opens those adhkār.\n• A surah\'s recitation download survives leaving the page, with a progress notification.\n• Surah names in calligraphy are set to one weight.',
      ar: '• «متابعة القراءة» تفتح عند الآية نفسها — وللقراءة الآن موضعها الخاص، منفصلًا عن الختمة، وله علامته على الصفحة.\n• علامة اليوم تسأل بحسب الوقت: «في وقتها» أو «متأخرة» ما دام الوقت الضروري قائمًا، والحالات الأربع بعد خروج الوقت.\n• تذكير أذكار الصباح والمساء يفتح تلك الأذكار عند الضغط عليه.\n• تنزيل تلاوة سورة يستمر بعد مغادرة الصفحة، مع إشعار بشريط تقدّم وسطر أعلى صفحة القرآن.\n• أسماء السور بخط واحد متناسق.',
      sv: '• ”Fortsätt läsa” landar på versen igen — och läsningen har ett eget ställe, skilt från khatman, med en egen markör på sidan.\n• Bocken på Idag frågar det stunden lämnar öppet: i tid eller sent medan andra tiden löper, alla fyra när tiden gått ut.\n• En tryckt adhkar-påminnelse öppnar just de adhkar.\n• Nedladdning av en surahs recitation överlever att man lämnar sidan, med en avisering med förloppsindikator.\n• Surornas namn i kalligrafi är satta i en och samma vikt.',
    },
  },
  {
    code: 268,
    version: '2.18.4',
    date: '2026-09-09',
    notes: {
      en: '• A day bar under the sky: a chevron at each edge steps a day, with the date between them in both calendars.\n• Turned back to an earlier day, that same block is the way home — "Back to today".\n• On a tablet held upright the sky stops stretching: it takes a measured height and the whole day sits centred on the page.\n• Fresh screenshots in every store and on the site.',
      ar: '• شريط لليوم تحت السماء: سهم عند كل حافة ينقلك يومًا، والتاريخ بينهما بالتقويمين.\n• وإذا رجعت إلى يوم مضى صار الشريط نفسه طريق العودة — «العودة إلى اليوم».\n• على اللوح الرأسي لم تعد السماء تتمدد: تأخذ ارتفاعًا مقدّرًا ويستقر اليوم كله في وسط الصفحة.\n• صور جديدة للتطبيق في كل متجر وعلى الموقع.',
      sv: '• En dagrad under himlen: en pil vid varje kant stegar en dag, och datumet står mellan dem i båda kalendrarna.\n• Har du bläddrat till en tidigare dag är samma ruta vägen hem — ”Tillbaka till idag”.\n• På en surfplatta i stående läge slutar himlen att växa: den får en avmätt höjd och hela dagen står centrerad på sidan.\n• Nya skärmbilder i varje butik och på webbplatsen.',
    },
  },
  {
    code: 267,
    version: '2.18.3',
    date: '2026-09-09',
    notes: {
      en: '• Today\'s table swipes back a week as well as forward — log a prayer on the day you missed it, where it happened.\n• Tap the check on a prayer whose time has passed and it asks: prayed on time, or made up?\n• A clearer line under the countdown — the weekday, both dates, and the way back to today.\n• The Quran row is smaller, and says "Start reading" when nothing has begun.\n• The prayer rows sit on the screen\'s own edges.',
      ar: '• جدول اليوم يُسحب أسبوعًا إلى الوراء كما يُسحب إلى الأمام — سجّل الصلاة في يومها الذي فاتتك فيه.\n• إذا ضغطت على علامة صلاة مضى وقتها سُئلت: أصُلّيت في وقتها أم قُضيت؟\n• سطر أوضح تحت العدّ التنازلي: اليوم من الأسبوع، والتاريخان، والعودة إلى اليوم.\n• سطر القرآن أصغر، ويقول «ابدأ القراءة» إذا لم تبدأ بعد.\n• صفوف الصلوات صارت على حواف الشاشة نفسها.',
      sv: '• Dagens tabell sveps bakåt en vecka lika väl som framåt — logga en bön på den dag du missade den.\n• Trycker du på bocken för en bön vars tid har passerat får du frågan: bads den i tid, eller togs den igen?\n• Tydligare rad under nedräkningen — veckodagen, båda datumen och vägen tillbaka till idag.\n• Koranraden är mindre och säger ”Börja läsa” när inget har påbörjats.\n• Bönraderna ligger mot skärmens egna kanter.',
    },
  },
  {
    code: 266,
    version: '2.18.2',
    date: '2026-09-09',
    notes: {
      en: '• A prayer log that could not be read is no longer written over. A moment\'s storage hiccup could leave the Log looking empty, and the next tap replaced your whole record with that one prayer. Every writer now refuses until the record can be read.\n• Once a prayer\'s first time has passed, its row says when the second time ends.\n• The sun crosses the sky once, from where it rises to where it sets.\n• The sky no longer mirrors in right-to-left languages.',
      ar: '• سجلّ الصلاة الذي تعذّرت قراءته لا يُكتب فوقه بعد الآن. كان خلل تخزين لحظي يُظهر السجلّ فارغًا، فتستبدل الضغطة التالية سجلّك كله بتلك الصلاة الواحدة. الآن ترفض كل كتابة حتى يُقرأ السجلّ.\n• بعد مضيّ الوقت الاختياري للصلاة، يبيّن صفّها متى ينتهي الوقت الضروري.\n• الشمس تعبر السماء مرة واحدة، من مشرقها إلى مغربها.\n• السماء لم تعد تنعكس في اللغات المكتوبة من اليمين إلى اليسار.',
      sv: '• En bönelogg som inte kunde läsas skrivs inte längre över. Ett kort lagringsfel kunde få loggen att se tom ut, och nästa tryck ersatte hela din historik med den ena bönen. Nu vägrar varje skrivning tills loggen kan läsas.\n• När en böns första tid har passerat visar raden när den andra tiden tar slut.\n• Solen går över himlen en gång, från där den går upp till där den går ner.\n• Himlen speglas inte längre i höger-till-vänster-språk.',
    },
  },
  {
    code: 265,
    version: '2.18.1',
    date: '2026-09-09',
    notes: {
      en: '• A new Today screen: one page, no scrolling, with a sky behind the countdown that follows the day — night and its moon, dawn, noon, sunset.\n• Log a prayer with one tap, from Today.\n• Surah names in the muṣḥaf\'s own calligraphy, throughout the Quran.\n• Tilāwah is a player: continue where you stopped, play, next, shuffle.\n• A Sky widget for the home screen, and steadier widgets.\n• The muṣḥaf\'s tone can follow the app\'s theme.\n• Every screen redrawn: quieter chrome, one voice of colour.',
      ar: '• شاشة "اليوم" من جديد: صفحة واحدة بلا تمرير، وخلف العدّ التنازلي سماء تتبع اليوم — ليل بقمره، وفجر، وظهيرة، وغروب.\n• سجّل الصلاة بضغطة واحدة من شاشة اليوم.\n• أسماء السور بخط المصحف نفسه، في القرآن كله.\n• التلاوة صارت مشغّلًا: تابع من حيث وقفت، تشغيل، التالي، عشوائي.\n• أداة "السماء" للشاشة الرئيسية، وأدوات أثبت عمومًا.\n• لون صفحة المصحف يمكن أن يتبع سمة التطبيق.\n• كل شاشة أُعيد رسمها: إطار أهدأ، ولون واحد.',
      sv: '• Ny startskärm: en sida utan rullning, med en himmel bakom nedräkningen som följer dygnet — natt med sin måne, gryning, middag, solnedgång.\n• Logga en bön med ett tryck, direkt från startskärmen.\n• Surornas namn i muṣḥafens egen kalligrafi, i hela Koranen.\n• Tilāwah är nu en spelare: fortsätt där du slutade, spela, nästa, blanda.\n• En himmelswidget till hemskärmen, och stabilare widgetar överlag.\n• Muṣḥafens sidton kan följa appens tema.\n• Varje skärm omritad: lugnare ramverk, en färgton.',
    },
  },
  {
    code: 264,
    version: '2.18.0',
    date: '2026-09-08',
    notes: {
      en: '• Dhikr reminders: set your own, at any time of day, fully offline.\n• Reminders for Surah Al-Kahf on Friday, Al-Mulk at night, and the morning and evening adhkar.\n• Pick your school — Hanafi, Maliki, Shafi\'i or Hanbali — and the times and names follow it.\n• A second Spanish translation: Isa Garcia, beside Cortes.\n• Duas: every category on one screen, grouped, plus the lavatory and dressing duas.\n• Tapping a notification or a prayer widget now opens the screen it is about.',
      ar: '• تذكيرات الذكر: اضبط تذكيراتك أنت، في أي وقت من اليوم، وتعمل دون اتصال.\n• تذكير بسورة الكهف يوم الجمعة، والملك ليلًا، وبأذكار الصباح والمساء.\n• اختر مذهبك — حنفي أو مالكي أو شافعي أو حنبلي — فتتبعه الأوقات والأسماء.\n• ترجمة إسبانية ثانية: عيسى غارسيا، إلى جانب كورتيس.\n• الأدعية: كل الأقسام في شاشة واحدة مرتبة في مجموعات، مع أدعية الخلاء واللباس.\n• الضغط على إشعار أو على أداة الصلاة صار يفتح الشاشة التي يتحدث عنها.',
      sv: '• Dhikr-påminnelser: sätt dina egna, när som helst på dygnet, helt offline.\n• Påminnelser för sura Al-Kahf på fredagar, Al-Mulk på natten och för morgonens och kvällens adhkar.\n• Välj din skola — hanafi, maliki, shafi\'i eller hanbali — så följer tider och namn den.\n• En andra spansk översättning: Isa García, vid sidan av Cortés.\n• Duor: alla kategorier på en skärm, grupperade, plus duorna för toaletten och påklädning.\n• Ett tryck på en avisering eller en bönewidget öppnar nu rätt skärm.',
    },
  },
  {
    code: 263,
    version: '2.17.1',
    date: '2026-09-07',
    notes: {
      en: '• The practice graph fills the card it is drawn on. It was built for two thirds of the space the card actually gives it, so it floated in the middle with a band of empty card above and below — a 4x4 now draws eight rows of history where it drew six.\n• Fixed: on the Log card the graph came out slightly too large for its box, so every square was scaled down and the grid stood away from both edges.',
      ar: '• صار مخطط المداومة يملأ البطاقة التي يُرسم عليها. كان يُبنى على ثلثي المساحة التي تمنحها له البطاقة فعلًا، فيطفو في وسطها بفراغ فوقه وتحته — وحجم 4×4 صار يرسم ثمانية صفوف من السجل بدل ستة.\n• إصلاح: في بطاقة السجل كان المخطط أكبر قليلًا من صندوقه، فتصغُر كل مربعاته ويبتعد الشبك عن الحافتين.',
      sv: '• Övningsgrafen fyller kortet den ritas på. Den byggdes för två tredjedelar av utrymmet kortet faktiskt ger den, så den svävade i mitten med ett band tomt kort ovanför och under — en 4x4 ritar nu åtta rader historik där den ritade sex.\n• Rättat: på Logg-kortet blev grafen aningen för stor för sin ruta, så varje kvadrat skalades ner och rutnätet stod ifrån båda kanterna.',
    },
  },
  {
    code: 262,
    version: '2.17.0',
    date: '2026-09-07',
    notes: {
      en: '• Send a dua or a passage of tafsir to someone, as text — with its source, and in the language you are reading it in.\n• The Continue Reading widget has a play button: one tap opens where you left off and starts the recitation there.\n• Fixed: a prayer time could break across two lines on some system fonts; the tasbih widget slowed down as the count grew; the reading widget cut off its last line at its default size; a Qur\'an download could hang instead of failing.',
      ar: '• أرسل دعاءً أو مقطعًا من التفسير إلى من تشاء، نصًّا — مع مصدره، وباللغة التي تقرأ بها.\n• أداة «متابعة القراءة» صار فيها زر تشغيل: نقرة واحدة تفتح موضعك وتبدأ التلاوة منه.\n• إصلاحات: كان وقت الصلاة ينكسر على سطرين مع بعض خطوط النظام؛ وكانت أداة التسبيح تبطؤ كلما زاد العدّ؛ وكانت أداة القراءة تقصّ سطرها الأخير في حجمها الافتراضي؛ وكان تنزيل القرآن قد يعلّق بدل أن يفشل.',
      sv: '• Skicka en dua eller ett stycke tafsir till någon, som text — med källa, och på språket du läser på.\n• Widgeten Fortsätt läsa har en uppspelningsknapp: ett tryck öppnar där du slutade och startar recitationen där.\n• Rättat: en bönetid kunde brytas över två rader med vissa systemtypsnitt; tasbih-widgeten blev långsammare ju högre räkningen steg; läswidgeten klippte sista raden i sin standardstorlek; en Koran-nedladdning kunde hänga sig i stället för att misslyckas.',
    },
  },
  {
    code: 261,
    version: '2.16.0',
    date: '2026-09-06',
    notes: {
      en: '• Downloading a reciter has moved onto the reciter list. Every voice now says what it holds on your device, and offers to fetch it or delete it — so "which do I have offline?" is one screen instead of forty-two.\n• The home-screen practice graph is rebuilt: bigger squares, edge to edge, and it reads down its columns like the Log screen does. Resizing the widget now adds or removes rows instead of shrinking the graph, from one row up.',
      ar: '• انتقل تنزيل القارئ إلى قائمة القرّاء. كل صوت يبيّن الآن ما هو محفوظ على جهازك ويعرض تنزيله أو حذفه — فسؤال "ما الذي لديّ دون إنترنت؟" صار شاشة واحدة بدل اثنتين وأربعين.\n• أُعيد بناء رسم المتابعة في الشاشة الرئيسية: مربعات أكبر، من حافة إلى حافة، ويُقرأ نزولًا في الأعمدة كما في السجل. تغيير الحجم يزيد الصفوف أو ينقصها بدل أن يصغّر الرسم، بدءًا من صف واحد.',
      sv: '• Nedladdningen av en recitatör har flyttat till recitatörslistan. Varje röst visar nu vad som finns på enheten och erbjuder att hämta eller radera den — så "vilka har jag offline?" är en skärm i stället för fyrtiotvå.\n• Praktikgrafen på hemskärmen är ombyggd: större rutor, kant till kant, och den läses nedåt i kolumner som i Loggen. Att ändra storlek lägger till eller tar bort rader i stället för att krympa grafen, från en rad och uppåt.',
    },
  },
  {
    code: 260,
    version: '2.15.1',
    date: '2026-09-05',
    notes: {
      en: '• The second-time alerts no longer fire for a prayer you have already logged. Recording ʿAṣr now takes its boundary alert and its "the time has ended" alert off the schedule — and where two prayers share one alert, the other prayer keeps its warning.\n• The Moroccan timetable is refreshed from the Ministry of Habous.',
      ar: '• لم تعد تنبيهات الأوقات الثانية تصل عن صلاة سجّلتها بالفعل. تسجيل العصر يرفع تنبيه حدّه وتنبيه انتهاء وقته من الجدول — وإذا اشتركت صلاتان في تنبيه واحد بقي تنبيه الأخرى.\n• حُدِّث جدول المغرب من وزارة الأوقاف.',
      sv: '• Aviseringarna för de andra tiderna går inte längre för en bön du redan har loggat. Att registrera ʿAṣr tar bort både gränsaviseringen och "tiden är slut"-aviseringen — och när två böner delar en avisering behåller den andra sin varning.\n• Den marockanska tidtabellen är uppdaterad från Habous-ministeriet.',
    },
  },
  {
    code: 259,
    version: '2.15.0',
    date: '2026-09-04',
    notes: {
      en: '• Tilāwah — put the Qur\'an on and listen. Pick a reciter, start anywhere, and it keeps going surah after surah with the screen off, offline once downloaded.\n• Morning and evening duas can now remind you in their own windows — after Fajr before sunrise, after ʿAṣr before sunset.\n• The Mālikī second times can be announced without adding rows to your card, and can say when a prayer becomes qaḍāʾ.\n• A 12-hour clock everywhere you read a time.\n• Widgets no longer cut off their last line.',
      ar: '• تِلاوة — شغّل القرآن واستمع. اختر قارئًا، وابدأ من حيث شئت، ويستمر سورةً بعد سورة والشاشة مطفأة، وبلا إنترنت بعد التنزيل.\n• أذكار الصباح والمساء صار لها تنبيه داخل وقتها — بعد الفجر قبل الشروق، وبعد العصر قبل الغروب. لا وقت تختاره: يتبع الشمس.\n• الأوقات الثانية المالكية يمكن التنبيه عليها دون إضافة صفوف إلى البطاقة، وتخبرك متى تصير الصلاة قضاءً.\n• نظام ١٢ ساعة في كل موضع تقرأ فيه وقتًا.\n• لم تعد أدوات الشاشة الرئيسية تقطع سطرها الأخير.',
      sv: '• Tilāwah — sätt på Koranen och lyssna. Välj en recitatör, börja var du vill, och den fortsätter sura efter sura med skärmen av, offline när den är nedladdad.\n• Morgonens och kvällens duaer påminner nu inom sina egna fönster — efter Fajr före soluppgången, efter ʿAṣr före solnedgången.\n• De maliktiska andra tiderna kan aviseras utan rader på kortet, och säger när en bön blir qaḍāʾ.\n• 12-timmarsklocka överallt där du läser en tid.\n• Widgetarna kapar inte längre sin sista rad.',
    },
  },
  {
    code: 257,
    version: '2.14.3',
    date: '2026-09-03',
    notes: {
      en: '• Twenty pages of the muṣḥaf drew some words in the system font instead of the page\'s own — rows of meaningless letter pairs. The page fonts are rebuilt, and Mihrab now checks the ones on your device and quietly replaces any that are wrong.\n• The bottoms of letters are no longer cut off at the line.\n• Turning the phone keeps the page you were on.\n• The page rail is rebuilt: it follows your finger smoothly, names the surah and juz under it, and slides up for finer control.',
      ar: '• عشرون صفحة من المصحف كانت تُظهر بعض الكلمات بخط النظام بدل خط الصفحة — أزواج حروف بلا معنى. أُعيد بناء خطوط الصفحات، وصار التطبيق يفحص ما على جهازك ويستبدل الخاطئ بهدوء.\n• لم تعد أسافل الحروف تُقطع عند السطر.\n• تدوير الهاتف يُبقيك على الصفحة نفسها.\n• أُعيد بناء شريط الصفحات: يتبع إصبعك بسلاسة، ويسمّي السورة والجزء تحته، واسحب لأعلى لتحكّم أدق — صفحة واحدة من ٦٠٤ بالضبط.',
      sv: '• Tjugo sidor i muṣḥafen ritade vissa ord med systemets typsnitt i stället för sidans eget — rader av meningslösa bokstavspar. Sidtypsnitten är ombyggda, och Mihrab kontrollerar nu dem du har och byter tyst ut de felaktiga.\n• Bokstävernas nederdelar kapas inte längre vid raden.\n• Att vrida telefonen behåller sidan du var på.\n• Sidreglaget är ombyggt: det följer fingret mjukt, namnger suran och juz under det, och dra uppåt för finare kontroll — en sida av 604, med avsikt.',
    },
  },
  {
    code: 256,
    version: '2.14.2',
    date: '2026-09-03',
    notes: {
      en: '• A tap on a word in the muṣḥaf opens its ayah: translation, tafsir, bookmark, recitation, khatmah position.\n• A sepia page, between paper and night.\n• The recited word lights up, and in landscape the page follows it down.\n• Reading starts the moment the download does.\n• The page reaches the bottom of the screen, and the Android navigation bar takes its colour.\n• Turning the phone shows one page, not two.\n• Word highlighting works on Android again.',
      ar: '• لمسة على كلمة في المصحف تفتح آيتها: الترجمة والتفسير والعلامة والتلاوة وموضع الختمة.\n• صفحة بلون السيبيا، بين الورق والليل.\n• الكلمة المتلوّة تُضاء، وفي الوضع الأفقي تتبعها الصفحة.\n• تبدأ القراءة منذ لحظة بدء التنزيل.\n• الصفحة تصل إلى أسفل الشاشة، وشريط تنقّل أندرويد يأخذ لونها.\n• تدوير الهاتف يُظهر صفحة واحدة لا صفحتين.\n• إبراز الكلمات يعمل على أندرويد من جديد.',
      sv: '• Ett tryck på ett ord i muṣḥafen öppnar dess vers: översättning, tafsir, bokmärke, recitation, khatmah-position.\n• En sepiasida, mellan papper och natt.\n• Det reciterade ordet lyser upp, och i liggande läge följer sidan med.\n• Läsningen börjar i samma stund som nedladdningen.\n• Sidan når skärmens nederkant, och Androids navigeringsfält tar dess färg.\n• Att vrida telefonen visar en sida, inte två.\n• Ordmarkeringen fungerar igen på Android.',
    },
  },
  {
    code: 255,
    version: '2.14.1',
    date: '2026-09-02',
    notes: {
      en: '• Ayah numbers sit inside their medallions again on the downloaded muṣḥafs. The first two pages drew an empty rosette with the number beside it.\n• Those two pages are set larger, so they fill the page the way the print does.\n• A khatmah can begin where you already are: give the page you are on, and the days cover what is left of the book.\n• The first third of the night, optional, after Isha — where Isha leaves its preferred window in the Mālikī reckoning.',
      ar: '• عادت أرقام الآيات إلى داخل مداراتها في المصاحف المنزَّلة؛ كانت الصفحتان الأوليان ترسمان دائرة فارغة والرقم بجانبها.\n• وصارت هاتان الصفحتان بخط أكبر يملأ الصفحة كما يفعل المطبوع.\n• ويمكن بدء الختمة من موضعك الحالي: تحدّد الصفحة التي أنت فيها فتوزَّع الأيام على ما بقي من المصحف.\n• وأُضيف الثلث الأول من الليل، اختياريًا، بعد العشاء: وعنده يخرج وقت العشاء المختار عند المالكية.',
      sv: '• Ayah-numren sitter inuti sina medaljonger igen i de nedladdade mushaferna. De två första sidorna ritade en tom rosett med siffran bredvid.\n• De två sidorna sätts större och fyller sidan så som trycket gör.\n• En khatma kan börja där du redan är: ange sidan du står på, så täcker dagarna det som är kvar av boken.\n• Nattens första tredjedel, valfri, efter Isha — där Isha lämnar sitt bästa tidsfönster enligt malikitisk räkning.',
    },
  },
  {
    code: 254,
    version: '2.14.0',
    date: '2026-09-02',
    notes: {
      en: '• Three more reading traditions: Warsh, Qālūn and Shuʿbah, set on the printed muṣḥaf\'s own fifteen lines. Tap the tradition\'s name at the top of a page to switch. Each is fetched from the publisher, not bundled.\n• The khatmah counts in pages now, of the muṣḥaf you are in, and its days are even — a thirtieth of the book is twenty pages, not eight one day and thirty-six the next.\n• The Qibla compass is back.\n• The prayer log can be reset: one prayer, a day, a month, a year, or the lot.',
      ar: '• ثلاث روايات إضافية: ورش وقالون وشعبة، مضبوطة على أسطر المصحف المطبوع الخمسة عشر لا على نص يُعاد سكبه. اضغط على اسم الرواية أعلى الصفحة للتبديل. كل واحدة تُنزَّل من الناشر ولا تأتي مع التطبيق.\n• صار عدّ الختمة بالصفحات، بصفحات المصحف الذي تقرأ فيه، وأيامها مقسّمة بالتساوي: جزء من ثلاثين عشرون صفحة، لا ثمانٍ يومًا وستٌّ وثلاثون في اليوم التالي.\n• عادت بوصلة القبلة في متناول اليد.\n• يمكن تصفير سجل الصلوات: صلاة واحدة أو يومًا أو شهرًا أو سنة أو السجل كله.',
      sv: '• Tre läsarter till: Warsh, Qālūn och Shuʿbah, satta på tryckets egna femton rader i stället för att flöda om. Tryck på läsartens namn högst upp på sidan för att byta. Var och en hämtas från utgivaren; ingen följer med appen.\n• Khatman räknas nu i sidor, i den mushaf du läser, och dagarna delas jämnt — en trettiondel av boken är tjugo sidor, inte åtta en dag och trettiosex nästa.\n• Qibla-kompassen går att nå igen.\n• Bönloggen kan nollställas: en bön, en dag, en månad, ett år eller alltihop.',
    },
  },
  {
    code: 253,
    version: '2.13.8',
    date: '2026-09-01',
    notes: {
      en: '• Widgets placed next to each other no longer run together. Each one now draws its own rounded card, inset inside its slot, instead of painting edge to edge — so two stacked widgets have a gap between them rather than a seam.',
      ar: '• لم تعد الأدوات الموضوعة بجوار بعضها تندمج معًا. صارت كل أداة ترسم بطاقتها المستديرة داخل مساحتها بدل أن تملأها حتى الحافة — فتظهر مسافة بين أداتين متجاورتين بدل خط التقاء.',
      sv: '• Widgetar som placeras intill varandra flyter inte längre ihop. Varje widget ritar nu sitt eget rundade kort, indraget i sin ruta, i stället för att fylla ut hela ytan — så två widgetar ovanför varandra får ett mellanrum i stället för en skarv.',
    },
  },
  {
    code: 252,
    version: '2.13.7',
    date: '2026-08-31',
    notes: {
      en: '• Prayer times were computed for the wrong date: a formatting slip meant every request to the default source asked for a day four years away. In Morocco it also shifted the whole day by an hour.\n• Morocco now uses the Ministry of Habous\'s own published times.\n• Several calculation methods used the wrong angles on your device.\n• The Quran reader turns to the page the recited verse is on.\n• Prayer widgets could go blank; their stored timeline was far too large.',
      ar: '• كانت أوقات الصلاة تُحسب لتاريخ خاطئ: خطأ في التنسيق جعل كل طلب إلى المصدر الافتراضي يطلب يومًا يبعد أربع سنوات. وفي المغرب أزاح ذلك اليوم كله ساعة كاملة.\n• المغرب يعتمد الآن المواقيت التي تنشرها وزارة الأوقاف نفسها.\n• عدة طرق حساب كانت تستخدم زوايا خاطئة على جهازك.\n• قارئ القرآن ينتقل إلى الصفحة التي طُبعت فيها الآية المتلوّة.\n• قد تُصبح أدوات الصلاة فارغة؛ كان الجدول الزمني المخزَّن كبيرًا جدًا.',
      sv: '• Bönetiderna beräknades för fel datum: ett formatfel gjorde att varje förfrågan till standardkällan bad om en dag fyra år bort. I Marocko förskjöts dessutom hela dygnet en timme.\n• Marocko använder nu de tider som ministeriet för Habous själv publicerar.\n• Flera beräkningsmetoder använde fel vinklar på din enhet.\n• Koranläsaren bläddrar till sidan där den upplästa versen står.\n• Bönewidgetar kunde bli tomma; den sparade tidslinjen var alldeles för stor.',
    },
  },
  {
    code: 251,
    version: '2.13.6',
    date: '2026-08-30',
    notes: {
      en: '• Logging a prayer from the Android widget now reaches the app straight away. Before, the tap was recorded on the widget but only reached your journal the next time you opened the app — so the widget and the app could disagree for days.',
      ar: '• تسجيل صلاة من أداة أندرويد يصل الآن إلى التطبيق فورًا. سابقًا كان الضغط يُسجَّل على الأداة لكنه لا يصل إلى سجلّك إلا عند فتح التطبيق في المرة التالية — فكانت الأداة والتطبيق قد يختلفان لأيام.',
      sv: '• Att logga en bön från Android-widgeten når nu appen direkt. Tidigare registrerades tryckningen på widgeten men nådde din dagbok först nästa gång du öppnade appen — så widgeten och appen kunde visa olika saker i dagar.',
    },
  },
  {
    code: 250,
    version: '2.13.5',
    date: '2026-08-29',
    notes: {
      en: '• Maintenance build. The fix in this version is for the iPhone, iPad and Mac widgets: logging a prayer from the widget now reaches the app straight away instead of waiting for the app to be reopened. Nothing changes on Android.',
      ar: '• إصدار صيانة. الإصلاح في هذه النسخة يخص أدوات iPhone وiPad وMac: تسجيل صلاة من الأداة يصل الآن إلى التطبيق فورًا بدل انتظار إعادة فتحه. لا شيء يتغيّر على أندرويد.',
      sv: '• Underhållsversion. Rättningen i den här versionen gäller widgetarna på iPhone, iPad och Mac: att logga en bön från widgeten når nu appen direkt i stället för att vänta på att appen öppnas igen. Ingenting ändras på Android.',
    },
  },
  {
    code: 249,
    version: '2.13.4',
    date: '2026-08-29',
    notes: {
      en: '• The widget picker now shows the card you actually get. Every preview was redrawn from the real thing: the log chip is the hollow ✓ the card draws, sunrise is named Sunrise, the one-row cards show their date line, and the 4×2 previews show the practice graph — because that is what a 4×2 draws on an ordinary phone.\n• On Mac, updating no longer removes your widgets.',
      ar: '• يعرض منتقي الأدوات الآن البطاقة التي تحصل عليها فعلًا. أُعيد رسم كل معاينة من البطاقة الحقيقية: علامة التسجيل هي ✓ المفرغة التي ترسمها البطاقة، والشروق يُسمّى الشروق، وبطاقات الصف الواحد تعرض سطر التاريخ، ومعاينات ٤×٢ تعرض رسم المواظبة — لأن هذا ما ترسمه ٤×٢ على هاتف عادي.\n• على الماك، لم يعد التحديث يزيل الأدوات المثبّتة.',
      sv: '• Widgetväljaren visar nu kortet du faktiskt får. Varje förhandsvisning är omritad efter det riktiga kortet: loggknappen är den ihåliga ✓ som kortet ritar, soluppgången heter Soluppgång, enradskorten visar sin datumrad, och 4×2-förhandsvisningarna visar övningsgrafen — för det är vad en 4×2 ritar på en vanlig telefon.\n• På Mac tar en uppdatering inte längre bort dina widgetar.',
    },
  },
  {
    code: 248,
    version: '2.13.3',
    date: '2026-08-29',
    notes: {
      en: '• Sunrise no longer plays the adhan. Muting and un-muting the next adhan from the Live Activity could hand the call to prayer to sunrise; it cannot any more. Sunrise and the two night times are times, not prayers.',
      ar: '• لم يعد الشروق يشغّل الأذان. كان كتم الأذان التالي ثم إلغاء كتمه من النشاط المباشر قد يمنح الأذان للشروق، ولم يعد ذلك ممكنًا. الشروق ووقتا الليل أوقات، لا صلوات.',
      sv: '• Soluppgången spelar inte längre adhan. Att tysta och åter slå på nästa adhan från live-aktiviteten kunde ge böneutropet till soluppgången; det kan den inte längre. Soluppgången och de två nattiderna är tider, inte böner.',
    },
  },
  {
    code: 247,
    version: '2.13.2',
    date: '2026-08-29',
    notes: {
      en: '• Widgets: a prayer can be logged the moment its adhan passes. It used to wait until you next opened the app.\n• The countdown no longer sits at zero before Fajr — the widget now wakes at the moment it runs out.\n• The tall Log and prayer-times widgets are placed two rows high instead of three. Stretch one taller for the practice graph.',
      ar: '• الأدوات: تصبح الصلاة قابلة للتسجيل فور دخول وقتها؛ كانت تنتظر حتى تفتح التطبيق.\n• لم يعد العد التنازلي يقف عند الصفر قبل الفجر — تستيقظ الأداة الآن في اللحظة التي ينتهي فيها.\n• أداتا السجل والأوقات الطويلتان تُوضعان بصفّين بدل ثلاثة. مدّها صفًا لإظهار الرسم البياني للالتزام.',
      sv: '• Widgetar: en bön går att logga så snart adhan har passerat. Tidigare väntade den tills du öppnade appen igen.\n• Nedräkningen står inte längre kvar på noll före fajr — widgeten vaknar nu i samma stund som den tar slut.\n• De höga widgetarna för logg och bönetider placeras två rader höga i stället för tre. Dra ut en så kommer aktivitetsgrafen.',
    },
  },
  {
    code: 246,
    version: '2.13.1',
    date: '2026-08-28',
    notes: {
      en: '• New: play the adhan as an alarm, so it is heard even on silent or vibrate (Android, off by default).\n• The Log widget updates when you log a prayer. It was the one widget nothing told.\n• On Mac, widgets and their previews no longer freeze at the version you upgraded from.\n• In the Quran the keyboard turns pages the way the book does: ←, A or H forward, →, D or L back.',
      ar: '• جديد: تشغيل الأذان كمنبّه فيُسمع حتى والهاتف صامت أو على الاهتزاز (أندرويد، مغلق افتراضيًا).\n• أداة السجل تتحدّث عند تسجيل صلاة؛ كانت الأداة الوحيدة التي لا يخبرها شيء.\n• على الماك لم تعد الأدوات ولا معايناتها تتجمّد عند الإصدار الذي رقّيت منه.\n• في المصحف يقلّب لوحة المفاتيح كما يُقلَّب الكتاب: ← أو A أو H للأمام، → أو D أو L للخلف.',
      sv: '• Nytt: spela adhan som ett alarm, så den hörs även vid ljudlöst eller vibration (Android, av som standard).\n• Loggwidgeten uppdateras när du loggar en bön. Den var den enda widgeten som ingenting sa till.\n• På Mac fastnar widgetar och förhandsvisningar inte längre på versionen du uppgraderade från.\n• I Koranen bläddrar tangentbordet åt samma håll som boken: ←, A eller H framåt, →, D eller L bakåt.',
    },
  },
  {
    code: 245,
    version: '2.13.0',
    date: '2026-08-27',
    notes: {
      en: '• The navigation bar moves out of the way while you read and comes back when you scroll up. Always there on Tasbih.\n• The back button now works on every tab: the reader goes to the Quran tab, a tab goes to Today, Today exits the app.\n• Widgets take the color you chose, never the wallpaper\'s — with a picker of their own when the app follows system colors.\n• Previous, Reset and Skip no longer sit against the navigation bar.\n• Mac and iPad: arrow keys, WASD and HJKL turn Quran pages.',
      ar: '• شريط التنقل يبتعد أثناء القراءة ويعود عند التمرير للأعلى. وهو ظاهر دائمًا في التسبيح.\n• زر الرجوع يعمل الآن في كل التبويبات: القارئ إلى تبويب القرآن، والتبويب إلى اليوم، ومن اليوم تخرج.\n• الأدوات تأخذ اللون الذي اخترته لا لون الخلفية، ولها منتقي ألوان خاص عندما يتبع التطبيق ألوان النظام.\n• أزرار السابق وإعادة التعيين والتخطي لم تعد ملاصقة لشريط التنقل.\n• ماك وآيباد: الأسهم وWASD وHJKL تقلّب صفحات المصحف.',
      sv: '• Navigeringsfältet går undan medan du läser och kommer tillbaka när du skrollar uppåt. Alltid kvar på Tasbih.\n• Bakåtknappen fungerar nu på alla flikar: läsaren går till Koran-fliken, en flik går till Idag, Idag lämnar appen.\n• Widgetar tar färgen du valt, aldrig bakgrundsbildens — med en egen färgväljare när appen följer systemfärgerna.\n• Föregående, Nollställ och Hoppa över ligger inte längre mot navigeringsfältet.\n• Mac och iPad: piltangenter, WASD och HJKL bläddrar i Koranen.',
    },
  },
  {
    code: 244,
    version: '2.12.0',
    date: '2026-08-27',
    notes: {
      en: '• Sync now runs whenever you change your log — including from a notification or a widget, with the app closed. It used to wait until you next opened the app.\n• The refresh button on a widget syncs before it redraws, instead of showing you the same thing again.\n• Removing a paired device now sticks: its file is deleted, it cannot re-add itself, and your other devices drop it too.\n• Sync setup says plainly that it needs a folder Nextcloud, OneDrive, Dropbox or similar keeps in step.',
      ar: '• تعمل المزامنة الآن عند أي تغيير في سجلك — حتى من إشعار أو أداة، والتطبيق مغلق. كانت تنتظر حتى تفتح التطبيق.\n• زر التحديث في الأداة يزامن قبل أن يعيد الرسم، بدل أن يعرض الشيء نفسه.\n• إزالة جهاز مقترن صارت نهائية: يُحذف ملفه، ولا يمكنه إعادة إضافة نفسه، وأجهزتك الأخرى تزيله أيضًا.\n• إعداد المزامنة يوضّح الآن أنه يحتاج مجلدًا يقوم Nextcloud أو OneDrive أو Dropbox أو ما شابه بمزامنته.',
      sv: '• Synk körs nu så fort du ändrar i loggen — även från en avisering eller widget, med appen stängd. Tidigare väntade den tills du öppnade appen.\n• Uppdateringsknappen på en widget synkar innan den ritar om.\n• Att ta bort en parad enhet håller nu: filen raderas, enheten kan inte lägga till sig själv igen, och dina andra enheter tar bort den också.\n• Synkinställningen säger tydligt att den behöver en mapp som Nextcloud, OneDrive eller liknande håller synkroniserad.',
    },
  },
  {
    code: 243,
    version: '2.11.1',
    date: '2026-08-27',
    notes: {
      en: '• Fixed: a sunnah prayer you un-logged came back. A device that had stopped syncing left its last file in the shared folder, and every round read it again and put the old count back — indefinitely. A snapshot already merged is now left alone.\n• Removing a paired device also removes its file from the shared folder.\n• Sync now shows how old your other device\'s record is, not when this device last read its file.',
      ar: '• إصلاح: صلاة سنة ألغيت تسجيلها كانت تعود. جهاز توقّف عن المزامنة ترك آخر ملف له في المجلد المشترك، وكل جولة كانت تقرأه من جديد وتعيد العدد القديم — بلا نهاية. النسخة التي سبق دمجها تُترك الآن كما هي.\n• إزالة جهاز مقترن تزيل أيضًا ملفه من المجلد المشترك.\n• شاشة المزامنة تعرض الآن عمر سجل جهازك الآخر بدل وقت آخر قراءة.',
      sv: '• Fixat: en sunnah-bön du avmarkerade kom tillbaka. En enhet som slutat synka lämnade kvar sin sista fil i den delade mappen, och varje runda läste den igen och satte tillbaka det gamla värdet — i all oändlighet. En ögonblicksbild som redan slagits samman lämnas nu i fred.\n• Att ta bort en parad enhet tar även bort dess fil ur den delade mappen.\n• Synk visar nu hur gammal den andra enhetens data är, inte när den senast lästes.',
    },
  },
  {
    code: 242,
    version: '2.11.0',
    date: '2026-08-26',
    notes: {
      en: '• The app uses noticeably less battery in the background: Android draws the countdown itself, timers stop when nobody is looking, the compass lets go of the sensor, and the widgets refresh once per unlock instead of nine times.\n• Fixed: the Log refused to un-log a sunnah prayer — and a paired device kept putting it back.\n• Fixed: a crash when Android restored the app from the background.\n• Sync now shows how old your other device\'s record is, and says so when nothing has arrived.',
      ar: '• يستهلك التطبيق طاقة أقل بوضوح في الخلفية: أندرويد يرسم العد التنازلي بنفسه، والمؤقتات تتوقف حين لا ينظر أحد، والبوصلة تحرّر المستشعر، والأدوات تُحدَّث مرة واحدة عند كل فتح بدل تسع مرات.\n• إصلاح: السجل كان يرفض إلغاء تسجيل صلاة سنة — وجهاز مقترن كان يعيدها.\n• إصلاح: تعطُّل عند استعادة أندرويد للتطبيق من الخلفية.\n• المزامنة تعرض الآن عمر سجل جهازك الآخر، وتنبّهك حين لا يصل شيء.',
      sv: '• Appen drar märkbart mindre batteri i bakgrunden: Android ritar nedräkningen själv, timers stannar när ingen tittar, kompassen släpper sensorn och widgetarna uppdateras en gång per upplåsning i stället för nio.\n• Fixat: loggen vägrade avmarkera en sunnah-bön — och en parad enhet lade tillbaka den.\n• Fixat: en krasch när Android återställde appen från bakgrunden.\n• Synk visar nu hur gammal den andra enhetens data är, och säger till när inget kommit fram.',
    },
  },
  {
    code: 241,
    version: '2.10.1',
    date: '2026-08-24',
    notes: {
      en: '• Fixed: choosing a Nextcloud folder — or any folder whose provider will not make a subfolder — failed with an error.\n• Fixed: a folder you already called Mihrab had another Mihrab made inside it, so sync wrote where your sync client was not looking.\n• A folder that really cannot be used now says so in words instead of quoting a Java exception.',
      ar: '• إصلاح: اختيار مجلد Nextcloud — أو أي مجلد لا يستطيع مزوّده إنشاء مجلد فرعي — كان يفشل برسالة خطأ.\n• إصلاح: مجلد سمّيته Mihrab كان يُنشأ بداخله مجلد Mihrab آخر، فتكتب المزامنة حيث لا ينظر تطبيق المزامنة لديك.\n• المجلد الذي لا يصلح فعلًا صار يقول ذلك بكلمات بدل عرض خطأ Java.',
      sv: '• Rättat: att välja en Nextcloud-mapp — eller någon mapp vars leverantör inte kan skapa undermappar — misslyckades med ett fel.\n• Rättat: en mapp du redan kallat Mihrab fick ännu en Mihrab inuti sig, så synkningen skrev dit din synkklient inte tittade.\n• En mapp som verkligen inte går att använda säger nu det med ord i stället för ett Java-fel.',
    },
  },
  {
    code: 240,
    version: '2.10.0',
    date: '2026-08-24',
    notes: {
      en: '• Sync your record between your own devices — no account, no server, encrypted.\n• Pair by scanning a code, and choose how often it syncs.\n• The Log Today widget gains a graph and a countdown at its tallest size.\n• Prayer times widget in three sizes.\n• Widgets speak the language you chose in the app.\n• Seconds on the countdown, aimed at any prayer.\n• The Quran download continues in the background.\n• Fixed: Manage downloads said nothing was downloaded.\n• Fixed: the Fajr countdown was missing.',
      ar: '• مزامنة سجلك بين أجهزتك — بلا حساب ولا خادم، ومشفّرة.\n• الاقتران بمسح رمز، مع اختيار عدد مرات المزامنة.\n• أداة «سجل اليوم» تعرض المخطط وعدًّا تنازليًا في أكبر حجم.\n• أداة المواقيت بثلاثة أحجام.\n• الأدوات تتحدث لغة التطبيق التي اخترتها.\n• ثوانٍ في العد التنازلي، موجَّه إلى أي صلاة.\n• تنزيل المصحف يستمر في الخلفية.\n• إصلاح: «إدارة التنزيلات» لم تعرض شيئًا.\n• إصلاح: غياب العد التنازلي للفجر في الأدوات.',
      sv: '• Synka ditt register mellan dina egna enheter — utan konto, utan server, krypterat.\n• Parkoppla med en kod, och välj hur ofta synkningen sker.\n• Widgeten Logga i dag får graf och nedräkning i största formatet.\n• Bönetidswidgeten i tre storlekar.\n• Widgetarna talar språket du valt i appen.\n• Sekunder i nedräkningen, riktad mot valfri bön.\n• Koranhämtningen fortsätter i bakgrunden.\n• Rättat: Hantera nedladdningar visade inget.\n• Rättat: nedräkningen till fajr saknades i widgetarna.',
    },
  },
  {
    code: 239,
    version: '2.9.1',
    date: '2026-08-21',
    notes: {
      en: '• Sunnah prayers can be logged beside each fard.\n• Any audio file on the phone can be used as the adhan.\n• Export and import now cover the full record, not only settings.\n• The best streak is shown next to the current one.\n• Widgets update while the app is closed.\n• The widget graph now matches the one in the app.\n• Fixed: the streak showed zero each morning.',
      ar: '• يمكن تسجيل السنن الرواتب بجانب كل فريضة.\n• يمكن استخدام أي ملف صوتي في الهاتف كأذان.\n• التصدير والاستيراد يشملان السجل كاملًا، لا الإعدادات وحدها.\n• أفضل تتابع يظهر بجانب الحالي.\n• الأدوات تتحدّث والتطبيق مغلق.\n• مخطط الأداة صار مطابقًا لمخطط التطبيق.\n• إصلاح: التتابع كان يظهر صفرًا كل صباح.',
      sv: '• Sunnahböner kan loggas bredvid varje fard.\n• Vilken ljudfil som helst på telefonen kan användas som adhan.\n• Export och import omfattar nu hela registret, inte bara inställningarna.\n• Bästa sviten visas bredvid den nuvarande.\n• Widgetarna uppdateras medan appen är stängd.\n• Grafen i widgeten stämmer nu med appens.\n• Rättat: sviten visade noll varje morgon.',
    },
  },
  {
    code: 238,
    version: '2.9.0',
    date: '2026-08-19',
    notes: {
      en: 'Sunnah prayers, your own adhan, and an app that reaches the edges of the screen.\n\n• Log the sunnah prayers beside each fard; the graph draws them around the day.\n• Your own adhan — pick any audio file on the phone.\n• Export and import your whole record, not just the settings.\n• Your best streak now sits beside the current one.\n• Fixed: the streak read zero every morning.\n• Fixed: the last row of the Settings pickers sat under the navigation bar.\n• 871 strings translated.',
      ar: 'السنن الرواتب، وأذانك الخاص، وتطبيق يصل إلى حواف الشاشة.\n\n• سجّل السنن الرواتب بجانب كل فريضة، ويرسمها المخطط حول اليوم.\n• أذانك الخاص — اختر أي ملف صوتي من الهاتف.\n• صدّر واستورد سجلك كاملًا، لا الإعدادات وحدها.\n• أفضل تتابع لك يظهر الآن بجانب الحالي.\n• إصلاح: التتابع كان يقرأ صفرًا كل صباح.\n• إصلاح: آخر صف في قوائم الإعدادات كان تحت شريط التنقل.\n• ترجمة 871 نصًا.',
      sv: 'Sunnahböner, din egen adhan, och en app som når skärmens kanter.\n\n• Logga sunnahbönerna bredvid varje fard; grafen ritar dem runt dagen.\n• Din egen adhan — välj vilken ljudfil som helst på telefonen.\n• Exportera och importera hela ditt register, inte bara inställningarna.\n• Din bästa svit står nu bredvid den nuvarande.\n• Rättat: sviten visade noll varje morgon.\n• Rättat: sista raden i inställningarnas listor låg under navigeringsfältet.\n• 871 texter översatta.',
    },
  },
  {
    code: 237,
    version: '2.8.10',
    date: '2026-08-14',
    notes: {
      en: 'Words were going missing from the mushaf. They are back.\n\n• Some lines of the Quran were losing their last word — roughly one line in eight, on nearly every page. The text and the fonts were always right; the renderer was asking phones for something they could quietly refuse. Fixed, and now checked on all 604 pages.\n• The graph scrolls the right way round in Arabic, Urdu, Persian and Hebrew.\n• Quran files left behind by an older version are cleared out.',
      ar: 'كانت بعض كلمات المصحف تختفي. عادت.\n\n• كان بعض السطور يفقد كلمته الأخيرة — نحو سطر من كل ثمانية، في معظم الصفحات. النص والخطوط سليمة دائمًا؛ الخلل كان في طريقة الرسم. أُصلح، ويُفحص الآن في صفحات المصحف كلها.\n• الرسم البياني صار يمرَّر في الاتجاه الصحيح في العربية والأردية والفارسية والعبرية.\n• حذف ملفات القرآن التي خلّفها تحديث سابق.',
      sv: 'Ord försvann ur mushaf. De är tillbaka.\n\n• Vissa rader i Koranen tappade sitt sista ord — ungefär var åttonde rad, på nästan varje sida. Texten och typsnitten var alltid rätt; felet låg i uppritningen. Åtgärdat, och kontrolleras nu på alla 604 sidor.\n• Grafen rullar åt rätt håll på arabiska, urdu, persiska och hebreiska.\n• Koranfiler som en äldre version lämnat kvar rensas bort.',
    },
  },
  {
    code: 236,
    version: '2.8.9',
    date: '2026-08-14',
    notes: {
      en: 'The Log, as you were already trying to use it.\n\n• The notification\'s "Log prayer" button now really records it — even with the app closed, on the day the alert was for.\n• Swipe the day panel to change day; the arrows still work.\n• Fill in earlier days, or the past three months. Both ask first and never touch a day you have logged.\n• A day with a missed prayer is marked on the graph.\n• The evening prompt stops asking about a finished day.\n• The graph scrolls on the first try, and on Today.',
      ar: 'السجل، كما كنت تستخدمه أصلاً.\n\n• زر «سجّل الصلاة» في الإشعار صار يسجّلها فعلاً — حتى والتطبيق مغلق، وعلى اليوم المقصود.\n• اسحب لوحة اليوم للتنقّل بين الأيام؛ والأسهم تعمل كما كانت.\n• املأ الأيام السابقة أو الأشهر الثلاثة الماضية. كلاهما يسأل أولًا ولا يمسّ يومًا سجّلته.\n• اليوم الذي فيه صلاة فائتة يُعلَّم في الرسم البياني.\n• تذكير المساء لا يسأل عن يوم أتممته.\n• الرسم البياني يستجيب للتمرير من أول محاولة.',
      sv: 'Loggen, så som du redan försökte använda den.\n\n• Knappen "Logga bön" i aviseringen registrerar nu bönen — även med appen stängd, på den dag aviseringen gällde.\n• Svep dagpanelen för att byta dag; pilarna fungerar än.\n• Fyll i tidigare dagar eller de senaste tre månaderna. Båda frågar först och rör aldrig en loggad dag.\n• Dagar med missad bön markeras i grafen.\n• Kvällspåminnelsen frågar inte om färdiga dagar.\n• Grafen går att skrolla direkt, även på startskärmen.',
    },
  },
  {
    code: 235,
    version: '2.8.8',
    date: '2026-08-07',
    notes: {
      en: 'Nothing changes on Android in this release.\n\nThe work went into the Mac app installed with Homebrew, which now has the prayer-times widget for Notification Centre — the same widget the iPhone has had. Android is untouched and is only here because the two platforms share a version number.',
      ar: 'لا يتغيّر شيء في أندرويد في هذا الإصدار.\n\nانصبّ العمل على تطبيق ماك المثبَّت عبر Homebrew، وصارت فيه أداة مواقيت الصلاة في مركز الإشعارات — الأداة نفسها الموجودة في الآيفون. أندرويد لم يُمَسّ، وهو هنا فقط لأن المنصّتين تتشاركان رقم الإصدار.',
      sv: 'Ingenting förändras på Android i den här versionen.\n\nArbetet har gått till Mac-appen som installeras med Homebrew, som nu har widgeten med bönetider i Notiscenter — samma widget som iPhone redan haft. Android är orört och finns med här bara för att plattformarna delar versionsnummer.',
    },
  },
  {
    code: 234,
    version: '2.8.7',
    date: '2026-08-03',
    notes: {
      en: 'The Log tells the truth about what you entered.\n\n• The graph is coloured by status, not by how many boxes you ticked. On time counts fully, late and make-up less, missed nothing — and a day recorded as missed is marked, not left blank.\n• Open any past day: the arrows by the date, or tap its square.\n• The graph reaches your first logged day and scrolls back.\n• A prayer whose time has not come cannot be logged, and "Mark all on time" respects that.\n• Optional: show the graph on the Today screen.',
      ar: 'السجل يعكس ما أدخلته فعلاً.\n\n• لون المربع يعتمد على الحالة لا على عدد الإدخالات: في الوقت يُحتسب كاملاً، والمتأخر والقضاء أقل، والفائتة لا شيء — واليوم الذي سجّلته فائتاً يظهر بعلامة ولا يُترك فارغاً.\n• افتح أي يوم سابق: بالسهمين بجانب التاريخ أو بالضغط على مربعه في الرسم.\n• يمتد الرسم إلى أول يوم سجّلته ويستمر إلى الوراء.\n• لا يمكن تسجيل صلاة لم يدخل وقتها، و"تسجيل الكل في الوقت" يلتزم بالقاعدة نفسها.\n• يتحدّث الرسم لحظة الضغط.\n• اختياري: إظهار الرسم في شاشة اليوم.',
      sv: 'Loggen visar det du faktiskt fyllt i.\n\n• Grafen färgas efter status, inte efter antal ifyllda rutor. I tid räknas fullt, sent och igen räknas mindre, missad räknas inte alls — en missad dag markeras, den lämnas inte tom.\n• Öppna vilken tidigare dag som helst: pilarna vid datumet, eller tryck på rutan.\n• Grafen når din första loggade dag och fortsätter bakåt.\n• En bön vars tid inte är inne kan inte loggas, och "Markera alla i tid" följer samma regel.\n• Valfritt: visa grafen på Idag-skärmen.',
    },
  },
  {
    code: 231,
    version: '2.8.3',
    date: '2026-07-31',
    notes: {
      en: 'The Quran\'s buttons work again after reading in fullscreen landscape. Leaving the reader used to leave the surah list, and the home screen\'s Quran button, looking normal and doing nothing.\n\nA surah now opens with an illuminated band, and the bismillah is set at the page\'s own size.\n\nThe mushaf asks before downloading, is five times faster, then never pauses for a page again. An older copy from a previous version is removed first.\n\nThe reader is lighter in and out of fullscreen.',
      ar: 'عادت أزرار القرآن للعمل بعد القراءة بملء الشاشة أفقيًّا. كان الخروج من المصحف يترك قائمة السور، وزر فتح القرآن في الشاشة الرئيسة، تبدو سليمة ولا تستجيب لأي لمسة.\n\nتبدأ السورة الآن بإطار مزخرف كما في المطبوع، والبسملة بحجم سطر الصفحة نفسه.\n\nيستأذنك المصحف قبل التنزيل، وصار أسرع بخمسة أضعاف، ثم لا يتوقف بعدها لجلب صفحة. وتُحذف أولًا نسخة قديمة خلّفها إصدار سابق.\n\nصار القارئ أخفّ عند الدخول والخروج من ملء الشاشة.',
      sv: 'Koranens knappar fungerar igen efter läsning i helskärm och liggande läge. Att lämna läsaren brukade lämna surahlistan, och Koran-knappen på startskärmen, till synes normala men helt döda för tryck.\n\nEn surah inleds nu med en ornerad ram som i trycket, och bismillah sätts i sidans egen storlek.\n\nMushaf frågar innan den laddas ner, går fem gånger snabbare och pausar sedan aldrig för en sida. En äldre kopia från en tidigare version tas bort först.\n\nLäsaren är lättare in och ut ur helskärm.',
    },
  },
  {
    code: 230,
    version: '2.8.2',
    date: '2026-07-31',
    notes: {
      en: 'Mushaf fixes.\n\nEvery line was losing its last word — the gap between words was drawn by a system typeface at a width the app never measured, so lines ran wider than their box. The gap now comes from a font the app ships, and lines justify to the measure as the print does.\n\nAyah 2:2 and the rub-el-hizb marks read in the printed order again.\n\nLeaving the Quran no longer leaves the app deaf to taps.\n\nThe page reaches all four screen edges and clears the camera cut-out.',
      ar: 'إصلاحات في المصحف.\n\nكان كل سطر يفقد كلمته الأخيرة، لأن المسافة بين الكلمات كانت تُرسم بخط من النظام بعرض لم يقِسه التطبيق، فتخرج السطور أعرض من مساحتها. صارت المسافة الآن من خط يرفقه التطبيق ويعرف مقاييسه، وتُضبط السطور على المقاس كما في المطبوع.\n\nعادت الآية ٢:٢ وعلامات ۞ إلى ترتيب المصحف المطبوع.\n\nلم يعد الخروج من القرآن يُفقد التطبيق استجابته للمس.\n\nتصل الصفحة إلى حواف الشاشة الأربع وتتجنّب فتحة الكاميرا.\n\nيتبع عنوان القارئ الصفحة التي تقرؤها.',
      sv: 'Rättningar i mushaf-läsaren.\n\nVarje rad tappade sitt sista ord — mellanrummet mellan orden ritades av ett systemtypsnitt med en bredd appen aldrig mätt, så raderna blev bredare än sin ruta. Mellanrummet kommer nu från ett typsnitt appen levererar, och raderna justeras mot måttet som i trycket.\n\nVers 2:2 och hizb-markeringarna står i tryckets ordning igen.\n\nAtt lämna Koranen gör inte längre appen okänslig för tryck.\n\nSidan når alla fyra skärmkanter.\n\nRubriken följer sidan du är på.',
    },
  },
  {
    code: 229,
    version: '2.8.1',
    date: '2026-07-31',
    notes: {
      en: '• Mushaf lines now run to a single, consistent width, so the page has the straight margin the print does instead of a ragged one. The fit is small enough that the letterforms look unchanged; a line that would have to stretch further is left as it is.\n• The opening pages are bigger. Pages 1 and 2 hold only seven or eight lines in the space a normal page gives fifteen, so they now use a wider block and larger text.',
      ar: '• أصبحت أسطر المصحف تمتد إلى عرض واحد ثابت، فصار هامش الصفحة مستقيمًا كما في المطبوع بدل أن يكون متعرجًا. المقدار المضبوط يسير بحيث تبدو الحروف كما هي، والسطر الذي يحتاج تمديدًا أكبر يُترك على حاله.\n• صفحتا الفاتحة أكبر. تحمل الصفحتان ١ و٢ سبعة أو ثمانية أسطر في مساحة تتسع في الصفحة العادية لخمسة عشر سطرًا، فصار عرض الكتلة أوسع والنص أكبر.',
      sv: '• Mushafens rader går nu ut till en och samma bredd, så sidan får den raka marginal som trycket har i stället för en ojämn. Justeringen är så liten att bokstäverna ser oförändrade ut; en rad som skulle behöva sträckas mer lämnas som den är.\n• De inledande sidorna är större. Sida 1 och 2 rymmer bara sju eller åtta rader på den plats en vanlig sida ger femton, så de använder nu ett bredare block och större text.',
    },
  },
  {
    code: 228,
    version: '2.8.0',
    date: '2026-07-31',
    notes: {
      en: '• The Quran is drawn as text now, using the official Madinah page fonts instead of page images. It stays sharp at any zoom, uses far less memory, and rotates instantly. The reader opens right away too — each page is fetched as you read instead of waiting on one large download. Page-for-page and line-for-line as the printed mushaf.\n• Phones and tablets each get a reader built for them: one page on a phone, facing pages on an iPad.\n• Turning pages in landscape no longer skips one.',
      ar: '• أصبح المصحف يُعرض نصًّا باستخدام خطوط صفحات المدينة الرسمية بدل صور الصفحات: وضوح تام عند أي تكبير، واستهلاك ذاكرة أقل بكثير، ودوران فوري. كما يفتح القارئ مباشرة دون انتظار تنزيل كبير، إذ تُجلب كل صفحة أثناء القراءة. التخطيط مطابق للمصحف المطبوع صفحةً بصفحة وسطرًا بسطر.\n• قارئ مخصص لكل جهاز: صفحة واحدة على الهاتف في الوضعين، وصفحتان متقابلتان على الآيباد.\n• لم يعد تقليب الصفحات في الوضع الأفقي يتخطى صفحة.',
      sv: '• Koranen ritas som text med Medinas officiella sidtypsnitt i stället för sidbilder: skarp vid all zoom, mindre minne och direkt rotation. Läsaren öppnas genast — varje sida hämtas medan du läser i stället för en stor nedladdning. Sida för sida och rad för rad som den tryckta mushafen.\n• Telefon och surfplatta får varsin läsare: en sida på telefonen, uppslag på iPad.\n• Bläddring i liggande läge hoppar inte över en sida.',
    },
  },
  {
    code: 227,
    version: '2.7.43',
    date: '2026-07-30',
    notes: {
      en: '• Rotating the mushaf on a phone is fast and stable again. Landscape reading used far more memory than it needed to, which made rotation slow and could crash the app on tighter devices. The page you read is just as large on screen — it simply costs a fraction of the memory now.',
      ar: '• أصبح تدوير المصحف على الهاتف سريعًا ومستقرًا. كانت القراءة الأفقية تستهلك ذاكرة أكبر بكثير من اللازم، ما جعل التدوير بطيئًا وقد يؤدي إلى إغلاق التطبيق على بعض الأجهزة. حجم الصفحة على الشاشة كما هو، لكن باستهلاك ذاكرة أقل بكثير.',
      sv: '• Att rotera mushafen på telefonen är snabbt och stabilt igen. Liggande läsning använde mycket mer minne än nödvändigt, vilket gjorde rotationen långsam och kunde krascha appen på svagare enheter. Sidan är lika stor på skärmen — den kostar bara en bråkdel av minnet nu.',
    },
  },
  {
    code: 226,
    version: '2.7.42',
    date: '2026-07-30',
    notes: {
      en: '• Removed two permissions the app never needed: storage read/write came in from a library\'s manifest, but Mihrab only writes to its own private app storage.\n• Rewrote the store listing to match the app today, including a clear note on which features are optional and online.\n• macOS: the menu bar now says "Mihrab".',
      ar: '• إزالة إذنين لم يكن التطبيق بحاجة إليهما: أذونات قراءة/كتابة التخزين جاءت من مكتبة خارجية، بينما يكتب مِحراب في مساحته الخاصة فقط.\n• إعادة كتابة وصف التطبيق ليطابق حالته الحالية، مع توضيح الميزات الاختيارية التي تتطلب الإنترنت.\n• macOS: شريط القوائم يعرض الآن "Mihrab".',
      sv: '• Tog bort två behörigheter appen aldrig behövde: läs/skriv till lagring kom från ett biblioteks manifest, men Mihrab skriver bara till sitt eget privata utrymme.\n• Skrev om butiksbeskrivningen så att den matchar appen i dag, med en tydlig notis om vilka funktioner som är valfria och kräver nätverk.\n• macOS: menyraden visar nu "Mihrab".',
    },
  },
  {
    code: 225,
    version: '2.7.41',
    date: '2026-07-29',
    notes: {
      en: '• Landscape reading on phones: one page zoomed to the full width and scrolled vertically, instead of a cramped (and sometimes blank) two-page spread. Tap for fullscreen, long-press an ayah, swipe to turn — all unchanged.\n• Fixed two-word Arabic surah names losing their second word in the Quran list (Aal-i-Imran showed only "آل").\n• Fixed the Settings button on macOS not always responding.',
      ar: '• القراءة الأفقية على الهواتف: صفحة واحدة مكبَّرة بعرض الشاشة مع تمرير رأسي، بدلًا من صفحتين متقابلتين ضيّقتين (وأحيانًا فارغة). النقر لملء الشاشة والضغط المطوّل على الآية والسحب لتقليب الصفحات تعمل كما هي.\n• إصلاح اختفاء الكلمة الثانية من أسماء السور العربية في القائمة (آل عمران كانت تظهر "آل" فقط).\n• إصلاح عدم استجابة زر الإعدادات دائمًا على macOS.',
      sv: '• Liggande läsning på telefoner: en sida zoomad till full bredd med vertikal skrollning, i stället för ett trångt (ibland tomt) uppslag med två sidor. Tryck för helskärm, håll in en vers och svep för att bläddra fungerar som förut.\n• Fixat att tvåordiga arabiska surahnamn tappade sitt andra ord i listan (Aal-i-Imran visade bara "آل").\n• Fixat att inställningsknappen på macOS inte alltid svarade.',
    },
  },
  {
    code: 224,
    version: '2.7.40',
    date: '2026-07-27',
    notes: {
      en: '• One choice for what\'s under each verse: pick translation or tafsir and the edition once — applies to the reader, verse of the day, and daily-ayah notification. New selector on the Quran page and in Settings.\n• Adhan alerts now cover 4 days, so they keep firing even if the app isn\'t opened daily; plus a battery-optimization fix-it row.\n• Fixed the tools grid collapsing to two narrow columns on some phones.',
      ar: '• اختيار واحد لما يظهر أسفل كل آية: اختر الترجمة أو التفسير والإصدار مرة واحدة — يُطبَّق على القارئ وآية اليوم وإشعار الآية اليومي. مُحدِّد جديد في صفحة القرآن وفي الإعدادات.\n• تنبيهات الأذان تغطي الآن 4 أيام فتستمر حتى لو لم يُفتح التطبيق يوميًا، مع صف لإصلاح تحسين البطارية.\n• إصلاح انهيار شبكة الأدوات إلى عمودين ضيّقين على بعض الهواتف.',
      sv: '• Ett val för det som visas under varje vers: välj översättning eller tafsir och utgåva en gång — gäller läsaren, dagens vers och den dagliga ayah-aviseringen. Ny väljare på Koran-sidan och i Inställningar.\n• Adhan-aviseringar täcker nu 4 dagar och fortsätter även om appen inte öppnas dagligen; plus en åtgärdsrad för batterioptimering.\n• Fixat att verktygsrutnätet föll ihop till två smala kolumner på vissa telefoner.',
    },
  },
  {
    code: 223,
    version: '2.7.39',
    date: '2026-07-16',
    notes: {
      en: '• Fixed overlapping cards/dots on the Home screen (all devices)\n• Tools grid back to 3 comfortable columns on phones\n• Smaller app: unused resources stripped from the Play build',
      ar: '• إصلاح تداخل البطاقات والنقاط في الشاشة الرئيسية (جميع الأجهزة)\n• شبكة الأدوات تعود إلى ٣ أعمدة مريحة على الهواتف\n• حجم أصغر للتطبيق',
      sv: '• Fix för överlappande kort/prickar på hemskärmen (alla enheter)\n• Verktygsrutnätet åter 3 bekväma kolumner på mobiler\n• Mindre appstorlek',
    },
  },
  {
    code: 222,
    version: '2.7.38',
    date: '2026-07-16',
    notes: {
      en: '• Adhan fires exactly on time — fixed a rare 1–2 min early alert with a duplicate\n• Big iPad/Mac layout polish: filled dashboard, dual-page Quran chrome, page-turn buttons\n• Quran index centers correctly on wide screens (RTL fix)',
      ar: '• الأذان في وقته تمامًا — إصلاح تنبيه مبكر بدقيقة أو دقيقتين مع إشعار مكرر\n• تحسينات كبيرة لتخطيط iPad وMac\n• فهرس القرآن يتوسّط الشاشات العريضة بشكل صحيح',
      sv: '• Adhan exakt i tid — fix för notis 1–2 min för tidigt med dubblett\n• Stor layoutputs för iPad/Mac\n• Koranindexet centreras korrekt på breda skärmar',
    },
  },
  {
    code: 221,
    version: '2.7.37',
    date: '2026-07-15',
    notes: {
      en: 'Snooze prayer alerts: pick 5/10/15/30 min or type any number right in the notification. New Live Activity action to hide the prayer countdown from the lock screen while keeping it in the shade. Fixed stale prayer notifications lingering past the next prayer, and the Sunrise alert no longer says "Prayer time". Your tafsir choice now sticks, with a new tafsir selector in Settings. The layout adapts to large screens (tablets, foldables) and reflows to one column when narrow.',
      ar: 'تأجيل تنبيهات الصلاة: اختر 5/10/15/30 دقيقة أو اكتب أي عدد مباشرة في الإشعار. إجراء جديد في النشاط المباشر لإخفاء العدّ التنازلي للصلاة عن شاشة القفل مع بقائه في لوحة الإشعارات. إصلاح بقاء إشعارات الصلاة القديمة بعد الصلاة التالية، ولم يعد إشعار الشروق يقول "وقت الصلاة". يتم الآن حفظ اختيارك للتفسير، مع مُحدِّد تفسير جديد في الإعدادات. تتكيّف الواجهة مع الشاشات الكبيرة وتعود إلى عمود واحد عند التضييق.',
      sv: 'Snooza böneaviseringar: välj 5/10/15/30 min eller skriv valfritt antal direkt i aviseringen. Ny åtgärd på Live-aktiviteten som döljer bönenedräkningen från låsskärmen medan den finns kvar i aviseringspanelen. Åtgärdat: gamla böneaviseringar låg kvar efter nästa bön, och Soluppgång-aviseringen säger inte längre "Bönetid". Ditt tafsir-val sparas nu, med en ny tafsir-väljare i Inställningar. Layouten anpassar sig till stora skärmar och återgår till en kolumn när det är smalt.',
    },
  },
  {
    code: 217,
    version: '2.7.36',
    date: '2026-07-09',
    notes: {
      en: 'Mihrab is now a full iPad app — and runs on Apple Silicon Macs. The layout adapts to the window: a two-column Home dashboard on wide screens, centred reading, and reflowing tools, Settings and month schedule; back to a single column when narrow. Dual-page Quran (mushaf) in landscape. New tafsir selector in Settings that stays in sync with the Quran page — and your tafsir choice now sticks instead of resetting. Smoother day carousel on large screens.',
      ar: 'أصبح مِحراب الآن تطبيق iPad كاملاً — ويعمل على أجهزة Mac بمعالج Apple Silicon. تتكيّف الواجهة مع حجم النافذة: لوحة رئيسية بعمودين على الشاشات العريضة، وقراءة متمركزة، وأدوات وإعدادات وجدول شهري يعيد ترتيب نفسه لملء المساحة؛ وتعود إلى عمود واحد عند التضييق. عرض صفحتين من المصحف في الوضع الأفقي. مُحدِّد تفسير جديد في الإعدادات متزامن مع صفحة القرآن — واختيارك للتفسير يُحفظ الآن بدل أن يعود إلى الافتراضي. كاروسيل الأيام أكثر سلاسة على الشاشات الكبيرة.',
      sv: 'Mihrab är nu en fullvärdig iPad-app – och körs på Apple Silicon-Mac. Layouten anpassar sig efter fönstret: en tvåkolumners startvy på breda skärmar, centrerad läsning och verktyg, Inställningar och månadsschema som fyller ytan; tillbaka till en kolumn när det är smalt. Uppslag med två koransidor i liggande läge. Ny tafsir-väljare i Inställningar som synkas med koransidan – och ditt tafsir-val sparas nu i stället för att återställas. Mjukare dagskarusell på stora skärmar.',
    },
  },
  {
    code: 216,
    version: '2.7.35',
    date: '2026-07-08',
    notes: {
      en: 'A lot has landed since the last update:\n- A full Quran reader — interactive mushaf, 21 reciters with audio and word‑by‑word highlight, memorization tools, khatmah plans, tafsir and search\n- Ayah of the day and daily reminders\n- Swedish prayer times now work fully offline and more reliably\n- More reliable automatic location (Wi‑Fi + GPS, works indoors) that switches correctly when you travel\n- Steadier adhan alarms; your data survives reinstalls on Android\n- Many fixes and polish',
      ar: 'الكثير من الجديد منذ آخر تحديث:\n- مصحف تفاعلي كامل — ٢١ قارئًا بالصوت مع تظليل كلمة بكلمة، وأدوات حفظ، وخطط ختمة، وتفسير وبحث\n- آية اليوم وتذكيرات يومية\n- أوقات الصلاة في السويد تعمل الآن دون اتصال وبموثوقية أعلى\n- موقع تلقائي أكثر موثوقية (Wi‑Fi وGPS، يعمل داخل المباني) ويتبدّل بشكل صحيح عند السفر\n- أذان أكثر ثباتًا؛ وبياناتك تبقى بعد إعادة التثبيت على أندرويد\n- إصلاحات وتحسينات كثيرة',
      sv: 'Mycket nytt sedan förra uppdateringen:\n- En komplett Koranläsare — interaktiv mushaf, 21 recitatörer med ljud och ord‑för‑ord‑markering, memoreringsverktyg, khatmah‑planer, tafsir och sökning\n- Dagens vers och dagliga påminnelser\n- Svenska bönetider fungerar nu helt offline och mer pålitligt\n- Mer pålitlig automatisk plats (Wi‑Fi + GPS, fungerar inomhus) som byter korrekt när du reser\n- Stabilare adhan‑larm; dina data överlever ominstallation på Android\n- Många fixar och förbättringar',
    },
  },
  {
    code: 215,
    version: '2.7.34',
    date: '2026-07-08',
    notes: {
      en: 'More reliable automatic location — now uses Wi‑Fi/network alongside GPS, so it won\'t get stuck when GPS is unavailable indoors, and it works with Android\'s "Approximate location". Prayer times switch correctly as you travel between countries: the Swedish and global sources swap across borders, and returning to a recent city reuses its saved times. The location chip now shows your city in automatic mode too. Faster first‑time Quran page download.',
      ar: 'موقع تلقائي أكثر موثوقية — يستخدم الآن شبكة Wi‑Fi إلى جانب GPS، فلا يتوقف عندما يتعذّر تحديد الموقع عبر GPS داخل المباني، ويعمل مع "الموقع التقريبي" في أندرويد. تتبدّل أوقات الصلاة بشكل صحيح عند السفر بين البلدان (يتبدّل المصدر السويدي والمصدر العالمي عند الحدود)، وعند العودة إلى مدينة سابقة تُستخدم الأوقات المحفوظة. تعرض شارة الموقع اسم مدينتك في الوضع التلقائي أيضًا. تنزيل أسرع لصفحات المصحف لأول مرة.',
      sv: 'Mer pålitlig automatisk plats — använder nu Wi‑Fi/nätverk utöver GPS, så den fastnar inte när GPS saknas inomhus, och fungerar med Androids "Ungefärlig plats". Bönetider byts korrekt när du reser mellan länder (den svenska och den globala källan växlar vid gränser), och när du återvänder till en ort återanvänds sparade tider. Platsknappen visar nu din stad även i automatiskt läge. Snabbare nedladdning av Koranens sidor första gången.',
    },
  },
  {
    code: 214,
    version: '2.7.33',
    date: '2026-07-07',
    notes: {
      en: 'More reliable prayer times for Sweden: they now come from a regularly refreshed set of Islamiska Förbundet times, work offline, and fall back gracefully if the network is unavailable — so your times always show.',
      ar: 'أوقات صلاة أكثر موثوقية للسويد: تُؤخذ الآن من مجموعة أوقات محدَّثة بانتظام من الرابطة الإسلامية (Islamiska Förbundet)، وتعمل دون اتصال بالإنترنت، وتتحوّل تلقائيًا إلى بديل عند انقطاع الشبكة — لتظهر أوقاتك دائمًا.',
      sv: 'Mer tillförlitliga bönetider för Sverige: de hämtas nu från en regelbundet uppdaterad uppsättning tider från Islamiska Förbundet, fungerar offline och faller tillbaka smidigt om nätverket saknas — så dina tider visas alltid.',
    },
  },
  {
    code: 213,
    version: '2.7.32',
    date: '2026-07-06',
    notes: {
      en: 'More reliable prayer times for Sweden: they now come from a regularly refreshed set of Islamiska Förbundet times, work offline, and fall back gracefully if the network is unavailable — so your times always show.',
      ar: 'أوقات صلاة أكثر موثوقية للسويد: تُؤخذ الآن من مجموعة أوقات محدَّثة بانتظام من الرابطة الإسلامية (Islamiska Förbundet)، وتعمل دون اتصال بالإنترنت، وتتحوّل تلقائيًا إلى بديل عند انقطاع الشبكة — لتظهر أوقاتك دائمًا.',
      sv: 'Mer tillförlitliga bönetider för Sverige: de hämtas nu från en regelbundet uppdaterad uppsättning tider från Islamiska Förbundet, fungerar offline och faller tillbaka smidigt om nätverket saknas — så dina tider visas alltid.',
    },
  },
  {
    code: 212,
    version: '2.7.31',
    date: '2026-07-06',
    notes: {
      en: '• Khatmah: start a plan of any custom length, not just 30/60/90 days\n• Verse of the day: choose translation or real tafsir below the ayah',
      ar: '• الختمة: ابدأ خطة بأي مدة مخصصة، وليس فقط ٣٠/٦٠/٩٠ يومًا\n• آية اليوم: اختر بين الترجمة أو التفسير الحقيقي أسفل الآية',
      sv: '• Khatmah: starta en plan med valfri längd, inte bara 30/60/90 dagar\n• Dagens vers: välj översättning eller riktig tafsir under versen',
    },
  },
  {
    code: 211,
    version: '2.7.30',
    date: '2026-07-06',
    notes: {
      en: '• Sweden prayer-time source now falls back to AlAdhan instantly when unreachable\n• Home shows when times were last updated and how many days are stored offline\n• Wide Quran shortcut on Home; month view moved next to "Today" and into the grid\n• Hero accent line now matches dynamic colors\n• Quran pages 1–2 render sharp',
      ar: '• مصدر مواقيت السويد يتحول فورًا إلى AlAdhan عند تعذر الوصول إليه\n• الصفحة الرئيسية تعرض آخر تحديث للمواقيت وعدد الأيام المخزنة دون اتصال\n• اختصار عريض للمصحف في الرئيسية؛ عرض الشهر انتقل بجوار «اليوم» وإلى الشبكة\n• خط التمييز أعلى البطاقة يطابق الآن الألوان الديناميكية\n• الصفحتان ١ و٢ من المصحف تظهران بوضوح تام',
      sv: '• Svenska bönetidskällan växlar direkt till AlAdhan när den inte kan nås\n• Hemskärmen visar när tiderna senast hämtades och hur många dagar som lagras offline\n• Bred Koran-genväg på hemskärmen; månadsvyn flyttad intill "Idag" och till rutnätet\n• Accentlinjen matchar nu dynamiska färger\n• Koransidorna 1–2 renderas skarpt',
    },
  },
  {
    code: 210,
    version: '2.7.29',
    date: '2026-07-06',
    notes: {
      en: 'Mushaf reader:\n\n• Full pages now use the screen better — the text gently fills the free vertical space\n• Fullscreen keeps the surah name, night/light toggle and page number\n• Smoother fullscreen enter/exit\n• Pages 1–2 keep their decorative plates untouched',
      ar: 'قارئ المصحف:\n\n• الصفحات الكاملة تستغل الشاشة بشكل أفضل — يمتد النص برفق في المساحة الرأسية الفارغة\n• وضع ملء الشاشة يحتفظ باسم السورة وزر الوضع الليلي ورقم الصفحة\n• دخول وخروج أكثر سلاسة من ملء الشاشة\n• الصفحتان ١ و٢ تحتفظان بإطاريهما الزخرفيين دون تغيير',
      sv: 'Mushaf-läsaren:\n\n• Fulla sidor utnyttjar skärmen bättre — texten fyller varsamt det lediga vertikala utrymmet\n• Helskärm behåller surans namn, natt/ljus-knappen och sidnumret\n• Mjukare övergång in och ut ur helskärm\n• Sidorna 1–2 behåller sina dekorativa ramar oförändrade',
    },
  },
  {
    code: 209,
    version: '2.7.28',
    date: '2026-07-05',
    notes: {
      en: 'Reader upgrades:\n\n• Real tafsir (Ibn Kathir & more) in the ayah panel, cached offline\n• Sharper, larger mushaf pages; tap toggles fullscreen, long-press selects an ayah\n• All recitation controls unified in one panel\n• Khatmah: continue button, reset options, pin your exact position\n• New: khatmah daily reminder; Manage downloads screen\n• More reliable adhan timing and smoother long recitation sessions',
      ar: 'تحسينات القارئ:\n\n• تفسير حقيقي (ابن كثير وغيره) في لوحة الآية، مع حفظ للقراءة دون اتصال\n• صفحات مصحف أوضح وأكبر؛ نقرة لملء الشاشة وضغطة مطولة لاختيار الآية\n• جميع أدوات التلاوة في لوحة واحدة\n• الختمة: زر متابعة، وخيارات إعادة الضبط، وتثبيت موضعك بدقة\n• جديد: تذكير يومي للختمة؛ وشاشة إدارة التنزيلات\n• توقيت أذان أكثر موثوقية وجلسات تلاوة أطول دون انقطاع',
      sv: 'Läsaruppgraderingar:\n\n• Riktig tafsir (Ibn Kathir m.fl.) i aya-panelen, cachad offline\n• Skarpare och större mushaf-sidor; tryck för helskärm, långtryck väljer aya\n• Alla recitationskontroller samlade i en panel\n• Khatmah: fortsätt-knapp, återställningsval, fäst din exakta position\n• Nytt: daglig khatmah-påminnelse; skärm för nedladdningar\n• Pålitligare adhan-tider och jämnare långa recitationssessioner',
    },
  },
  {
    code: 208,
    version: '2.7.27',
    date: '2026-07-05',
    notes: {
      en: 'Quran reader upgrades:\n\n• 16 new reciters (21 total) with a searchable reciter picker\n• The mushaf page is now the default reading view, with a clearer night/light toggle\n• Sleeker recitation player\n• Bookmarks can now be deleted from the Bookmarks tab\n• New: daily "Ayah of the day" notification at a time you choose, with translation',
      ar: 'تحسينات قارئ القرآن:\n\n• 16 قارئًا جديدًا (21 إجمالًا) مع قائمة اختيار قابلة للبحث\n• صفحة المصحف أصبحت العرض الافتراضي، مع زر أوضح للوضع الليلي/الفاتح\n• مشغّل تلاوة أكثر أناقة\n• يمكن الآن حذف الإشارات المرجعية من تبويب الإشارات\n• جديد: إشعار «آية اليوم» يوميًا في الوقت الذي تختاره، مع الترجمة',
      sv: 'Uppgraderad Koranläsare:\n\n• 16 nya recitatörer (21 totalt) med sökbar recitatörsväljare\n• Mushaf-sidan är nu standardvyn, med tydligare natt/ljus-växling\n• Snyggare recitationsspelare\n• Bokmärken kan nu tas bort från bokmärkesfliken\n• Nytt: daglig "Dagens aya"-avisering vid valfri tid, med översättning',
    },
  },
  {
    code: 207,
    version: '2.7.26',
    date: '2026-07-05',
    notes: {
      en: 'All-new Quran reader:\n\n• Interactive Madinah mushaf — tap any ayah to translate, bookmark, star or share\n• Recitation with 5 reciters, background playback and offline downloads\n• Memorization tools: repeat, ranges, hide-and-reveal\n• Khatmah plans with daily progress\n\nAlso new: a quick feature tour, richer themes with real Amiri typography, two new accent colors, a third Live Activity design, and your data now survives uninstall/reinstall via Android backup.',
      ar: 'قارئ قرآن جديد كليًا:\n\n• مصحف المدينة تفاعلي — انقر أي آية للترجمة أو الإشارة المرجعية أو التمييز أو المشاركة\n• تلاوة بخمسة قرّاء مع تشغيل في الخلفية وتنزيلات دون اتصال\n• أدوات الحفظ: التكرار، والنطاقات، والإخفاء والكشف\n• خطط ختمة مع تقدّم يومي\n\nوأيضًا: جولة تعريفية سريعة، وسمات أجمل بخط أميري الأصيل، ولونان مميزان جديدان، وتصميم ثالث للنشاط المباشر، وبياناتك تبقى الآن بعد إلغاء التثبيت وإعادته عبر النسخ الاحتياطي في أندرويد.',
      sv: 'Helt ny Koranläsare:\n\n• Interaktiv Madinah-mushaf — tryck på en aya för översättning, bokmärke, stjärna eller delning\n• Recitation med 5 recitatörer, bakgrundsuppspelning och offline-nedladdningar\n• Memoreringsverktyg: repetition, intervall, dölj-och-visa\n• Khatmah-planer med dagligt framsteg\n\nÄven nytt: en snabb funktionsguide, finare teman med äkta Amiri-typografi, två nya accentfärger, en tredje Live Activity-design, och din data överlever nu avinstallation/ominstallation via Androids säkerhetskopiering.',
    },
  },
  {
    code: 206,
    version: '2.7.25',
    date: '2026-06-27',
    notes: {
      en: 'Welcome to Mihrab — a calm, privacy-first companion for the five daily prayers.\n\n• Accurate prayer times that work offline\n• Adhan and pre-prayer reminders\n• Home-screen widgets and a live countdown to the next prayer\n• Qibla compass and a full monthly calendar\n• Quran reader, duas, tasbih, prayer journal and fasting tracker\n• Hijri dates, 13 languages, light and dark themes\n\nNo ads, no tracking, ever. Open source.',
      ar: 'مرحبًا بك في مِحراب — رفيقٌ هادئ يحترم خصوصيتك للصلوات الخمس.\n\n• أوقات صلاة دقيقة تعمل دون اتصال بالإنترنت\n• تنبيهات الأذان وتذكيرات ما قبل الصلاة\n• أدوات على الشاشة الرئيسية وعدّاد تنازلي مباشر للصلاة القادمة\n• بوصلة القبلة وتقويم شهري كامل\n• مصحف، وأدعية، ومسبحة، ومفكرة صلاة، ومتتبّع صيام\n• التاريخ الهجري، و١٣ لغة، وسمات فاتحة وداكنة\n\nبلا إعلانات، وبلا تتبّع، أبدًا. مفتوح المصدر.',
      sv: 'Välkommen till Mihrab — en lugn och integritetsvänlig följeslagare för de fem dagliga bönerna.\n\n• Exakta bönetider som fungerar offline\n• Adhan- och förbönspåminnelser\n• Widgetar på hemskärmen och en live-nedräkning till nästa bön\n• Qibla-kompass och en fullständig månadskalender\n• Koranläsare, duas, tasbih, böndagbok och fasteräknare\n• Hijri-datum, 13 språk, ljust och mörkt tema\n\nInga annonser, ingen spårning, någonsin. Öppen källkod.',
    },
  },
];
