// GENERATED by scripts/gen-widget-contract.js from scripts/contract/widget-contract.js — do not edit.
//
// The v2 widget payload and the queues back to the app. Every reader here
// is lenient: a required field that is missing or mistyped makes its
// object unreadable; anything else falls back to its default or nil; a
// list drops the elements it cannot read. Formatting and time maths live
// in WallClock.swift, never here.

import Foundation

enum WidgetContract {
  static let version = 2

  enum Eid: String, Codable, Hashable {
    case fitr
    case adha
  }

  enum PrayerStatus: String, Codable, Hashable {
    case onTime = "on-time"
    case late
    case missed
    case qadha
  }

  enum ReaderMode: String, Codable, Hashable {
    case mushaf
    case translation
  }

  enum TasbihAction: String, Codable, Hashable {
    case inc
    case reset
    case next
  }

  /// Everything the home-screen widgets draw. Written by the app, read on
  /// every widget redraw.
  struct Payload: Codable, Hashable {
    /// Always 2 for this shape.
    var schemaVersion: Int
    /// Epoch ms when the app wrote it.
    var builtAt: Int
    /// The app's language tag (`sv`, `ar`). Native chrome resolves its own
    /// strings against it, so one widget never speaks two languages.
    var language: String
    /// How to write a time.
    var clock: Clock
    /// Short place label.
    var locationName: String
    /// Today first, then the days after it. Readers pick the entry whose
    /// `dateKey` is the device's local date, so a widget keeps rolling
    /// forward without the app.
    var days: [Day]
    /// Jumuʿah, Ramadan, Eid accents.
    var seasonal: Seasonal?
    /// Today's five with their journal status — the Log Today widget.
    var today: Today?
    /// Streak and the practice grid. Absent means "do not draw", never zero.
    var practice: Practice?
    /// Where the reader left off, and what the khatmah asks of today.
    var reading: Reading?
    /// Today's Hijri date and the month after it.
    var hijri: Hijri?
    /// The dhikr counter, for the Tasbih widget.
    var tasbih: Tasbih?

    init(
      schemaVersion: Int,
      builtAt: Int = 0,
      language: String = "",
      clock: Clock = Clock(),
      locationName: String = "",
      days: [Day],
      seasonal: Seasonal? = nil,
      today: Today? = nil,
      practice: Practice? = nil,
      reading: Reading? = nil,
      hijri: Hijri? = nil,
      tasbih: Tasbih? = nil
    ) {
      self.schemaVersion = schemaVersion
      self.builtAt = builtAt
      self.language = language
      self.clock = clock
      self.locationName = locationName
      self.days = days
      self.seasonal = seasonal
      self.today = today
      self.practice = practice
      self.reading = reading
      self.hijri = hijri
      self.tasbih = tasbih
    }

    enum CodingKeys: String, CodingKey {
      case schemaVersion
      case builtAt
      case language
      case clock
      case locationName
      case days
      case seasonal
      case today
      case practice
      case reading
      case hijri
      case tasbih
    }

    init(from decoder: Decoder) throws {
      let c = try decoder.container(keyedBy: CodingKeys.self)
      schemaVersion = try c.wcRequire(c.wcInt(.schemaVersion).flatMap(wcInt32), .schemaVersion)
      builtAt = c.wcInt(.builtAt) ?? 0
      language = c.wcValue(String.self, .language) ?? ""
      clock = c.wcValue(Clock.self, .clock) ?? Clock()
      locationName = c.wcValue(String.self, .locationName) ?? ""
      days = try c.wcRequire(c.wcList(Day.self, .days), .days)
      seasonal = c.wcValue(Seasonal.self, .seasonal)
      today = c.wcValue(Today.self, .today)
      practice = c.wcValue(Practice.self, .practice)
      reading = c.wcValue(Reading.self, .reading)
      hijri = c.wcValue(Hijri.self, .hijri)
      tasbih = c.wcValue(Tasbih.self, .tasbih)
    }
  }

  /// The user's clock, resolved by the app (Settings → Appearance, else the
  /// device). Digits are always Latin; only the day-period marker is
  /// localised, exactly as src/utils/clockFormat.ts writes it.
  struct Clock: Codable, Hashable {
    /// 12-hour clock.
    var hour12: Bool
    /// Morning marker in the app language.
    var am: String
    /// Afternoon marker in the app language.
    var pm: String
    /// Marker before the digits (下午5:31).
    var periodFirst: Bool

    init(
      hour12: Bool = false,
      am: String = "AM",
      pm: String = "PM",
      periodFirst: Bool = false
    ) {
      self.hour12 = hour12
      self.am = am
      self.pm = pm
      self.periodFirst = periodFirst
    }

    enum CodingKeys: String, CodingKey {
      case hour12
      case am
      case pm
      case periodFirst
    }

    init(from decoder: Decoder) throws {
      let c = try decoder.container(keyedBy: CodingKeys.self)
      hour12 = c.wcValue(Bool.self, .hour12) ?? false
      am = c.wcValue(String.self, .am) ?? "AM"
      pm = c.wcValue(String.self, .pm) ?? "PM"
      periodFirst = c.wcValue(Bool.self, .periodFirst) ?? false
    }
  }

  /// One local calendar day of prayer times.
  struct Day: Codable, Hashable {
    /// Local YYYY-MM-DD.
    var dateKey: String
    /// The device's UTC offset at local noon of this date when the app built
    /// it. A reader whose own offset for the date differs is looking at times
    /// computed under rules that no longer apply (#56).
    var utcOffsetMinutes: Int?
    /// Short day label ("Wed, Apr 9").
    var label: String
    /// The five ṣalāh, Fajr to ʿIshāʾ.
    var prayers: [Row]
    /// Absent when the user turned Sunrise off.
    var sunrise: Row?
    /// The night marks the user turned on, each on the calendar date it
    /// falls.
    var extras: [Row]

    init(
      dateKey: String,
      utcOffsetMinutes: Int? = nil,
      label: String = "",
      prayers: [Row],
      sunrise: Row? = nil,
      extras: [Row] = []
    ) {
      self.dateKey = dateKey
      self.utcOffsetMinutes = utcOffsetMinutes
      self.label = label
      self.prayers = prayers
      self.sunrise = sunrise
      self.extras = extras
    }

    enum CodingKeys: String, CodingKey {
      case dateKey
      case utcOffsetMinutes
      case label
      case prayers
      case sunrise
      case extras
    }

    init(from decoder: Decoder) throws {
      let c = try decoder.container(keyedBy: CodingKeys.self)
      dateKey = try c.wcRequire(c.wcValue(String.self, .dateKey), .dateKey)
      utcOffsetMinutes = c.wcInt(.utcOffsetMinutes).flatMap(wcInt32)
      label = c.wcValue(String.self, .label) ?? ""
      prayers = try c.wcRequire(c.wcList(Row.self, .prayers), .prayers)
      sunrise = c.wcValue(Row.self, .sunrise)
      extras = c.wcList(Row.self, .extras) ?? []
    }
  }

  /// One time on one day.
  struct Row: Codable, Hashable {
    /// `Fajr`, `Sunrise`, `Midnight`, … — never localised.
    var key: String
    /// Full localised name.
    var name: String
    /// Short label for narrow layouts.
    var abbr: String
    /// Minutes after local midnight of the day, 0–1439. Null when the time
    /// does not occur at this latitude; draw a dash.
    var minutes: Int?

    init(
      key: String,
      name: String = "",
      abbr: String = "",
      minutes: Int? = nil
    ) {
      self.key = key
      self.name = name
      self.abbr = abbr
      self.minutes = minutes
    }

    enum CodingKeys: String, CodingKey {
      case key
      case name
      case abbr
      case minutes
    }

    init(from decoder: Decoder) throws {
      let c = try decoder.container(keyedBy: CodingKeys.self)
      key = try c.wcRequire(c.wcValue(String.self, .key), .key)
      name = c.wcValue(String.self, .name) ?? ""
      abbr = c.wcValue(String.self, .abbr) ?? ""
      minutes = c.wcInt(.minutes).flatMap(wcInt32)
    }
  }

  /// Seasonal accents.
  struct Seasonal: Codable, Hashable {
    /// Friday before Maghrib.
    var jumuah: Bool
    /// Inside Ramadan.
    var ramadan: Bool
    /// Eid day, or null.
    var eid: Eid?

    init(
      jumuah: Bool = false,
      ramadan: Bool = false,
      eid: Eid? = nil
    ) {
      self.jumuah = jumuah
      self.ramadan = ramadan
      self.eid = eid
    }

    enum CodingKeys: String, CodingKey {
      case jumuah
      case ramadan
      case eid
    }

    init(from decoder: Decoder) throws {
      let c = try decoder.container(keyedBy: CodingKeys.self)
      jumuah = c.wcValue(Bool.self, .jumuah) ?? false
      ramadan = c.wcValue(Bool.self, .ramadan) ?? false
      eid = c.wcValue(String.self, .eid).flatMap(Eid.init(rawValue:))
    }
  }

  /// Today's five as the Log Today widget needs them.
  struct Today: Codable, Hashable {
    /// Local YYYY-MM-DD. A widget that slept through midnight must not draw
    /// yesterday's ticks as today's.
    var dateKey: String
    var logged: Int
    var loggable: Int
    /// Missed today and not yet made up.
    var owed: Int
    var prayers: [TodayPrayer]

    init(
      dateKey: String,
      logged: Int = 0,
      loggable: Int = 0,
      owed: Int = 0,
      prayers: [TodayPrayer] = []
    ) {
      self.dateKey = dateKey
      self.logged = logged
      self.loggable = loggable
      self.owed = owed
      self.prayers = prayers
    }

    enum CodingKeys: String, CodingKey {
      case dateKey
      case logged
      case loggable
      case owed
      case prayers
    }

    init(from decoder: Decoder) throws {
      let c = try decoder.container(keyedBy: CodingKeys.self)
      dateKey = try c.wcRequire(c.wcValue(String.self, .dateKey), .dateKey)
      logged = c.wcInt(.logged).flatMap(wcInt32) ?? 0
      loggable = c.wcInt(.loggable).flatMap(wcInt32) ?? 0
      owed = c.wcInt(.owed).flatMap(wcInt32) ?? 0
      prayers = c.wcList(TodayPrayer.self, .prayers) ?? []
    }
  }

  /// One prayer on the Log Today widget.
  struct TodayPrayer: Codable, Hashable {
    /// Journal prayer key.
    var key: String
    /// Localised name.
    var name: String
    /// Its time today, as `Row.minutes`.
    var minutes: Int?
    /// Journal status; null when nothing is recorded.
    var status: PrayerStatus?
    /// Its time has arrived; only a due prayer takes a tap.
    var due: Bool

    init(
      key: String,
      name: String = "",
      minutes: Int? = nil,
      status: PrayerStatus? = nil,
      due: Bool = false
    ) {
      self.key = key
      self.name = name
      self.minutes = minutes
      self.status = status
      self.due = due
    }

    enum CodingKeys: String, CodingKey {
      case key
      case name
      case minutes
      case status
      case due
    }

    init(from decoder: Decoder) throws {
      let c = try decoder.container(keyedBy: CodingKeys.self)
      key = try c.wcRequire(c.wcValue(String.self, .key), .key)
      name = c.wcValue(String.self, .name) ?? ""
      minutes = c.wcInt(.minutes).flatMap(wcInt32)
      status = c.wcValue(String.self, .status).flatMap(PrayerStatus.init(rawValue:))
      due = c.wcValue(Bool.self, .due) ?? false
    }
  }

  /// Practice history.
  struct Practice: Codable, Hashable {
    var streak: Int
    var bestStreak: Int
    /// Of the five, how many are logged today.
    var loggedToday: Int
    /// Missed and not yet made up, all time.
    var owed: Int
    /// Sunnah kept this month as a fraction; null before there is a
    /// denominator.
    var sunnahRate: Double?
    var fastsThisMonth: Int
    /// Oldest first, ending today; empty days omitted.
    var days: [PracticeDay]
    /// First day with a prayer entry, YYYY-MM-DD. Before it an empty square
    /// means "not started yet", after it "not filled in".
    var since: String?

    init(
      streak: Int = 0,
      bestStreak: Int = 0,
      loggedToday: Int = 0,
      owed: Int = 0,
      sunnahRate: Double? = nil,
      fastsThisMonth: Int = 0,
      days: [PracticeDay] = [],
      since: String? = nil
    ) {
      self.streak = streak
      self.bestStreak = bestStreak
      self.loggedToday = loggedToday
      self.owed = owed
      self.sunnahRate = sunnahRate
      self.fastsThisMonth = fastsThisMonth
      self.days = days
      self.since = since
    }

    enum CodingKeys: String, CodingKey {
      case streak
      case bestStreak
      case loggedToday
      case owed
      case sunnahRate
      case fastsThisMonth
      case days
      case since
    }

    init(from decoder: Decoder) throws {
      let c = try decoder.container(keyedBy: CodingKeys.self)
      streak = c.wcInt(.streak).flatMap(wcInt32) ?? 0
      bestStreak = c.wcInt(.bestStreak).flatMap(wcInt32) ?? 0
      loggedToday = c.wcInt(.loggedToday).flatMap(wcInt32) ?? 0
      owed = c.wcInt(.owed).flatMap(wcInt32) ?? 0
      sunnahRate = c.wcDouble(.sunnahRate)
      fastsThisMonth = c.wcInt(.fastsThisMonth).flatMap(wcInt32) ?? 0
      days = c.wcList(PracticeDay.self, .days) ?? []
      since = c.wcValue(String.self, .since)
    }
  }

  /// One day's marks on the practice grid. Short keys: up to 210 of these
  /// ride in every payload.
  struct PracticeDay: Codable, Hashable {
    /// Local YYYY-MM-DD.
    var d: String
    /// Weighted score ×100 — on-time 100, late 70, qadha 45 — summed over the
    /// five, capped at 500.
    var kw: Int
    /// How many of the five carry any entry.
    var l: Int
    /// A prayer recorded missed and not made up.
    var m: Bool
    /// A completed fast.
    var f: Bool
    /// Sunnah units kept.
    var s: Int

    init(
      d: String,
      kw: Int = 0,
      l: Int = 0,
      m: Bool = false,
      f: Bool = false,
      s: Int = 0
    ) {
      self.d = d
      self.kw = kw
      self.l = l
      self.m = m
      self.f = f
      self.s = s
    }

    enum CodingKeys: String, CodingKey {
      case d
      case kw
      case l
      case m
      case f
      case s
    }

    init(from decoder: Decoder) throws {
      let c = try decoder.container(keyedBy: CodingKeys.self)
      d = try c.wcRequire(c.wcValue(String.self, .d), .d)
      kw = c.wcInt(.kw).flatMap(wcInt32) ?? 0
      l = c.wcInt(.l).flatMap(wcInt32) ?? 0
      m = c.wcValue(Bool.self, .m) ?? false
      f = c.wcValue(Bool.self, .f) ?? false
      s = c.wcInt(.s).flatMap(wcInt32) ?? 0
    }
  }

  /// The Continue Reading widget.
  struct Reading: Codable, Hashable {
    var surah: Int
    /// Localised surah name.
    var surahName: String
    var ayah: Int
    var page: Int
    var juz: Int
    var pagesRead: Int
    var totalPages: Int
    var bookmarks: Int
    /// Epoch ms of the last page turn.
    var lastReadAt: Int?
    /// Which reader a tap opens — decided by the app, which knows whether the
    /// muṣḥaf is on disk.
    var mode: ReaderMode
    var khatmah: Khatmah?
    /// False when the Qurʾān has never been opened.
    var started: Bool
    /// The muṣḥaf page images are on disk.
    var downloaded: Bool

    init(
      surah: Int = 1,
      surahName: String = "",
      ayah: Int = 1,
      page: Int = 1,
      juz: Int = 1,
      pagesRead: Int = 0,
      totalPages: Int = 604,
      bookmarks: Int = 0,
      lastReadAt: Int? = nil,
      mode: ReaderMode = .translation,
      khatmah: Khatmah? = nil,
      started: Bool = false,
      downloaded: Bool = false
    ) {
      self.surah = surah
      self.surahName = surahName
      self.ayah = ayah
      self.page = page
      self.juz = juz
      self.pagesRead = pagesRead
      self.totalPages = totalPages
      self.bookmarks = bookmarks
      self.lastReadAt = lastReadAt
      self.mode = mode
      self.khatmah = khatmah
      self.started = started
      self.downloaded = downloaded
    }

    enum CodingKeys: String, CodingKey {
      case surah
      case surahName
      case ayah
      case page
      case juz
      case pagesRead
      case totalPages
      case bookmarks
      case lastReadAt
      case mode
      case khatmah
      case started
      case downloaded
    }

    init(from decoder: Decoder) throws {
      let c = try decoder.container(keyedBy: CodingKeys.self)
      surah = c.wcInt(.surah).flatMap(wcInt32) ?? 1
      surahName = c.wcValue(String.self, .surahName) ?? ""
      ayah = c.wcInt(.ayah).flatMap(wcInt32) ?? 1
      page = c.wcInt(.page).flatMap(wcInt32) ?? 1
      juz = c.wcInt(.juz).flatMap(wcInt32) ?? 1
      pagesRead = c.wcInt(.pagesRead).flatMap(wcInt32) ?? 0
      totalPages = c.wcInt(.totalPages).flatMap(wcInt32) ?? 604
      bookmarks = c.wcInt(.bookmarks).flatMap(wcInt32) ?? 0
      lastReadAt = c.wcInt(.lastReadAt)
      mode = c.wcValue(String.self, .mode).flatMap(ReaderMode.init(rawValue:)) ?? .translation
      khatmah = c.wcValue(Khatmah.self, .khatmah)
      started = c.wcValue(Bool.self, .started) ?? false
      downloaded = c.wcValue(Bool.self, .downloaded) ?? false
    }
  }

  /// Today's share of the khatmah plan.
  struct Khatmah: Codable, Hashable {
    /// 1-based day of the plan.
    var day: Int
    var targetDays: Int
    var pagesToday: Int
    var doneToday: Int
    var behindBy: Int
    var daysLeft: Int
    /// Pages left unread behind the reader.
    var skipped: Int

    init(
      day: Int = 1,
      targetDays: Int = 0,
      pagesToday: Int = 0,
      doneToday: Int = 0,
      behindBy: Int = 0,
      daysLeft: Int = 0,
      skipped: Int = 0
    ) {
      self.day = day
      self.targetDays = targetDays
      self.pagesToday = pagesToday
      self.doneToday = doneToday
      self.behindBy = behindBy
      self.daysLeft = daysLeft
      self.skipped = skipped
    }

    enum CodingKeys: String, CodingKey {
      case day
      case targetDays
      case pagesToday
      case doneToday
      case behindBy
      case daysLeft
      case skipped
    }

    init(from decoder: Decoder) throws {
      let c = try decoder.container(keyedBy: CodingKeys.self)
      day = c.wcInt(.day).flatMap(wcInt32) ?? 1
      targetDays = c.wcInt(.targetDays).flatMap(wcInt32) ?? 0
      pagesToday = c.wcInt(.pagesToday).flatMap(wcInt32) ?? 0
      doneToday = c.wcInt(.doneToday).flatMap(wcInt32) ?? 0
      behindBy = c.wcInt(.behindBy).flatMap(wcInt32) ?? 0
      daysLeft = c.wcInt(.daysLeft).flatMap(wcInt32) ?? 0
      skipped = c.wcInt(.skipped).flatMap(wcInt32) ?? 0
    }
  }

  /// Today's Hijri date.
  struct Hijri: Codable, Hashable {
    var day: Int
    var month: Int
    var year: Int
    var monthName: String
    /// The whole date, localised.
    var label: String
    var nextMonthName: String
    var nextMonthInDays: Int

    init(
      day: Int,
      month: Int,
      year: Int,
      monthName: String = "",
      label: String = "",
      nextMonthName: String = "",
      nextMonthInDays: Int = 0
    ) {
      self.day = day
      self.month = month
      self.year = year
      self.monthName = monthName
      self.label = label
      self.nextMonthName = nextMonthName
      self.nextMonthInDays = nextMonthInDays
    }

    enum CodingKeys: String, CodingKey {
      case day
      case month
      case year
      case monthName
      case label
      case nextMonthName
      case nextMonthInDays
    }

    init(from decoder: Decoder) throws {
      let c = try decoder.container(keyedBy: CodingKeys.self)
      day = try c.wcRequire(c.wcInt(.day).flatMap(wcInt32), .day)
      month = try c.wcRequire(c.wcInt(.month).flatMap(wcInt32), .month)
      year = try c.wcRequire(c.wcInt(.year).flatMap(wcInt32), .year)
      monthName = c.wcValue(String.self, .monthName) ?? ""
      label = c.wcValue(String.self, .label) ?? ""
      nextMonthName = c.wcValue(String.self, .nextMonthName) ?? ""
      nextMonthInDays = c.wcInt(.nextMonthInDays).flatMap(wcInt32) ?? 0
    }
  }

  /// The dhikr counter.
  struct Tasbih: Codable, Hashable {
    var presetId: String
    /// Localised transliteration.
    var label: String
    var arabic: String
    var count: Int
    /// 0 means open counting.
    var target: Int
    var unbounded: Bool
    /// Position in the preset cycle.
    var index: Int
    /// Cycle length.
    var total: Int
    /// Every preset's count, in order.
    var counts: [Int]
    /// Every preset's label — the widget steps the cycle in its own process.
    var labels: [String]
    var targets: [Int]
    var unboundedFlags: [Bool]
    /// Beads counted today, across presets.
    var todayTotal: Int
    var todayRounds: Int

    init(
      presetId: String = "",
      label: String = "",
      arabic: String = "",
      count: Int = 0,
      target: Int = 0,
      unbounded: Bool = false,
      index: Int = 0,
      total: Int = 0,
      counts: [Int] = [],
      labels: [String] = [],
      targets: [Int] = [],
      unboundedFlags: [Bool] = [],
      todayTotal: Int = 0,
      todayRounds: Int = 0
    ) {
      self.presetId = presetId
      self.label = label
      self.arabic = arabic
      self.count = count
      self.target = target
      self.unbounded = unbounded
      self.index = index
      self.total = total
      self.counts = counts
      self.labels = labels
      self.targets = targets
      self.unboundedFlags = unboundedFlags
      self.todayTotal = todayTotal
      self.todayRounds = todayRounds
    }

    enum CodingKeys: String, CodingKey {
      case presetId
      case label
      case arabic
      case count
      case target
      case unbounded
      case index
      case total
      case counts
      case labels
      case targets
      case unboundedFlags
      case todayTotal
      case todayRounds
    }

    init(from decoder: Decoder) throws {
      let c = try decoder.container(keyedBy: CodingKeys.self)
      presetId = c.wcValue(String.self, .presetId) ?? ""
      label = c.wcValue(String.self, .label) ?? ""
      arabic = c.wcValue(String.self, .arabic) ?? ""
      count = c.wcInt(.count).flatMap(wcInt32) ?? 0
      target = c.wcInt(.target).flatMap(wcInt32) ?? 0
      unbounded = c.wcValue(Bool.self, .unbounded) ?? false
      index = c.wcInt(.index).flatMap(wcInt32) ?? 0
      total = c.wcInt(.total).flatMap(wcInt32) ?? 0
      counts = c.wcList(WCInt.self, .counts)?.compactMap { wcInt32($0.value) } ?? []
      labels = c.wcList(String.self, .labels) ?? []
      targets = c.wcList(WCInt.self, .targets)?.compactMap { wcInt32($0.value) } ?? []
      unboundedFlags = c.wcList(Bool.self, .unboundedFlags) ?? []
      todayTotal = c.wcInt(.todayTotal).flatMap(wcInt32) ?? 0
      todayRounds = c.wcInt(.todayRounds).flatMap(wcInt32) ?? 0
    }
  }

  /// One Log Today tap, queued by the widget until the app drains it. Same
  /// wire shape as v1.
  struct LogQueueEntry: Codable, Hashable {
    /// Local YYYY-MM-DD the tap was for.
    var d: String
    /// Journal prayer key.
    var p: String
    /// Epoch ms of the tap.
    var t: Int

    init(
      d: String,
      p: String,
      t: Int
    ) {
      self.d = d
      self.p = p
      self.t = t
    }

    enum CodingKeys: String, CodingKey {
      case d
      case p
      case t
    }

    init(from decoder: Decoder) throws {
      let c = try decoder.container(keyedBy: CodingKeys.self)
      d = try c.wcRequire(c.wcValue(String.self, .d), .d)
      p = try c.wcRequire(c.wcValue(String.self, .p), .p)
      t = try c.wcRequire(c.wcInt(.t), .t)
    }
  }

  /// One Tasbih widget action. Same wire shape as v1.
  struct TasbihQueueEntry: Codable, Hashable {
    /// Action.
    var a: TasbihAction
    /// Epoch ms.
    var t: Int
    /// Run length for coalesced taps; absent means one.
    var n: Int?

    init(
      a: TasbihAction,
      t: Int,
      n: Int? = nil
    ) {
      self.a = a
      self.t = t
      self.n = n
    }

    enum CodingKeys: String, CodingKey {
      case a
      case t
      case n
    }

    init(from decoder: Decoder) throws {
      let c = try decoder.container(keyedBy: CodingKeys.self)
      a = try c.wcRequire(c.wcValue(String.self, .a).flatMap(TasbihAction.init(rawValue:)), .a)
      t = try c.wcRequire(c.wcInt(.t), .t)
      n = c.wcInt(.n).flatMap(wcInt32)
    }
  }

}

// MARK: - Lenient reading

/// Decodes from any JSON value and keeps nothing: what a lossy list reads
/// to step past an element it could not use.
private struct WCSkip: Decodable {
  init(from decoder: Decoder) throws {}
}

/// A whole number, accepting a JSON number written with a fraction of zero
/// (Swift's own encoder writes a Double epoch as 1759000000000.0).
struct WCInt: Decodable, Hashable {
  let value: Int
  init(from decoder: Decoder) throws {
    let c = try decoder.singleValueContainer()
    if let i = try? c.decode(Int.self) {
      value = i
    } else {
      let d = try c.decode(Double.self)
      guard d.isFinite, d == d.rounded(), abs(d) < 9.0e15 else {
        throw DecodingError.dataCorruptedError(in: c, debugDescription: "not a whole number")
      }
      value = Int(d)
    }
  }
}

/// An `int` field is 32-bit on every platform — Kotlin reads it as `Int` —
/// so a value outside that range is unreadable here too, not silently wider.
private func wcInt32(_ v: Int) -> Int? {
  (Int(Int32.min)...Int(Int32.max)).contains(v) ? v : nil
}

struct WCDouble: Decodable, Hashable {
  let value: Double
  init(from decoder: Decoder) throws {
    value = try decoder.singleValueContainer().decode(Double.self)
  }
}

extension KeyedDecodingContainer {
  fileprivate func wcValue<T: Decodable>(_ type: T.Type, _ key: Key) -> T? {
    (try? decodeIfPresent(type, forKey: key)) ?? nil
  }

  fileprivate func wcInt(_ key: Key) -> Int? {
    wcValue(WCInt.self, key)?.value
  }

  fileprivate func wcDouble(_ key: Key) -> Double? {
    wcValue(Double.self, key)
  }

  /// Every element that reads; the rest are skipped, not fatal.
  fileprivate func wcList<T: Decodable>(_ type: T.Type, _ key: Key) -> [T]? {
    guard (try? decodeNil(forKey: key)) == false,
          var items = try? nestedUnkeyedContainer(forKey: key)
    else { return nil }
    var out: [T] = []
    while !items.isAtEnd {
      if let v = try? items.decode(T.self) {
        out.append(v)
      } else if (try? items.decode(WCSkip.self)) == nil {
        break
      }
    }
    return out
  }

  fileprivate func wcRequire<T>(_ value: T?, _ key: Key) throws -> T {
    guard let value else {
      throw DecodingError.keyNotFound(
        key, .init(codingPath: codingPath, debugDescription: "required by the widget contract"))
    }
    return value
  }
}
