/**
 * The Hijri calendars a user can pick (Settings → Prayer times → Hijri
 * calendar): the arithmetic default, and Indonesia's two — the government
 * and NU (MABIMS) and Muhammadiyah (KHGT). See `src/hijri/calendar.ts`.
 *
 * The Indonesian tables are generated by tools/hijri-calendars/build.ts.
 * These dates are the ones each body announced; the tables must agree with
 * every one of them.
 */
import { gregorianToHijri, tabularGregorianToHijri } from '../src/hijri/convert';
import data from '../src/hijri/data/monthStarts.json';
import {
  activeHijriCalendar,
  expand,
  fromTable,
  coerceHijriAdjust,
  coerceHijriCalendarId,
  hijriCalendarVersion,
  setHijriCalendar,
  subscribeHijriCalendar,
} from '../src/hijri/calendar';

const at = (iso: string) => {
  const [y, m, d] = iso.split('-').map(Number);
  return new Date(y, m - 1, d, 12);
};

afterEach(() => setHijriCalendar('tabular', 0));

/**
 * First day of a month by the government: announced in the sidang isbat,
 * or implied by a national holiday in its own calendar (1 Muharram; Maulid
 * on 12 Rabiulawal; Isra Mi'raj on 27 Rajab). [hijri year, month, gregorian].
 */
const GOVERNMENT: [number, number, string][] = [
  [1445, 1, '2023-07-19'],
  [1445, 3, '2023-09-17'],
  [1445, 7, '2024-01-13'],
  [1446, 1, '2024-07-07'],
  [1446, 3, '2024-09-05'],
  [1446, 7, '2025-01-01'],
  [1447, 3, '2025-08-25'],
  [1447, 7, '2025-12-21'],
  [1448, 1, '2026-06-16'],
  [1448, 3, '2026-08-14'],
  [1444, 9, '2023-03-23'],
  [1444, 10, '2023-04-22'],
  [1444, 12, '2023-06-20'],
  [1445, 9, '2024-03-12'],
  [1445, 10, '2024-04-10'],
  [1445, 12, '2024-06-08'],
  [1446, 9, '2025-03-01'],
  [1446, 10, '2025-03-31'],
  [1446, 12, '2025-05-28'],
  [1447, 1, '2025-06-27'],
  [1447, 9, '2026-02-19'],
  [1447, 10, '2026-03-21'],
  [1447, 12, '2026-05-18'],
];

/** Muhammadiyah's own published calendar (khgt.muhammadiyah.or.id). */
const MUHAMMADIYAH: [number, number, string][] = [
  [1447, 1, '2025-06-26'],
  [1448, 2, '2026-07-15'],
  [1448, 4, '2026-09-12'],
  [1448, 5, '2026-10-12'],
  [1448, 6, '2026-11-10'],
  [1448, 8, '2027-01-09'],
  [1448, 11, '2027-04-08'],
  [1492, 1, '2069-02-22'],
  [1492, 11, '2069-12-15'],
  [1447, 9, '2026-02-18'],
  [1447, 10, '2026-03-20'],
  [1447, 12, '2026-05-18'],
  [1448, 1, '2026-06-16'],
  [1448, 3, '2026-08-14'],
  [1448, 7, '2026-12-10'],
  [1448, 9, '2027-02-08'],
  [1448, 10, '2027-03-09'],
  [1448, 12, '2027-05-07'],
];

const dayBefore = (iso: string) => {
  const d = at(iso);
  d.setDate(d.getDate() - 1);
  return d;
};

describe.each([
  ['mabims', GOVERNMENT],
  ['khgt', MUHAMMADIYAH],
] as const)('%s', (id, announced) => {
  beforeEach(() => setHijriCalendar(id, 0));

  it.each(announced)('%i-%i begins on %s', (year, month, iso) => {
    expect(gregorianToHijri(at(iso))).toEqual({ year, month, day: 1 });
    // …and the day before is the last of the month before, not the 1st —
    // except before the table's first month, where the arithmetic
    // calendar answers (Muhammadiyah adopted KHGT from 1 Muharram 1447).
    if (!(id === 'khgt' && year === 1447 && month === 1)) {
      expect(gregorianToHijri(dayBefore(iso)).day).toBeGreaterThanOrEqual(29);
    }
  });

  it('has only 29- and 30-day months, numbered in order, to 1500 AH', () => {
    let prev = gregorianToHijri(at('2026-01-01'));
    const d = at('2026-01-02');
    let monthLength = 0;
    for (let i = 0; i < 365 * 50; i++) {
      const h = gregorianToHijri(d);
      if (h.day === 1) {
        if (monthLength) expect([29, 30]).toContain(monthLength);
        const wantMonth = prev.month === 12 ? 1 : prev.month + 1;
        expect(h.month).toBe(wantMonth);
        monthLength = 1;
      } else {
        expect(h.day).toBe(prev.day + 1);
        monthLength = h.day;
      }
      prev = h;
      d.setDate(d.getDate() + 1);
    }
  });
});

describe('the default calendar', () => {
  it('is the arithmetic one, unchanged', () => {
    expect(activeHijriCalendar()).toEqual({ id: 'tabular', adjustDays: 0 });
    expect(gregorianToHijri(at('2026-02-18'))).toEqual(tabularGregorianToHijri(at('2026-02-18')));
    expect(gregorianToHijri(at('2026-02-18'))).toEqual({ year: 1447, month: 9, day: 1 });
  });

  it('counts on from a table at both edges, without repeating or skipping a day', () => {
    for (const id of ['mabims', 'khgt'] as const) {
      setHijriCalendar(id, 0);
      // Across the start of each table (2022 / 2025) and its end (2077–78).
      for (const [from, days] of [['2021-06-01', 1000], ['2077-06-01', 900]] as const) {
        const d = at(from);
        let prev = gregorianToHijri(d);
        for (let i = 0; i < days; i++) {
          d.setDate(d.getDate() + 1);
          const h = gregorianToHijri(d);
          if (h.day === 1) {
            expect([29, 30]).toContain(prev.day);
            expect(h.month).toBe(prev.month === 12 ? 1 : prev.month + 1);
          } else {
            expect(h).toEqual({ ...prev, day: prev.day + 1 });
          }
          prev = h;
        }
      }
    }
  });
});

describe('the adjustment', () => {
  it('moves the date by whole days, in whichever calendar', () => {
    setHijriCalendar('mabims', 1);
    // Government 1 Ramadan 1447 is 19 Feb; one day later shows it on the 18th.
    expect(gregorianToHijri(at('2026-02-18'))).toEqual({ year: 1447, month: 9, day: 1 });
    setHijriCalendar('tabular', -1);
    expect(gregorianToHijri(at('2026-02-19'))).toEqual({ year: 1447, month: 9, day: 1 });
  });

  it('is held to ±2 days and to known calendars', () => {
    expect(coerceHijriAdjust(5)).toBe(2);
    expect(coerceHijriAdjust(-9)).toBe(-2);
    expect(coerceHijriAdjust('1')).toBe(0);
    expect(coerceHijriCalendarId('nu')).toBe('tabular');
    expect(coerceHijriCalendarId('khgt')).toBe('khgt');
  });

  it('tells subscribers, once per real change', () => {
    const seen: number[] = [];
    const off = subscribeHijriCalendar(() => seen.push(hijriCalendarVersion()));
    setHijriCalendar('khgt', 0);
    setHijriCalendar('khgt', 0);
    setHijriCalendar('khgt', 1);
    off();
    expect(seen).toHaveLength(2);
  });
});

describe('the bundled tables', () => {
  const months = (t: NonNullable<ReturnType<typeof expand>>) => t.starts.length - 1;

  it('decode, and run from adoption to the end of 1500 AH', () => {
    const mabims = expand(data.mabims)!;
    const khgt = expand(data.khgt)!;
    expect([mabims.year, mabims.month]).toEqual([1444, 1]);
    expect([khgt.year, khgt.month]).toEqual([1447, 1]);
    const last = (t: NonNullable<ReturnType<typeof expand>>) => fromTable(t, t.starts[t.starts.length - 1] - 1);
    expect(last(mabims)).toMatchObject({ year: 1500, month: 12 });
    expect(last(khgt)).toMatchObject({ year: 1500, month: 12 });
    expect(months(mabims)).toBe((1500 - 1444 + 1) * 12);
  });

  it('take KHGT from Muhammadiyah through its last published month', () => {
    expect(data.khgtOfficialThrough >= '1492-11').toBe(true);
    expect(data.khgtSource).toMatch(/^https:\/\/khgt\.muhammadiyah\.or\.id\//);
  });

  it('list the government months too close to call, by name', () => {
    expect(data.mabimsUncertain.length).toBeGreaterThan(0);
    for (const m of data.mabimsUncertain) expect(m).toMatch(/^1(4[4-9]\d|500)-(0[1-9]|1[0-2])$/);
  });

  it.each([
    ['no table', undefined],
    ['a length that is not 29 or 30', { ...data.mabims, lengths: '9091' }],
    ['a start that is not a day', { ...data.mabims, start: '2022-02-30' }],
    ['month 13', { ...data.mabims, month: 13 }],
  ])('refuse %s, so the arithmetic calendar answers', (_l, raw) => {
    expect(expand(raw as never)).toBeNull();
  });
});
